### ISSUE TITLE
Include inhabitants for each country/region

### ISSUE THREAD

**Issue by calterras** [CSSEGISandData/COVID-19#1107]
Please, consider including the number of inhabitants of each country / region in the data.
Notice that one infected in Wuhan is equivalent to 8 in Germany or 30 in the USA.
therefore, apart from absolute values ​​we should be able to compare percentages.

Could we include a file like this?

Country/region; Population in millions

Germany; 83
Spain; 47
HongKong, China; 7
Californa, USA; 39

Should be an static file with about 300 rows.

**Comment by Ramesh-X** [comment]
Same as #1106

**Comment by calterras** [comment]
Posted by Ramesh-X in #1106

It is better to have population count of a country/region to get an idea on how badly the virus is spreading wrt the population.
I think that information is needed to be their in the system.

**Comment by flccrakers** [comment]
I'm trying to understand why it's important (no jugement).

The rapidity of spreading is only due quantities of contacts, so what seems to be important is the evolution of confirmed number. As I understood the only thing that we are trying to follow is the slow down of contamination number at word scale and/or locale scale. Once the daily number of case start to decrease, the COVID is loosing.   
What will bring us to know the percentage of people contaminated in a region, compared to confirmed case ? 
I don't get the logic behind that need, if you can give me more info, thanks

**Comment by calterras** [comment]
Hello Frank 

Of course you have now enough data to measure the loosing of COVID.

But in my opinion, managing the population number we could get additional info. If for example in Wuhan the 0.1% of population has been infected we could estimate that France, with similar sanitary measures would reach 67.000 cases previous to decrease.

I am not an expert, but maybe a way to detect if actions taken are good or bad, or even discover populations with genetic resistance. Isn't it ?

**Comment by flccrakers** [comment]
Hello Eduardo,

Thanks for the precision. 
So you mean it could be interesting to have that info (percentage of population) to try to make prediction ? 

I guess (and it's only an opinion base on my actual knowledge) you can also do the same by comparing the curves of confirmed in china -> look at the number of confirmed (by region or not) at the time they put everybody in quarantine. Look at the number of case 1 day after, 2 days after etc… and determine a percentage of augmentation per day from the starting point. Apply the same evolution to the French or any population and then you will get your prediction (which is not super precise, but can get an idea).

As the propagation is not linked to the size of the population, but the size of the confirmed and the interaction they have it seems to be even a better way to try to evaluate what is the number of confirmed to reach before the curve is supposed to start flattening.

But that work only if we apply the same mesure and only if the mesures are respected, otherwise, it can be delayed.

Concerning the probability te detect genetic resistance, it's hard to determine just with that info. There is so many parameters that can influence the evolution of the propagation that  saying that the percentage of confirmed is lower than in other place and concluded that it can be a genetic resistance would be very hazardous.

**Comment by Ramesh-X** [comment]
I think dashboard v2 has that feature. This should be closed..

**Comment by calterras** [comment]
ok 

nowI see that as not the whole population has been exposed, we should compare against exposed population, and that is not possible.

Thanks Frank and Ramesh, closing issue.
