### ISSUE TITLE
France recovered cases (12) not updated since a long time now

### ISSUE THREAD

**Issue by DrBob007** [CSSEGISandData/COVID-19#1220]
Hi All,
France recovered COVID_19 cases are remaining at 12 since a very long time now. This number is certainly wrong. However, I don't know where I can find the real numbers to change that, sorry.
Many thanks

**Comment by r-lomba** [comment]
Regarding France and US, I still can't get how they haven't put up a strategy to maintain a fairly correct stream of data regarding Recoveries. They are important Countries when it comes to estimate how the pandemic evolves

Apart from that, I find this site quite useful to integrate the stats from JHU:

https://www.worldometers.info/coronavirus/

Hopefully someone at JHU will realise that they have to structurally fix the stream of data for important Countries. Much respect for the huge work they are doing, but if you put up an infrastructure providing information to the world, you must correctly and regularly maintain it at least for the key Countries. Otherwise shut it down

**Comment by DrBob007** [comment]
Ooh, many thanks for your very usefull reply.
I fully agree.
Thanks for the worldometer web site.
