### ISSUE TITLE
suggestion consistant data

### ISSUE THREAD

**Issue by vparekar** [CSSEGISandData/COVID-19#1487]
understanding the data is being developed still, one suggestion was to have consistent data. 
if you look at 
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv 
and 
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv
- addition one number of columns is not an issue but the change of existing columns names is breaking developed code

**Comment by rsgoodwin** [comment]
Agree with the comment.   Since the time_series data no longer has US state level data,  I decided to use the daily reports,  and just concat them in long form,  but the column names do not align,  so I have to insert a "detect and correct" rename (not that hard in Python with pandas).

**3/22 and prior**
'Province/State', 'Country/Region', 'Last Update', 'Confirmed', 'Deaths', 'Recovered', 'Latitude', 'Longitude'

**3/23 and after**
'FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update', 'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active', 'Combined_Key'  

I do like the new column naming,  getting rid of '/' and spaces in names has some small programming benefits.   Not sure why Latitude and Longitude needed to change though (and why the dangling _ for Long.

Still missing US state level data,  which used to be in the time_series_19-covid-Confirmed.csv going back to 3/8/2020.   To get full US state level trend data now,  I would have to read both the time_series_19-covid-Confirmed.csv (get state data from 3/8 to 3/22) and the new daily reports,  but role it back up from county level to state level,  then merge...  which is probably what I will do.
