### ISSUE TITLE
Has the data source layout changed? I build a dashboard using the previous data, which had updates coming in from state and province first.  

### ISSUE THREAD

**Issue by Shalin-2020** [CSSEGISandData/COVID-19#1503]

**Comment by JNFoo** [comment]
Apparently so. Check the descriptions under the directories for info. The global recovered time series is also not maintained anymore because ... reasons. It broke most of our visuals :-( Some other members have posted alternative sites to check out and one even posted a conversion program source code to make the datasets easier to use.

**Comment by JNFoo** [comment]
Here are some deets: https://github.com/CSSEGISandData/COVID-19/issues/1250

**Comment by Shalin-2020** [comment]
Thanks for the information, would you have information to those links?

**Comment by JNFoo** [comment]
The only one I've used so far is https://covidtracking.com/
Just read the other threads from today and you'll see the same thing I did.

**Comment by Shalin-2020** [comment]
Thanks for that. Yes, I did find the same link but it only shows US data, I am after current global data.

**Comment by JNFoo** [comment]
The rest of the global data is in the same old directory with the files that have been retired. It's a new file format for confirmed and deaths. No recoveries. It's only missing the US state time series which is why I referenced the above link

**Comment by hippodribble** [comment]
See comment #1458 for Python code to reformat the new file data

**Comment by Shalin-2020** [comment]
Thanks for that, I'll have a play around with it.
