### ISSUE TITLE
Please stop misinforming people by feeding fake data

### ISSUE THREAD

**Issue by XaXaXa12345** [CSSEGISandData/COVID-19#1513]
Hi,
Italy, Spain, France, Switzerland are wrong.
You keep misinforming people by feeding absolutely fake data.
Close you poorly maintained junk project and let trustworthy providers, like www.worldometers.info/coronavirus/ do the job.

**Comment by Wikunia** [comment]
At least for Italy both show the exact same number so keep calm.
You might missed that they changed to a different file: (See #1250)
The file for the confirmed cases is here: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

**Comment by ttobis** [comment]
@AndreyBabkinFromSwarovski, you really do call someone's project a junk? Just don't use.

**Comment by AndreyBabkinFromSwarovski** [comment]
> At least for Italy both show the exact same number so keep calm.
> You might missed that they changed to a different file: (See #1250)
> The file for the confirmed cases is here: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

At least for Italy it's wrong since 2020-03-19 and up to date, so shut up.

**Comment by frchalaoux** [comment]
From where are coming the data from www.worldometers.info ?

**Comment by AndreyBabkinFromSwarovski** [comment]
> @AndreyBabkinFromSwarovski, From where are coming the data from [www.worldometers.info](http://www.worldometers.info) ?

They're using official sources only.
Their data management is much better than in this project, at least their figures match official records.

**Comment by skr47ch** [comment]
@AndreyBabkinFromSwarovski 
But do they report historical data?

**Comment by AndreyBabkinFromSwarovski** [comment]
> @AndreyBabkinFromSwarovski
> But do they report historical data?

Well, officially they don't (at least for free), but you can manually collect historical points directly from their site because they provide labelled historical graphs.

**Comment by kakadu21** [comment]
What are you talking about? All the series are exactly the same in worldmeters and here. I use data from worldmeters to update my sheet during the day before this datasheet is updated and it always matches perfectly.

**Comment by bjarkimg** [comment]
Well. I will trust a university better than any private corp. 
#fullofadds

**Comment by federico-vitale** [comment]
Official Italian data are available at https://github.com/pcm-dpc/COVID-19

**Comment by cbehren** [comment]
> > At least for Italy both show the exact same number so keep calm.
> > You might missed that they changed to a different file: (See #1250)
> > The file for the confirmed cases is here: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
> 
> At least for Italy it's wrong since 2020-03-19 and up to date, so shut up.

You are probably using the wrong files. 
https://github.com/CSSEGISandData/COVID-19/issues/1250

**Comment by dsr358** [comment]
> 
> 
> > @AndreyBabkinFromSwarovski, From where are coming the data from [www.worldometers.info](http://www.worldometers.info) ?
> 
> They're using official sources only.
> Their data management is much better than in this project, at least their figures match official records.

How are you able to verify that Worldometer is using "official sources"?

What do you know about Worldometer? They have a clean looking site displaying stats on 1) corona virus and 2) population.  Cool.

They are also headquartered in Shanghai, a place where access to information must follow the official narrative, otherwise your site gets shutdown. Worldometer is owned by Dadax, an "independent company" - what is that?  "We have no political, governmental, or corporate affiliation." Okay Dadax, please post your last 5 years audits for public review to verify this claim.  

You see Andrey, this repository is about as honest as it comes. Users from all over the world are fact checking data, verifying it, spotting inconsistencies and you have the audacity to criticize their hard work with some bogus claim? Shame on you. I guess you rather go for some info spoonfed to you by a site owned by China, because it looks clean and goes with whatever narrative you wish to believe.  If you don't trust the data than go kick rocks or do something about, just don't ridicule folks you never met as if you are some sort of omniscient guru who knows all about Italy's data on CV cases.

**Comment by hxslxd** [comment]
This  man@XaXaXa12345  is using newly registered account to advertise another website with ads...So sad

**Comment by mskymoore** [comment]
@XaXaXa12345  shill

**Comment by samirinux** [comment]
Guys, never mind the ignorant. Here is more serious question.
Where can I find the data of the recovered Covid-19 cases?

**Comment by samirinux** [comment]
Please, ignore my question. It looks it was added to repo in the mean time. :-)
