### ISSUE TITLE
 Inaccurate data sets, please remove and correct.

### ISSUE THREAD

**Issue by davidlyon3** [CSSEGISandData/COVID-19#1535]
If you are going to release these VERY SENSITIVE data to the public you need to make sure they are accurate. 

Files are inaccurate, please remove and correct them.
time_series_covid19_confirmed_global.csv
time_series_covid19_deaths_global.csv

**Comment by Bmr55** [comment]
Please be specific about the incorrect data in those files.

**Comment by kevinkiernan** [comment]
Values for column X3.23.20 are identical to X3.22.20 for all non-blank values.

**Comment by sandtreader** [comment]
It looks like the files have been renamed - see 
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/README.md

However since the last column is invalid it might be better to delete them - this would trigger warnings for those of us who are pulling them for display (woodfortrees.org).

Thanks!

**Comment by Bmr55** [comment]
#1250

**Comment by sandtreader** [comment]
Understood, leaving them non-updated is fine (and is common in climate data too) but the last column (23rd March) is *invalid*.  That's a different issue.
