### ISSUE TITLE
Canada Data missing from recovered

### ISSUE THREAD

**Issue by ablanch5** [CSSEGISandData/COVID-19#1656]
There is no date for recovered for country Canada. Also in confirmed and deaths "recovered" is listed as a region with Canada as one of the countries

**Comment by cipriancraciun** [comment]
It was announced in #1250 that the recovered data will not be available anymore (after March 22nd) due to logistics regarding reporting and scraping.

In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.
