### ISSUE TITLE
Error in daily update for March 26th 

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#1661]
Serbia has 7 (+3 new) fatalities in total and not 1 (-3 new). 

In your daily update for March 25th there were 4 fatalities.

**Comment by Borg19l71** [comment]
For Serbia: data (total cases,total deaths,total recovered,current active cases):
Year 2020 Date March 26 data should be 457,7,15?,435? instead of 384,1,0,383
Year 2020 Date March 27 data should be 528,8,15?,505? instead of 457,1,0,456
Year 2020 Date March 28 data should be 659,10,15?,634? instead of 528?,1,0,527?
I don't know the number of current recovered cases,so the question mark.

**Comment by Borg19l71** [comment]
#1839
