### ISSUE TITLE
Daily reports does not seem to be updated

### ISSUE THREAD

**Issue by sroyyors** [CSSEGISandData/COVID-19#1668]
hi, It seems the numbers per US state is no longer available. Can this be provided? Also I noted that the daily case reports are not being updated. I grepped reports for Wisconsin and they seem to be at 72 since Mar 22, 2020.

**Comment by cipriancraciun** [comment]
I have built a derived dataset based on JHU dataset, where (among other fixes and features) I also aggregate the data for US at both state and country level, and merge everything in a single dataset for easy usage:

* https://github.com/cipriancraciun/covid19-datasets
* I have described it in this issue #1281 or the readme in the repo above;

(I try as much as possible not to change the format too much, mainly I only add new rows and columns.)

**Comment by sroyyors** [comment]
hi, thanks. It seems the data organization change is documented here: https://github.com/CSSEGISandData/COVID-19/issues/1652
Is this where you have been getting the new stats?

**Comment by cipriancraciun** [comment]
@sroyyors I use as basis for my derived datasets only the JHU `daily_reports` data (as suggested in the first comment in that ticket).  (I am not using other external API.)

**Comment by sroyyors** [comment]
ok, but the issue was that the daily_reports were out of date. I grepped out cases for Wisconsin and they were all 72. How do you make sure the daily reports are being updated? This was last night, so maybe the issue was fixed?

**Comment by cipriancraciun** [comment]
@sroyyors I think there is a high pressure on the JHU team, especially since the entires US dataset is perhaps as long as the rest of the world one, and therefore some values might be out of date.  (But perhaps later tonight when they update it it will be fixed.)  (Regarding my own dataset, at the moment I consider the JHU dataset as the "source of truth" and I only clean and augment it.)

(Please don't use these datasets, or any other data source on the internet that doesn't come from governmental officials for important decisions.  Use them only for statistical / visualization purposes.)

**Comment by sroyyors** [comment]
ok, thanks, yes that is understandable. Yes, I am using it only for my own tracking. thanks.
