### ISSUE TITLE
Recovered cases file issues

### ISSUE THREAD

**Issue by imdevskp** [CSSEGISandData/COVID-19#1672]
Recovered cases file missing data from
Canada provinces
Timor-Leste, 
Syria, 
Mozambique

Other two file has this data

**Comment by cipriancraciun** [comment]
It was announced in #1250 that the recovered data will not be available anymore (after March 22nd) due to logistics regarding reporting and scraping.

In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.
