### ISSUE TITLE
New fields must be added to understand the crisis 

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#1677]
The 3 values we have to understand the crisis are not sufficient : Confirmed - Deceased - Recovered

As many countries discover often too late , the real issue is to count the hospitalized people and the people put in ICU 
Worldometers give  the ICU value
Official Italian and French sites give these 2 values at a region level ( In France at the Departement level)

It's time to change

**Comment by JiPiBi** [comment]
![image](https://user-images.githubusercontent.com/44967630/77741689-984c9000-7015-11ea-9a52-b401a14bd23a.png)

**Comment by JiPiBi** [comment]
French data

![image](https://user-images.githubusercontent.com/44967630/77741887-e792c080-7015-11ea-955c-87ad4e32cd40.png)

**Comment by JiPiBi** [comment]
Italian data

![image](https://user-images.githubusercontent.com/44967630/77742636-0fceef00-7017-11ea-9fe1-9e9ce49ca150.png)

**Comment by cipriancraciun** [comment]
Can someone point to a machine-readable (and reliable) dataset?

(I have already augmented the JHU dataset as described in #1281, and I could add these values to that.)

**Comment by JiPiBi** [comment]
For italy : link this well known site 
https://github.com/pcm-dpc/COVID-19
 
For France :
https://github.com/opencovid19-fr/data
in this repo : folder dist gives in one file data at different level of granularity 
there is an english read.me to explain the data with english translation of the fields

Good work !

**Comment by cipriancraciun** [comment]
@JiPiBi unless people start standardizing on a particular data-format (I mean a JSON or TSV schema), merging all these datasets will be a nightmare.

For example in order to merge, clean and augment the JHU dataset it took me about 3 full work-days.  (And the raw data was already available in a single semi-consistent format...)

**Comment by cipriancraciun** [comment]
@JiPiBi the repository for Italy that you've pointed at (https://github.com/pcm-dpc/COVID-19/) looks reasonable enough (although it would have helped if the fields and description would have been in English...)  (Perhaps if I have the time and energy I'll integrate it in my dataset.)

BTW, is this an official dataset?  (I.e. the ones that publish it are the italian authorities, or this is a volunteer project?)

(In order to augment that data I would also need a dataset with the population of each province / county.  Do you know of an official one?  Or, like in the case of US, I'll have to scrape Wikipedia...)  :)

**Comment by hamedmh** [comment]
Hi, the source is included in the repo as pdf-files.

**Comment by michim321** [comment]
Hi! I totally second this request! I also would like to see the data broken down by # hospitalizations (regular + ICU). @cipriancraciun the Italian data comes from the official source (Interior Ministry) and it's been really useful to me to understand trends/gravity of each individual category.
I hope this is possible to obtain at the state level, eventually, before hospitals go totally insane.

THANK YOU

**Comment by JiPiBi** [comment]
No reaction of JHU . But the issue in the real world remains 
I close
