### ISSUE TITLE
Can we change US to United States in Country/Region

### ISSUE THREAD

**Issue by aravindnc** [CSSEGISandData/COVID-19#1705]
Can we change US to United States in Country/Region to make it consistent name.

**Comment by cipriancraciun** [comment]
At this moment, given how many people are already using this dataset for their own projects, I would say this would be a really breaking change, that will throw everyone a step backward once more...

Do you have a specific reason for this change?  (In the end you can easily map it in your own processing.)

(I am not affiliated with the JHU team, but during the last 3 days I've seen countless issues due to minor changes like date formats, column names, etc.)

**Comment by aravindnc** [comment]
Yes. Understood. I can use local datamapping.
Thank you.
