### ISSUE TITLE
Add more precise localisation to a lot of countries

### ISSUE THREAD

**Issue by Rphad** [CSSEGISandData/COVID-19#1787]
Check the following dashboard : 
https://www.healthmap.org/covid-19/

It has much more precise info (administrative separation). They use this dataset : 
https://github.com/beoutbreakprepared/nCoV2019/tree/master/latest_data
More precision could be added

**Comment by oltdaniel** [comment]
@Rphad I think it is more than awesome to provide cooridantes to the countries than just the name. I hink other APIs will provide you well wnough with detailed data. I can be sure it is not @CSSEGISandData task to provide that detailed data. Combine APIs to provide our own instead of youst copying/mirroing data. Please close.
