### ISSUE TITLE
Province-Level for Germany

### ISSUE THREAD

**Issue by eopo** [CSSEGISandData/COVID-19#182]
Germany has now over 100 currently infected persons. The Robert-Koch-Institut (Federal Agency for Infections) has a list that is updated daily: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html
Maybe it is possible to add the province level to Germany on that base.

**Comment by iceweasel1** [comment]
The Robert Koch Institute is a disgrace, as is the Federal Ministry of Health. For weeks, half to whole days nothing has been updated. The last weekends nothing at all has been updated. Even since it really started this week in Germany, these two authorities have been the lame-assed ones.

Every federal state, i.e. every ministry of health of the individual federal states also makes, as it is funny, data hours or several days later only online.

Mostly, counties and cities that are affected were the first to provide official confirmation.

Currently, the 129 that the Robert Koch Institute states on its website as of 15:00 are outdated again. The communication outside of official opening hours and weekends with the own population is shameful and sad. Ridiculous is still politely expressed. The Robert Koch Institute and the Federal Ministry of Health can be completely forgotten.

You cannot rely on them.

**Comment by iceweasel1** [comment]
Sorry, but this had to be done now. :-)

**Comment by Rainmaker52** [comment]
I guess every country says that their government is reacting in the worst ways possible, and that all other countries have responded way better and more adequate. It is the same discussion in The Netherlands.

But, with regards to this request; may I suggest that, above a certain infection rate, regions are added to the country, providing the source datasource allows for it? So, if there is over 100 infections in a country (or, the limit is variable, such as 1 in 100.000 citizens), regions are added to (in this case) Germany?
As another example, South Korea has a very large number of infections (over 4000 at the time of writing), but doesn't have any further subdivision into regions or provinces either.

I see the [CSV ](https://github.com/CSSEGISandData/COVID-19/blob/master/archived_data/archived_time_series/time_series_2019-ncov-Confirmed.csv) which holds the source data, but this just lists very generic regions, such as "Mainland China".

What I cannot get from this, is where this CSV is coming from. If I look at the website quoted in your README for the [ECDC](https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases), it does not seem to list any specific regions. So, if that's the sole data source, adding provinces or regions might not be possible.

**Comment by eopo** [comment]
@Rainmaker52 Germany is really really bad on that point. For one of the infections, the first official place where information came out was the major's personal Facebook. The city's page followed a few hours later, an official press release the next day. I think that cannot be the way to go. (@iceweasel1 Press release for the case in Essen: https://www.essen.de/meldungen/pressemeldung_1361729.de.html )

Nonetheless I agree with @iceweasel1 that the RKI might not be the best source. It is accurate, but very very very slow. @iceweasel1 s repo seems to be a good way, the information is detailed enough for the map, sourced from different official sources and the sources are to be found in the list.

**Comment by iceweasel1** [comment]
Many thanks @eopo . I can only agree with your execution. Thanks for the link to Essen. I'll add that in the Essener case to my repo.

There have been other cases added today. I'm currently adding them to my list and uploading the new data to the repo.

**Comment by Rainmaker52** [comment]
Well, that's my point.

We can keep track of the numbers in our local region, by using information from media outlets, APIs or webpage scraping from official institutes (be sure to monitor the major's twitter account as well), local governmental organizations.

There's people willing to track this, and expose information via CSV, JSON or whatever. See the other "issues" in this repo for examples. That's what crowdsourcing is about. The problem is that, unless one of the maintainers from this repo responds, that information will not actually reach the map.

**Comment by iceweasel1** [comment]
@Rainmaker52 You mean something like this?

For Germany, I offer this: 
https://github.com/iceweasel1/COVID-19-Germany

It's currently only for confirmed cases. I do not yet keep a list of recoveries, as we do not have many recoveries (time period) yet. Fortunately, none have died yet.

**Comment by SeidChr** [comment]
Dashboard on province level for germany:
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

Overview of other Dashboards:
https://github.com/CSSEGISandData/COVID-19/issues/576
