### ISSUE TITLE
Recoveries for us 

### ISSUE THREAD

**Issue by ralucaandreeaoman** [CSSEGISandData/COVID-19#1831]
is there a file with recoveries for us counties/states? thank you so much.

**Comment by oltdaniel** [comment]
@ralucaandreeaoman Due to different data sources and not open sources of each country, collecting the data is pretty hard. @CSSEGISandData mentioned already in the data forma update, that there are no good sources for recovered sources. It is a crisis, and data sources can change every day, and result in different formats in here. Please close and just keep an daily eye on the commits in this repo for updates on the @CSSEGISandData side.

**Comment by ralucaandreeaoman** [comment]
Thank you. Ok. You can close the case.Regards,
    On Wednesday, April 1, 2020, 09:26:02 PM EDT, Daniel Oltmanns <notifications@github.com> wrote:  
 
 


@ralucaandreeaoman Due to different data sources and not open sources of each country, collecting the data is pretty hard. @CSSEGISandData mentioned already in the data forma update, that there are no good sources for recovered sources. It is a crisis, and data sources can change every day, and result in different formats in here. Please close and just keep an daily eye on the commits in this repo for updates on the @CSSEGISandData side.

**Comment by oltdaniel** [comment]
@ralucaandreeaoman You need to close, I have not any permissions.
