### ISSUE TITLE
Time series for US and Global. Updates at the same time?

### ISSUE THREAD

**Issue by rasa2k** [CSSEGISandData/COVID-19#1855]
Hi,

Is there any chance that all the time series could get updated at the same time?
Meaning that they would been aligned with the scope of dates.
Currently US's last record is 3/30 and Global is 3/31.
I'm trying to merge all the files and do some data transformation since the US data has been moved to a second file.

Secondly:
Could the columns of dates have the same date format in all time series files?
Currently US is m/dd/yyyy and global is m/dd/yy

Thanks. Awesome work btw.
/R

**Comment by oltdaniel** [comment]
@rasa2k The data strea @CSSEGISandData seems to have a certain amount of manual work, as they need to combine sources not updating in the same intervall. So, updates on GitHub will keep going to come on certain delays to each other. Currently, I persoally wait for the timeseries update for my application. But @CSSEGISandData does an amazing job due to the complains we all have for data format. So please close this issue to keep everything on focus. If they are able to do updates on the same time, I think they are more than smart enough to make the change.
