### ISSUE TITLE
Data format:

### ISSUE THREAD

**Issue by roohy466** [CSSEGISandData/COVID-19#1877]
Could you please keep the data formatting the same!! I do see now alot of US counties are not there anymore! why is that?

**Comment by oltdaniel** [comment]
The data is not reported equally by each country, state, city. It is hard to combine it into an well-defined data structure. @CSSEGISandData does its best job. So please suit your application each day/week to the changes here, as the data officialy reported changes every day too, Still it is the best source here to find data. So please close due to multiple duplicates complaining about the data format,
