### ISSUE TITLE
Will the schema keep changing?

### ISSUE THREAD

**Issue by kkchu791** [CSSEGISandData/COVID-19#1956]
Just wondering if the schema for the CSV files will keep changing?

**Comment by cipriancraciun** [comment]
Based on two weeks of experience, sadly the answer most likely is "yes".  :)

(However I understand "why" they keep changing the format, which has mainly to do with the inconsistencies "upstream" in the way countries and officials do the reporting...)

Therefore many have already built parsers that deal with the inconsistencies, and many have published their derived datasets.  For example I've described mine in #1281 which is also available at https://github.com/cipriancraciun/covid19-datasets

(In order to keep things tidy, if no-one actually answers this in say a few days, please close the report, as there are already countless reports like this...  Just see #1281 where I've linked a lot of them...)

**Comment by Lucas-Czarnecki** [comment]
Oh hi @cipriancraciun, nice to see you again. :) 

@kkchu791 there are no guarantees that JHU will keep their naming conventions consistent moving forward. And given how much work @CSSEGISandData puts in to make these data public - it's a tall order; folks should be prepared to do a little heavy lifting of their own. 

If you want a consistent schema, consider taking @cipriancraciun's advice.  I also keep a tidy repo of JHU that may be of interest [HERE](https://github.com/Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE) if you'd rather not spend too much time data cleaning.

**Comment by aquiot-inc** [comment]
I have created an API that delivers a JSON version of the global data, will soon be adding data for US states from the US data. [https://covid.aquiot.com/api/covid-19-data.php](https://covid.aquiot.com/api/covid-19-data.php)

You can visualize this data at [https://covid.aquiot.com](https://covid.aquiot.com)

**Comment by texadactyl** [comment]
@kkchu791 Schema?  What schema?  (=:  The JHU fols seem to be maintaining data in spreadsheets.  They might think that the headings are just comments!  

Seriously, I am not criticizing them.  They're working hard.

You seem to be doing some Javascript.  I'll bet that one of your JS libs can read, extract, and reorder the columns any way you like.  In Python, people frequently use ```pandas readcsv()``` for that sort of job.

**Comment by jjbenes** [comment]
@kkchu791 I uploaded some front-end code at https://github.com/jjbenes/covid19 to read JHU's CSV files as Pandas data frames. There are just two Python files. Only one of them will have to change if JHU changes their spreadsheet format. 

This code helps create U.S. maps like these: https://first-principles.ai/covid-19/map.html and https://first-principles.ai/covid-19/per-capita-map.html. 
![Screen Shot 2020-04-05 at 5 44 29 AM](https://user-images.githubusercontent.com/62985029/78499136-ce6bcd00-7703-11ea-92ef-c469c06c9575.png)
