### ISSUE TITLE
France: still wrong numbers

### ISSUE THREAD

**Issue by alfkoehn** [CSSEGISandData/COVID-19#2038]
We still have the problem with France as extensively discussed yesterday, see e.g. https://github.com/CSSEGISandData/COVID-19/issues/2005. One reason for the difference in numbers of confirmed cases is that *potential* cases are also included, where in my understanding this should only be *confirmed* cases.

According to source [1] and [2], we have the following numbers (Ref. [3] requires adding together all territorial regions but seems to end up with very similar values):

    confirmed cases: 74390

[1] https://github.com/opencovid19-fr/data/blob/master/ministere-sante/2020-04-05.yaml
[2] https://dashboard.covid19.data.gouv.fr/
[3] https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200405-sitrep-76-covid-19.pdf?sfvrsn=6ecf0977_2

**Comment by misterbenj34** [comment]
I confirm

**Comment by Philliec459** [comment]
The bug shows in JH website  (https://coronavirus.jhu.edu/map.html) a Daily Increase that on April 3 for France of 25,600 Confirmed Cases for that day. Possibly there is a blending of territories or whatever, but this issue does make it impossible to forecast for France

**Comment by JiPiBi** [comment]
It is not a real bug. Because these values come from French SPF
These values corresponds to  cases in nursing homes , they are not clearly suspected or confirmed , because when people are symptomatics in these nursing homes , they are not always tested.  
For the moment French SPF gives separately hospitals(confirmed)  and nursing homes (confirmed +supected) values

**Comment by alfkoehn** [comment]
Fixed: https://github.com/CSSEGISandData/COVID-19/issues/2094#issue-597470646
