### ISSUE TITLE
Some countries don't have data in total, only Provinces/States.

### ISSUE THREAD

**Issue by Patryk01** [CSSEGISandData/COVID-19#2076]
Like Canada or China.

**Comment by cipriancraciun** [comment]
Countries with provinces don't have totals.  In fact countries with provinces, that do have "country" level rows are unassigned / unknown values.

Therefore if you want to know the total for a particular country, you'll have to sum the values.

That being said, I have derived the JHU dataset as described in #1281, and available at https://github.com/cipriancraciun/covid19-datasets to contain country level (continent and sub-continent level) sums.

BTW, there are countless other issues on this topic, like for example #1743, therefore in order to help the JHU team keep things tidy, I would suggest closing this ticket and follow one of the other duplicates.
