### ISSUE TITLE
About confirmed cases in France

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#2094]
Update 4/16: after communicating with solidarites-sante.gouv.fr, we decided to make these adjustments based on public available information. From April 4 to April 11, only "cas confirmés" are counted as confirmed cases in our dashboard. Starting from April 12, both "cas confirmés" and "cas possibles en ESMS" (probable cases from ESMS) are counted into confirmed cases in our dashboard.

Original: Translating press conferences and case reports invariably results in the loss of nuance and detail. In a daily briefing on April 3rd, the French health ministry director reported that there were 17,827 confirmed or suspected cases of COVID-19 in nursing homes. Data aggregation sites that rely on media reports to report case counts, such as ourselves, Worldometer, and BNO, followed the conclusion from this [Reuters article](https://www.reuters.com/article/us-health-coronavirus-france-toll/french-coronavirus-cases-jump-above-chinas-after-including-nursing-home-tally-idUSKBN21L3BG) that the nursing home cases were being reported separately from the confirmed case total and thus the two values should be summed to reach the true number of cases. This was also facilitated by the [French Health Ministry](https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde) reporting "confirmed cases" and "cases in social or medical-social establishments (nursing homes)" as two different quantities. After careful consideration and extensive research, we cannot confirm beyond a reasonable doubt that these two categories are mutually exclusive. For that reason, and in the interest of accuracy, we are reverting our numbers to reflect only those confirmed by the French Health Ministry and will be retroactively adjusting our time series data. We will continue to monitor the situation and will adjust our approach if a more appropriate way forward presents itself.

**Comment by cipriancraciun** [comment]
@CSSEGISandData also regarding invalid numbers for France, it appears that the daily reports for `03-23-2020.csv` for `French Polynesia` includes also the values for the `France` mainland.  (The `series` files seems to be correct.)

For example:
* in `03-22-2020.csv`:
~~~~
,,,France,3/22/20 23:45,46.2276,2.2137,16018,674,2200,13144,France
,,French Polynesia,France,3/22/20 23:45,-17.6797,149.4068,15,0,0,15,"French Polynesia, France"
~~~~
* in `03-23-2020.csv`:
~~~~
# France missing
,,French Polynesia,France,2020-03-23 23:19:21,-17.6797,-149.4068,19874,860,2200,16814,"French Polynesia, France"
~~~~
* in `03-24-2020.csv`:
~~~~
,,,France,2020-03-24 23:37:15,46.2276,2.2137,22304,1100,3281,17923,France
,,French Polynesia,France,2020-03-24 23:37:15,-17.6797,-149.4068,25,0,0,25,"French Polynesia, France"
~~~~

I.e. for 23rd the `France` row is missing, and the numbers for `French Polynesia` jump drastically from 22nd, but then go back again for 24th.

**Comment by ivandebono** [comment]
This is the data source you should be using: 
https://www.gouvernement.fr/info-coronavirus/carte-et-donnees

**Comment by greg-minshall** [comment]
also (if this is better than opening a new case... :), the 04-09-2020.csv daily file has an odd French entry:
```
00250,,,France,2020-04-09 23:02:19,46.2276,2.2137,117749,12210,23206,82333,",,France"
```
(that leading "00250" seems bogus.)

**Comment by yetzt** [comment]
you're back to the wrong number:
![Screenshot](https://imgur.com/UvdL3Gd.png)

**Comment by yetzt** [comment]
![meme](https://i.imgflip.com/3w40rb.jpg)

**Comment by alfkoehn** [comment]
Just to have the correct (i.e. official from other sources) numbers here:

The data here says: 117749
Number in other data sources [1,2]: 86334

[1] https://dashboard.covid19.data.gouv.fr/
[2] https://github.com/opencovid19-fr/data/blob/master/ministere-sante/2020-04-09.yaml

**Comment by boogheta** [comment]
If France were releasing confirmed data with the same accuracy they do for hospital cases, things would be so much simplier, but hey, that's how we do in France with official data, never simple...

**Comment by JiPiBi** [comment]
@boogheta 
Perhaps as french yourself,  could you explain the situation of nursing homes, instead of inappropriate comment.

**Comment by boogheta** [comment]
@JiPiBi I'm not sure how this is inappropriate. France has a long history of cultural lack of transparency and releasing hardly valid data (see for instance companies register data...).
The lack of transparency from the government on nurses home situation makes it hard to explain it properly, but basically people are not all tested, and as soon as a spread is observed in a nursing home, all sick people in this home are accounted. This does not legitimate government not publishing detailed figures coming from these since they do account them in their total national confirmed cases and in a separate national deaths count.

**Comment by ivandebono** [comment]
> The lack of transparency from the government on nurses home situation makes it hard to explain properly, but basically people are not all tested, and as soon as a spread is observed in a nursing home, all sick people in this home are accounted. This does not legitimate government not publishing detailed figures coming from these since they do account them in their total national confirmed cases and in a separate national deaths count.

Do you mean that "cas confirmés" is over-reported here:
https://www.gouvernement.fr/info-coronavirus/carte-et-donnees ?

**Comment by boogheta** [comment]
I wouldn't go as far as "over-reported", but according to the way it is accounted in nurses home and what the government announced, it should rather be called "cas confirmés ou fortement suspectés" yes.

**Comment by JiPiBi** [comment]
@boogheta 
I disagree, the cases in nursing homes are separatedly presented on the official dashboard and not aggregate in the national confirmed cases for the reasons you gave.
Secondly the people from ESMS   who died  in hospitals are in the hospital death counter and the people died outside hospital are in the death global counter.

**Comment by boogheta** [comment]
@JiPiBi No, according to official speeches, the cases of deceased are presented separately only, not the cases of confirmed. This is coherent with the fact that hospitals do not report data on confirmed: deceased must be added from both sources (hospitals and ehpad), whereas there is no breakdown for confirmed (neither by source nor by region), only a global figure which accounts for everything, even though numbers are not accounted in the same way.
This is exactly the point @CSSEGISandData is explaining in this issue and why they are reverting (tonight?) to the good value which is around 90 000 and not 110 000 as was reported over the past week but not touching the number of deceased which is the good one.
You can read more about it in French here: https://www.liberation.fr/checknews/2020/04/05/covid-19-pourquoi-des-sites-evoquent-90-000-cas-en-france-contre-68-000-au-bilan-officiel_1784232

**Comment by JiPiBi** [comment]
@boogheta 
No about what ??
What did I say that is not coherent with the following yesterday's dashboard 

 
![image](https://user-images.githubusercontent.com/44967630/79011418-49017600-7b64-11ea-856d-6897122e156d.png)

**Comment by yetzt** [comment]
As far as ai understand it, the ESMS/EHPAD cases are not in fact confirmed cases, but consist in fact in part of speculation. therefore adding them to a data field named _Confirmed_ is deeply problematic. If there is no valid conclusive official count of definitely confirmed cases outside the official number, there is nothing that can be added without setting fire to any meaning.

**Comment by JiPiBi** [comment]
@yetzt 
You are right , the 31415 are not for the moment sorted between confirmed and suspected , a ratio of 1/3 of confimed has been annouced yesterday and we are waiting on more accurate values 
In France there are about 7000 nursing homes , which where not in the network of health system .
This is the explanation of huge increase  in death cases because many of these old people died very quickly in the nursing homes and not in the hospitals.
It seems that the people could be in quite good form and some hours later became very sick abd die
People after a certain age can't support ICU  even if there are in an hospital. 
Imagine to be 2 or 3 weeks unconscious on the belly . Even for young people it is hard to recover, it may last weeks or moths .
In hospital about 25-30% of people under 80's are in ICU . Above 80's  only about 10% are in ICU . 
And they represent the main part of deaths ...

**Comment by JiPiBi** [comment]
Update this evening
![image](https://user-images.githubusercontent.com/44967630/79016170-97b40d80-7b6e-11ea-9205-4406e7c27c39.png)

**Comment by ivandebono** [comment]
I have another question: What is the total number of recovered? "Retours à domicile" means patients released from hospital. What about those who had the virus but were never hospitalised? Do we just use this?
recovered = total infected - total dead - active cases

Can we find a figure for total active cases somewhere?

**Comment by JiPiBi** [comment]
Recovered here is clearly   recovered after being hospitalyzed.
People who had mild symptoms were asked to stay at home : mainly not tested, in tight contact with their doctor to see if the sickness is evoluting.  
In the family , there is also a possibility that another person is positive but these values are not known and if they recover at home these values are also not known and probably will never been known.
So as we dont know how many people where infected , the notion of recovered means nothing for the moment . Only serologic tests could give a real  idea of the situation .

See on worldometers the informations about a test in Germany

A study by the University of Bonn has tested a randomized sample of 1,000 residents of the town of Gangelt (an epicenter of the outbreak in Germany) and found that 2% of the population was currently infected and 14% were carrying antibodies suggesting that they had already been infected — whether or not they experienced any symptoms. Eliminating an overlap between the two groups, the team concluded that 15% of the town have been infected with the virus [source]

If these findings are correct, Germany’s actual death rate could be as low as 0.22% (2,607 deaths / (2,607 cases that have resulted in death + 1,172,000 cases that have resulted in recovery)). Assuming 14% of the German population of 83,700,000 (1,172,000 people) have been infected and have recovered.
Source : https://spectator.us/covid-antibody-test-german-town-shows-15-percent-infection-rate/

**Comment by ivandebono** [comment]
The notion of recovered is very clear. There are many countries in Europe where people who tested positive and had mild symptoms were made to self-isolate at home, then tested again periodically, and finally declared recovered when they tested negative (the Prince of Wales is one example). They were then added to the tally of recovered cases. 

If France only considers as recovered those patients who were released from hospital, it is under-reporting recoveries.

**Comment by JiPiBi** [comment]
You are right. But Prince of Wales is not the good example. John Doe on SmallCity has not the same attention :-)

People that recovered alone at home have been rarely tested positive, because lack of tests at the beginning.
I m not justifying, I am explaining the values.

**Comment by Clumpton** [comment]
Just to make it 100% clear. Here in France they are currently mainly testing people admitted to hospital with advanced symptoms, front-line medical staff (plus politicians etc.). The general public are not being tested even if symptomatic. If a nursing home resident falls ill, are hospitalised and test positive then the whole home is classed as 'possible'. 
The "recovered" cannot include people who self-isolated and got well since they were never confirmed in the first place (French logic).
The govt. have announced the start of 'massive' testing in nursing homes, so those 'possibles' will gradually turn into 'confirmed' - this means that we should not include them in the statistics at the moment as they will eventually end up being counted twice!
The French count includes ALL confirmed cases as per this graph (from 01:00 CEST 2020-04-11)
![canvas](https://user-images.githubusercontent.com/59048696/79029562-263b8580-7b95-11ea-8f8d-3cfeac4c1ba8.png)
With this key
![key](https://user-images.githubusercontent.com/59048696/79029573-30f61a80-7b95-11ea-82e0-267bad716f5c.JPG)

Translated it reads (from top to bottom)
- Deaths in nursing homes (magenta)
- Deaths at hospital (red)
- Currently in ICU (blue)
- Other hospitalizations (azure)
- Recovered and discharged (green)
- Others (i.e. tested positive but never hospitalized) (orange)

I hope that helps clarify the matter

**Comment by ivandebono** [comment]
Thank you. 

The different reporting methods make forecasting harder. I would have expected standardised reporting at least across the EU, or what remains of it.

**Comment by JiPiBi** [comment]
@Clumpton 
Nothing to add to your explanations.

Remarks: 
- I hesitated a bit to understand autre hospitalisation , suggestion to call hosp en rea, hosp hors rea,   and final autre: non hosp or confirmes a domicile. But details

- Add décès in hosp+ recovered+ currently hosp and compare to 65420. I dont understand the result. 

- add guéris  decedes in hospital and hospitalises and compare to the total

**Comment by JiPiBi** [comment]
@ivandebono 
Agree with the reporting differences making it hard to compare. For example, knowing new ICU  and new hosp is very important. 
At the beginning cases and deaths are important, in the middle, the exponential increase and quantity of beds and  ICU  at the peek  the new hosp and new ICU, and after I suppose all the dead includind surmortality by class of age and the percentage of infectes people 

I think WHO should now propose common reporting.

**Comment by Clumpton** [comment]
>     * Add décès in hosp+ recovered+ currently hosp and compare to 65420. I dont understand the result.

I don't understand where you get 65240 from?
- Add all the figures and you get 90676 which is total confirmed cases (dead, alive, cured, in and out of hospital).
- Add the two 'red' figures and you get 13197 which is total deaths (a subset of confirmed cases)

**Comment by JiPiBi** [comment]
Look above, I put yesterday the most recent informations. There are 6 colored cells from SPF.

**Comment by Clumpton** [comment]
@JiPiBi 
OK I see now, that 65240 cell is the total over the pandemic, if you look at the 3rd line it says "dont 31267 en cours" (of which 31267 are currently in hospital).
Add 32167 (current), 24932 (number discharged) and 8598 (hospital deaths) you get 64797 - a disparity of 443 - perhaps those are cases that were hospitalised and tested negative?

**Comment by JiPiBi** [comment]
I got my issue to understand this gap, except that the current value for hosp is 31267(not 32167) and the difference is 623 persons.
It was almost the same 2 days ago.
There is an hypothesis that some of them could be linked to people sent to other regions, because it seems that they are counted again as new for the new hospital.
Question asked without answer for the moment.

**Comment by Clumpton** [comment]
Oops sorry about that slip. The hypothesis of the hospital changes counting twice sounds quite likely.

**Comment by ivandebono** [comment]
> The "recovered" cannot include people who self-isolated and got well since they were never confirmed in the first place (French logic).

Can you confirm, then, that everyone who tested positive was admitted to hospital.

And if you include "possible" cases with the grand total of infections, why not include "possible" cases with the grand total of recoveries? In statistics we call it systematic bias.

**Comment by Clumpton** [comment]
@ivandebono 
> Can you confirm, then, that everyone who tested positive was admitted to hospital.
Of course not, many have self-isolated, but SO FAR in France the huge majority of tests have been done on people exhibiting symptoms that prompted hospitalization.
I am fully aware that the actual situation in France is forcibly far worse than indicated by the statistics due to insufficient testing.
The grand total of recoveries is (as stated above, and as far as I know) those who have been discharged from hospital. I suspect that the govt. doesn't currently have the faintest idea of how many have recovered in nursing homes or in self-isolation, so there are no possible cases to include in recoveries. So the systematic bias exists only if you insist on including a figure for "possible" cases in the confirmed cases while being unable to include or estimate the "recovered possible cases" in recoveries.

Please remember that these "possible" cases are a number pulled out of the air by a minister. Probably (N° of Homes with a case) * (average occupants in homes) * (90% infection rate).

Anyway if Johns Hopkins wishes to insist that France has 133k while the French govt. says 95k they will only lose all credibility in France, all while increasing the paranoia that the French people have about being lied by their govt.
That's me finished.

**Comment by JiPiBi** [comment]
Do you really think that the number of confirmed or recovered is so important now,  you dont really know both values...
Even deaths are unknown, home dead people  covid suspected are not tested...
You will only measure later surmortality...

IMHO what is more important now  is  the  number of hospitalyzed in or out ICU, and the evolution of these values, day after day.

**Comment by Clumpton** [comment]
@JiPiBi 

I agree I don't know why people are wittering about possible recovered etc.

**Comment by ivandebono** [comment]
Of course it's important. When you try to fit epidemiological models to the data, you want your data to be as accurate as possible. That's basic statistical science. 

If you're making policy based on the fitted models, it becomes even more vital.

**Comment by JiPiBi** [comment]
But when data are not available, what can you do ?

Do you really think that chinese data were faithfull and helped other countries to prepare themselves? 
At first , people said, its China, they have strange habits with animals and the epidemic kills only old and already very sick people. Comorbidities as they said.

After, it's the turn of Italy, people say , they have no modern hospital  and they have so many old people and olds live in the same house than youngs. Italian are also  so latin...
But Lombardia is not a third world region...
And after in France you meet difficulties with a region, you discover that you have not enough masks, not enough tests, and people in nursing homes are not well protected.

It seems that countries never learn from the previous infected ones if you look at the situation in the US.
They only know to apply confinement and they  add economic troubles to health troubles.

In Japan , there is no confinement, there are no many tests , the cities are crowdy and they have few deaths.

Italy : many tests, many deaths
Germany: many tests, few deaths
Japan: few tests, few deaths.

Is there a model fitting all that situations ?

Moreover, what seems important in these epidemic is local red hot situations : every country has its Wuhan and its Hubei. In France we have 3 or 4 regions with difficulties. In Italy, there is Lombardia and Bergamo and they dont represent the whole country. So you need to be more specific than the country scale.

And now  apart from statistics, there is a simple fact , how do you deal with a huge arrival of very sick people in the same hospital, you are  in a scale of time where every hour is important  ?
 
So I dont see for the moment how data can help to deal with such a crisis, if you are not prepared culturally at first and well equiped in second .

But strangely , small countries like Portugal, Croatia , Austria have very good results. 
Can data help to understand all that diversity and make usefull forecasts ?
Some days ago, we saw that the results were better in Italy. But even Italian descent is quite chaotic. 
Could data explain that?

**Comment by JiPiBi** [comment]
Pls , Look at the new hosp evolution in Italia.
Can model show the real tendancy , I dont speak of the successive peaks but the general form
Some days ago you see a descent and now it becomes  flat but at a high level 
![image](https://user-images.githubusercontent.com/44967630/79141367-f6b99280-7db9-11ea-9b20-e911e23806a4.png)

**Comment by Clumpton** [comment]
I said that I was going to shut up, but UK has just revealed 521 extra deaths in care homes that are not included in official figures. Additonally : 

> HC One, which operates about 350 homes, said that as of 8pm on Monday there had been 311 deaths from confirmed or suspected Covid-19 with outbreaks in two thirds of its homes. MHA, a charitable operator, said there have been 210 deaths across 131 homes, with outbreaks in about half of its homes.

So if we assume a 10% mortality rate:
- 311 deaths in 2/3 of 350 homes = 3110 infected
- 210 deaths in 1/2 of 131 homes = 2100 infected

So we could **estimate** 5210 extra infected.
Now lets guestimate that between 1/2 and 2/3 of the **430 000** people in 10 819 **other** care homes in the UK are also infected at a rate of 80%. That would give us anywhere between 176 000 and 234 000  extra cases.

Can you see where I'm going with this? Should we unilaterally add 5210 extra cases the the UK's figure?

If we do, why don't we add another 200 000 for all those other care homes.

Of course we wouldn't do this! None of the approximations I have made are justified by fact nor statistically valid. **So why the F do we add similar guessed-at figures for France?**

**Comment by JiPiBi** [comment]
@Clumpton 
I read your comment about manual writing , are you evocating French issues in Marseille city ?
If it is the case , in my knowledge , the issue was only there in Marseille , for the  registry office of the city , who  cannot  transmit automtaicaly   the  informations (covid or not, deaths or births) and only INSEE values are affected (delayed) , not hospitals one

**Comment by Clumpton** [comment]
@JiPiBi 
Yes I was thinking of the problems in the Bouches de Rhône.

Whatever there will always be some small differences in reporting due to delays etc. Have you noticed the "Sunday Effect" on French cases? Nearly always a drop on Sunday and then an uptick on Monday.

**Comment by JiPiBi** [comment]
Yes but even in Italy results are erratic. See above. I fear that everywhere the descent slope could be sometimes desperating.For me it is due to successive new infections even at region's level.It s a long way in front of us.
-------- Message d'origine --------De : Clumpton <notifications@github.com> Date : 14/04/2020  13:29  (GMT+01:00) À : CSSEGISandData/COVID-19 <COVID-19@noreply.github.com> Cc : JiPiBi <jpbozo@hotmail.fr>, Mention <mention@noreply.github.com> Objet : Re: [CSSEGISandData/COVID-19] About confirmed cases in France (#2094) 

@JiPiBi

Yes I was thinking of the problems in the Bouches de Rhône.

Whatever there will always be some small differences in reporting due to delays etc. Have you noticed the "Sunday Effect" on French cases? Nearly always a drop on Sunday and then an uptick on Monday.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/CSSEGISandData/COVID-19/issues/2094#issuecomment-613386338",

"url": "https://github.com/CSSEGISandData/COVID-19/issues/2094#issuecomment-613386338",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by JiPiBi** [comment]
FYI news about Confirmed and Possible in nursing homes seem to be detailled now 

https://solidarites-sante.gouv.fr/IMG/pdf/point_de_situation_du_14_avril_2020.pdf

What is new for me is that all confirmed cases are included in the official confirmed counter and the Possible are counted separatly .
So the official Confirmed value remains available.

**Comment by boogheta** [comment]
Hi @CSSEGISandData, it seems like the correction announced here was introduced yesterday, but only for April 14th data and not for the past days.

As a result, the number of confirmed cases is surprisingly decreasing as of today, with a negative daily change as we can see on my dashboard using your data:

[![france_april14](https://user-images.githubusercontent.com/1822297/79326224-c89b9600-7f12-11ea-8417-2a0fa35e16c5.png)](https://boogheta.github.io/coronavirus-countries/#confirmed&places=France&alignTo=deceased)
[![france_april14_2](https://user-images.githubusercontent.com/1822297/79326231-ca655980-7f12-11ea-8d9a-2dd02efe18bf.png)](https://boogheta.github.io/coronavirus-countries/#confirmed&daily&multiples&places=France&alignTo=deceased)

Do you plan on correcting also the data for the past days, or will it remain with this inconsistency?

**Comment by boogheta** [comment]
Thanks for tonight's correction!

**Comment by CSSEGISandData** [comment]
Update 4/16: after communicating with solidarites-sante.gouv.fr, we decided to make these adjustments based on public available information. From April 4 to April 11, only "cas confirmés" are counted as confirmed cases in our dashboard. Starting from April 12, both "cas confirmés" and "cas possibles en ESMS" (probable cases from ESMS) are counted into confirmed cases in our dashboard.

**Comment by Clumpton** [comment]
Good news!

**Comment by cipriancraciun** [comment]
@CSSEGISandData I still see that the French Polynesia issue reported above was not solved:
https://github.com/CSSEGISandData/COVID-19/issues/2094#issuecomment-611744632

**Comment by yetzt** [comment]
why count "_cas probables en EHPAD et EMS_" as confirmed cases when there is "_cas **confirmés** en EHPAD et EMS_" [in the dashboard](https://dashboard.covid19.data.gouv.fr/)? this makes no sense!

**Comment by yetzt** [comment]
As predicted, your data is useless now. Negative number of new cases, good job.

![Screenshot](https://imgur.com/xVC2vCO.png)

**Comment by boogheta** [comment]
"useless" seriously? Do you realise how disrecpectful that is? how much time and dedication they have to invest to produce data of quality that we are all reusing?
Of course there are occasional issues and they fix it progressively (the whole point in this thread was fixed already, the spike you're pointing is a different one...).
But we're not talking about HMO here, but a research lab, doing this freely. They have no responsibility to do anything whatsoever... If you're not happy with it, no one forces you to reuse this dataset, feel free to maintain your own (and understand the time and manpower it takes maybe...).
Thanks again @CSSEGISandData!

**Comment by yetzt** [comment]
@boogheta yes, useless. imagine calculating an increase rate with sinking data, which should by definition never happen. i don't have to respect anyone insisting on publishing unusable mislabeled data and i will proactively disrespect anyone not giving a fuck about deliberately misinforming the public.

**Comment by boogheta** [comment]
Well, don't use it and produce your own data then...

**Comment by Clumpton** [comment]
I told you weeks ago that cases would get counted twice if you carried on like that!
No disrespect, but after been accused of ignoring (or promoting) statistical bias I took my bat home because it was disrepectful!

**Comment by yetzt** [comment]
@boogheta i do. but all the people relying on this data have a right to know that this data is faulty and any analysis of this data is flawed because of upstream ignorance.

**Comment by boogheta** [comment]
Well luckily you said that on a closed issue, so the people will know for sure. Thanks for your good service of such better quality! :roll_eyes: 
Haters gotta hate...

**Comment by Clumpton** [comment]
More seriously though, what do we do about the French data? It is now quite complete giving both confirmed cases & deaths in hospitals and care homes. Additionally we have the "suspected" cases in care homes which have recently been omitted for a couple of days.
Counting ALL  cases (confirmed and suspected) is all very well and good but if people (read politicians) start trying to compare countries on this basis it all goes wrong. On the face of it the crisis in the UK is far less than in France - but this is entirely due to unreported equivalent data in the UK where they apparently have no idea of how many are dead or infected in care homes.
I say - take out those "suspected cases" in the French data that were added in on 4/12/20 and remember that the first line of the French data includes ALL confirmed cases and deaths - including care homes
![image](https://user-images.githubusercontent.com/59048696/80195375-076cd280-861c-11ea-8cec-2f3e1d861f37.png)

**Comment by traut21** [comment]
At least try to get it clean within a country.

negative new numbers are just a no go without any kind of explanation.
