### ISSUE TITLE
St. Martin and St. Barthelemy missing?

### ISSUE THREAD

**Issue by kdlange** [CSSEGISandData/COVID-19#211]
2 confirmed cases in St. Martin and 1 case in St. Barthelemy are not listed on the tracker.  Is this because they are listed as a French overseas territory?  If not and when able please add.

https://www.miamiherald.com/news/nation-world/world/americas/article240781521.html

**Comment by RedZorsha** [comment]
Hello, as far as I inox all French casse are counted under "France".
I also think it would be interesting to split this "all-in-one" number due to number of overseas french locations: Europe, South America, Africa, West Indies, Polynesia...
Don't you think it may be interesting and really more accurate ?
(By the way I'm french ;) )

⁣Télécharger BlueMail pour Android ​

Le 3 mars 2020 à 20:54, à 20:54, kdlange <notifications@github.com> a écrit:

**Comment by CSSEGISandData** [comment]
Updated! Thank you for the notification.
