### ISSUE TITLE
France data is progressively diverging from other sources 15/4

### ISSUE THREAD

**Issue by just2610** [CSSEGISandData/COVID-19#2226]
Attached is a summary of country totals from the dataset

<img width="684" alt="image" src="https://user-images.githubusercontent.com/41932947/79401635-3e0f7100-7fbc-11ea-98c9-4e2a7ad7eeee.png">

This is from worldometers

<img width="684" alt="image" src="https://user-images.githubusercontent.com/41932947/79401689-5f705d00-7fbc-11ea-8e10-e120ddf6cf2a.png">

Note France is showing as 147,863 on worldometer and 134,582 on the John Hopkins dataset. This is not a timing issue - the number is progressively diverging from the reported numbers for France in other datasets. please can you do a one time adjustment and review the source?

**Comment by GerardoRTobar** [comment]
Please can you make this happen? @CSSEGISandData France has already 3 days of having wrong data

**Comment by mendes-jom** [comment]
Please note  that total  for France on 14 April is lower than on the 13 Th !.....
Please correct.
Thanks a lot.

**Comment by steveNash12** [comment]
in time_series_covid19_confirmed_global.csv file
France 
 14/4 is 136779 
15/4 is 130253
-6526

![image](https://user-images.githubusercontent.com/46519675/79403640-0dcad100-7fc2-11ea-8f15-eddf47a9685a.png)

**Comment by Aureuum** [comment]
Does anybody know where Worldometers get their data from?
Their figures for France are about 40k higher than Wikipedia's.
I would trust Wikipedia's more since they get it from the official ministry of France.

**Comment by just2610** [comment]
@Aureuum the source seems to be : https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde

**Comment by Aureuum** [comment]
@just2610 thank you, the figure there says 106,206 cases for 4/15.
Why would Worldometers then say about 40,000 higher?

**Comment by yetzt** [comment]
official source: https://dashboard.covid19.data.gouv.fr/

**Comment by Aureuum** [comment]
Since they don't seem to fix it, you can just replace your data with this:
4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20
56989,59105,64338,68605,70478,74390,78167,82048,86334,90676,93790,95403,98076,103573,106206

**Comment by yetzt** [comment]
yeah, @CSSEGISandData stick by their mistakes, even when they announced to fix em.

**Comment by CSSEGISandData** [comment]
Update 4/16: after communicating with solidarites-sante.gouv.fr, we decided to make these adjustments based on public available information. From April 4 to April 11, only "cas confirmés" are counted as confirmed cases in our dashboard. Starting from April 12, both "cas confirmés" and "cas possibles en ESMS" (probable cases from ESMS) are counted into confirmed cases in our dashboard.

**Comment by yetzt** [comment]
why count "_cas probables en EHPAD et EMS_" as confirmed cases when there is "_cas **confirmés** en EHPAD et EMS_" [in the dashboard](https://dashboard.covid19.data.gouv.fr/)? this makes no sense!

**Comment by WildH0g** [comment]
@CSSEGISandData I hope you change your mind and will count only confirmed cases for consistency. Having a mix of both is screwing with the dataset

**Comment by Aureuum** [comment]
I agree. For a valid interpretation of data there needs to be consistency.
In this case for 2 main reasons: 1) To compare FR data to other countries, and 2) to interpret the progression of new cases for FR.
So there should be a count of the confirmed cases even if probable cases are counted as well.

**Comment by prosoitos** [comment]
@Aureuum: in theory, obviously, you are perfectly right. In practice however, this is happening a lot in places you would not necessarily suspect. So the data should be treated for what it is: far from perfect. Things will take years to be retrospectively corrected towards values closer to the true values.

One example where this is happening (suspected cases counted as confirmed): Quebec in Canada. The province suddenly decided weeks ago to start reporting suspected cases as "confirmed", thus creating a jump in numbers and a change in reporting protocol. You are probably not using Quebec data per se, but, since it is the most affected province in Canada, it is highly influencing the Canadian total.

It is likely that similar inconsistencies are happening all over the place (in addition to under-reporting for various reasons and many other problems).

So I am not sure that this French inconsistency really matters that much.
