### ISSUE TITLE
Virus in 21/22 April Update?

### ISSUE THREAD

**Issue by HedgePig** [CSSEGISandData/COVID-19#2327]
I've tried downloading the latest version of the zipped master and my corporate virus scanner (McAfeee Web gateway) is objecting, claiming that there is a virus. I haven't had this issue  with previous downloads of the master and was wondering if anyone else is finding a similar problem?

The message I'm getting is 
URL: https://codeload.github.com/CSSEGISandData/COVID-19/zip/master
Media Type: application/pdf
Virus Name: Generic Trojan.lj

**Comment by ralph-holland** [comment]
I grab the https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports files via git which avoids downloading the entire zip and you issue, which could be related to anything. 

If you install git you could clone the repository instead of grabbing the entire zip master every day - it would be more efficient.

**Comment by justinPalmer1** [comment]
McAfee identified the same issue for me using the zip file from today. Curiously, a virus scan doesn't identify any issues when cloning the repo so it appears the problem is with the zip only.

URL: https://codeload.github.com/CSSEGISandData/COVID-19/zip/master
Media Type: application/pdf
Virus Name: Generic Trojan.lj

**Comment by HedgePig** [comment]
Thanks for the feedback, folks - "glad" that I wasn't the only one who encountered the issue (which still seems to be there today)
Looks like I'll have to learn to use git!

**Comment by taalbrecht** [comment]
I've also encountered the same issue when using git with McAfee so the issue is not just for those using the download zip option. It is identifying a daily WHO situation report as containing a trojan (I forget which one).

**Comment by atz** [comment]
@CSSEGISandData : Please respond to this reported security issue.  Would hate to see a good project distributing malware unintentionally.  Potential operational security hazard, too (compromise of originating system, or upstream).

**Comment by CSSEGISandData** [comment]
Thanks for the feedback. We are asking our network security to check this issue.

**Comment by CSSEGISandData** [comment]
Thank you again for reporting.  Based on analysis, it appears that the earlier hits on the file were most likely false alarms.  Regardless, the offending file was removed and replaced with a screened copy.
