### ISSUE TITLE
Records for Serbia not updated since: 20.04.2020

### ISSUE THREAD

**Issue by momcilo78** [CSSEGISandData/COVID-19#2418]
Records for Serbia not updated since: 20.04.2020
For comparison, the official government daily announcements were published here regularly:
https://www.worldometers.info/coronavirus/country/serbia/

**Comment by pericnenad** [comment]
Additionally, WHO status reports are regularly updating these numbers as well, albeit with one day delay. The WHO data does not seem to be pulled into the statistics here as well.

**Comment by momcilo78** [comment]
In the meanwhile, it appears the automated data imports work again, since data for 04/30/2020 did show up. However everything between 04/21/2020 and 04/29/2020 still contains non up to data.

This is causing the variety of tools to show weird data (e.g. sudden drops and sudden jumps) and may lead to incorrect calculation of doubling rate. We simply feel that this could lead to the wrong decisions being made, since the JHU data are trusted globally. 

If it is not possible to merge the data from pull request #2419, then please use it to update your master data.

**Comment by CSSEGISandData** [comment]
Hello

Thanks for bringing this to our attention. We have had to change sources due to data going stale from our main source from 4/21 on. We are planning on updating the time series data for Serbia and Kosovo today using the new source, but need to deconflict the case counts between the two regions to ensure we are not double-counting cases. This should be fixed within the next few hours. Thank you for your patience.
