### ISSUE TITLE
United Kingdom Data

### ISSUE THREAD

**Issue by saccpp** [CSSEGISandData/COVID-19#2463]
United Kingdom Data with Lat 55.3781 & Long -3.4360000000000004, is shown as zero since 13th April? Please clarify.

**Comment by Lucas-Czarnecki** [comment]
What folder/data are you looking at? I cannot see this issue anywhere.

**Comment by saccpp** [comment]
In the global recovered csv file.

**Comment by ThEls-1847** [comment]
Timeseries global recovered shows zero since April, 13th. Link to timeseries: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

[Worldometer ](https://www.worldometers.info/coronavirus/country/uk/) reports "n/a" for UK. reporting 0 (digit zero) is missleading.
