### ISSUE TITLE
Wrong data source for number of recoveries in France

### ISSUE THREAD

**Issue by syntakker** [CSSEGISandData/COVID-19#2523]
Sorry for contradicting the last comment in #2521, the number cited on the site

https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA

is not the number of recovered patients. In the section "Données hospitalières", "retours à domicile" is the number of people that have been hospitalized and have left the hospital, i.e., this is the number of recoveries only among people who underwent treatment in a hospital.

The actual number of recoveries should be substantially higher (see #2521)

**Comment by CSSEGISandData** [comment]
@syntakker we still agree with you that the recovered data is likely higher, however that data is not publicly available. Retours à domicile is the closest proxy value we have for estimating recovered patients.

An issue with the WHO definition for recovered patients is that it requires two negative PCR tests within 24 hours. For most countries, this testing is only occurring in hospital settings and thus those with mild disease will never reach the WHO definition of recovered since they aren't being retested. For this reason, we suspect that recovered data in any country with a high burden of cases has a certain element of inaccuracy.

If you are able to find an official source that contains recovered data for France, please pass it along and we will integrate it into our data pipeline.

**Comment by syntakker** [comment]
Ok, so there might indeed be no data for recoveries according to the WHO's criteria.
In this case it is debatable if it would make sense to fallback to some obvious heuristics such as assuming that people which are neither hospitalized nor have died should have recovered after a certain time (probably somewhere between 14 to 30 days).

In case I find some better data source or more information about the proceeding in France, I'll get back to you.

In any case, thank you for your great work!
