### ISSUE TITLE
Drill down to patient name missing

### ISSUE THREAD

**Issue by ChristophGer** [CSSEGISandData/COVID-19#257]

**Comment by ladris** [comment]
Most likely because there are massive privacy issues across the board with that kind of granularity. Same reason the map would never individually marker houses and addresses and instead defaults to "local area" at the city level.

**Comment by ChristophGer** [comment]
I am aware of this problem but it needs to be fixed!!

**Comment by ladris** [comment]
I'm confused, are you demanding the private information of patients be released to a globally used public platform? That's not an "issue" that's often the law that it remain private and non-public.

**Comment by designerfuzzi** [comment]
@ChristophGer  As Development Architect at SAP you should know by nature that names will never show up in public health data collections. If you make names available somehow, i would consider to make a lawsuit against someone trying to do so. 
Sorry maybe you meant "troll down" instead of Drill down..

and i hope you got that about 3.4k developers read this also..

**Comment by ChristophGer** [comment]
As a Product Owner I would like to have this feature and that the law is changed :)

@designerfuzzi

**Comment by ladris** [comment]
Never going to happen. Ever. It would violate thousands of laws in every
country on the planet. Product owner or not. No person on earth is entitled
to the medical or private data of another patient under any circumstances
in any country unless the patient provides direct written permission to
release the information. I'm legitimately shocked that you seem to feel
it's a right of yours to have it and require it be provided, significant
ethics issues aside.

**Comment by ChristophGer** [comment]
[CLOSED]
