### ISSUE TITLE
Negative values for daily deaths

### ISSUE THREAD

**Issue by jeannechaverot** [CSSEGISandData/COVID-19#2596]
Death's time series doesn't seem to be cumulative.

For instance, I'm interested in predicting the number of deaths in a given country. Taking France's time series of the cumulative number of deaths `deaths_france`, `deaths_france.diff().plot()` yields the following:
![uncoherent-deaths-france](https://user-images.githubusercontent.com/10252332/83353908-04b97780-a356-11ea-93a6-b7ea62e2c72f.png)

I have noticed this same inaccuracy for multiple countries such as Kazakhstan, France, Switzerland

Thank you,

Jeanne

**Comment by ObliviousMonkey** [comment]
This is probably due to the fact that data is quickly relayed to the public, without being properly quality controlled. A few days later when it is finally carefully checked, numbers can change. For instance below you'll find the `date`, `cumulative number of deaths` and `daily increase/decrease` for French nursing homes (from Santé Publique France's [daily dashboard](https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde)).

It can be because a patient was reported by multiple sources and counted multiple times without being properly deduplicated etc. Now that the wave is slowly receding, data is being consolidated and that can result in absurdities like daily "negative deaths".

![image](https://user-images.githubusercontent.com/43589586/83402233-a13b5280-a406-11ea-8fde-80ea7a9ea320.png)

**Comment by CSSEGISandData** [comment]
@ObliviousMonkey thank you.
