### ISSUE TITLE
France? WTF?

### ISSUE THREAD

**Issue by jtene001** [CSSEGISandData/COVID-19#2617]
Confirmed cases global dataset. French data showed 185,952 cases Monday, 184,980 cases Tuesday and 110,906 cases today. It seems that France's time reversal has gone into hyperdrive.

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

**Comment by CSSEGISandData** [comment]
@jtene001 Thank you.  This should be fixed now.

**Comment by btklein** [comment]
Can we just make sure we are doing a sanity check on answering/closing associative issues in regards to data?  The concerns around providing accurate data due to the nature and severity of this event should warrant us as a community to provide better governance over the data.  When we have discrepancies, we should be able to point to exactly what and why data changes will be made/were made.  There may be times when we are not fully aware of how/why the data perversion occurred, but if we have solid community data principles then data lineage and provenance should be associative.  My concern mostly is about providing our GitHub community and the greater community abroad sound reason/justification for data integrity and fidelity.  Perhaps a better explanation regarding commits?

**Comment by btklein** [comment]
In the time of my writing the comment, it appears @CSSEGISandData is getting around to answering these associated issues, thank you!

Best to all, keep up the support in this fight against the virus!
