### ISSUE TITLE
Bronx, Queens, Kings County lumped into New York County, NY

### ISSUE THREAD

**Issue by mgorris** [CSSEGISandData/COVID-19#2620]
In the raw, confirmed case time series data there are 0 cases reported in Bronx, Queens, and Kings County, NY. I noticed the case numbers for New York County, NY are much too high. After a back-of-the-envelope calculation based on the numbers reported on the interactive map, I believe Bronx, Queens, Kings, and New York County may have been summed and reported under New York County, NY. 

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

Thanks, Morgan
email: mgorris at lanl.gov

**Comment by rockonomist** [comment]
The five boroughs of New York City (Manhattan, The Bronx, Brooklyn, Queens, Staten Island) are coterminous with New York, Bronx, Kings, Queens, and Richmond counties, respectively. I presume they are lumping everything into New York County because their official source is not reporting at the borough/county level within New York City.

**Comment by rockonomist** [comment]
If in fact they are now reporting the boroughs separately, would be nice to see a revision made here, as OP requested.

**Comment by John-Steidley** [comment]
@mgorris Thank you for opening this issue. I'm not affiliated with the project in any way, but it helped me understand an issue I was having.
