### ISSUE TITLE
brazil missing recovery data for June 5

### ISSUE THREAD

**Issue by kalmenk** [CSSEGISandData/COVID-19#2639]
brazil shows 0 recovered cases for june 5. it's a gap in the dataset.

**Comment by ArtemisDicoTiar** [comment]
[https://github.com/CSSEGISandData/COVID-19/issues/2632#issue-632281820](url)
Issue fixed.

**Comment by kalmenk** [comment]
thank you!

**Comment by ViniciusssMelo** [comment]
The problem isn't in the dataset, but the government denied to share the data. That's a problem even in the country itself.

**Comment by ArtemisDicoTiar** [comment]
Sorry for delivering wrong information. As @ViniciusssMelo mentioned, the problem is not on the dataset. The Brazil government changed the rule to share the data for recovered. Here's the link that shows Brazil government's rule about the data. 
[https://covid.saude.gov.br/](https://covid.saude.gov.br/)
(* When you get to the page of Brazil's coronavirus panel([https://covid.saude.gov.br/](https://covid.saude.gov.br/), they still shows the overall recovered number in their county. So I think they've changed the way of showing the recovered number. They are now only trying to show the country's recovered number.)

I think the dataset you are looking now is 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/06-05-2020.csv'.
I can find that recovered number is still 0 and for the next day(6/6) too.
However, if you only care the number of recovered data for whole country rather than the region specified, then this dataset will help you.
'COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'

**Comment by kalmenk** [comment]
brazil shows recovered data for June 7. so now the gap is June 5-6.

**Comment by CSSEGISandData** [comment]
@kalmenk @ArtemisDicoTiar @ViniciusssMelo Thank you.  The recovery data should now be in the 06-05-2020.csv under "Unknown, Brazil".  It is already in the timeseries files and 06-06-2020.csv and 06-07-2020.csv.

**Comment by kalmenk** [comment]
those dates look good, thanks! however, June 8th data now looks funky as it shows 94k recoveries for brazil - way higher than any of the previous days.
