### ISSUE TITLE
Cache County Utah missing from daily reports

### ISSUE THREAD

**Issue by a-rosenberg** [CSSEGISandData/COVID-19#2654]
Was previously in reports and stopped being updated/included on 4/15

**Comment by QuantumForge** [comment]
It seems to me there are many Utah counties that do not make sense. In COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv shouldn't the number of infections for each day be equal to or greater than the number of infections of the previous day for all cases? In other words these files report the integral number of infections recorded up to any given date? I find, for instance, Beaver County records 0 infections up to March 28, then on March 29 1 infection is shown in both the time series summary file and the daily update file. Then on March 30 the number of infections reported in both the time series and daily update drops back to 0. This is presumably a similar problem with Cache County. In the time series data, the number of infections shows infections (after the first entry with number of infections > 0) going as 2, 2, 2, 2, 3, 3, 0, 0, 0, 5... Infections should not decrease if I understand the data format correctly. Other counties in Utah such as Garfield, Grand, San Juan, Uinta show similar problems. The daily reports differ in the case of Cache county, but according to the readme this can be explained by errors in reporting. The readme says errors will be corrected in the **time series** file but not the daily report.

I am trying to plot the daily number of infections reported in all of Utah, but because of these discrepancies the data is suspect, at least for Utah. Does anyone understand what is happening here or am I misunderstanding the data format?

**Comment by QuantumForge** [comment]
a-rosenberg, since we may be trying to plot similar data I'm going to throw in a plot and some data since maybe we can cross check each other if that's helpful. I am interested in looking at infections and deaths reported daily. I use the time series data to sum all Utah counties on a daily basis for the total number of infections and deaths for the state, then do a day-by-day subtraction of the integral number to determine the daily numbers. Attached is my plot of daily infections (each histogram bin is one day), and 7 day moving averages (bands around the lines are SEM, please ignore it because it's not appropriate for such small numbers I should be using Poisson errors instead).

![utah_20200608](https://user-images.githubusercontent.com/17340612/84203981-99fbf080-aa67-11ea-9c01-3268dbe52e69.png)

In the first week of April deaths shows an odd feature. A flat feature, then a spike that dips down to 0. That's possible given I am plotting the daily numbers but when I look at what I actually pull from the time series data I see something weird. Here are the integral number of deaths I calculate for the first week of April:
2020-04-05 00:00:00 8
2020-04-06 00:00:00 13
2020-04-07 00:00:00 13
2020-04-08 00:00:00 13 
2020-04-09 00:00:00 13
2020-04-10 00:00:00 17
2020-04-11 00:00:00 18
2020-04-12 00:00:00 18
2020-04-13 00:00:00 13
2020-04-14 00:00:00 18
2020-04-15 00:00:00 20

and the differential number of daily infections (middle column) and deaths (right column):

2020-04-05      173        0
2020-04-06       77        5
2020-04-07       61        0
2020-04-08      109        0
2020-04-09        8        0
2020-04-10      247        4
2020-04-11      104        1
2020-04-12       96        0
2020-04-13       60       -5
2020-04-14       54        5
2020-04-15      131        2


notice on April 13, the integral number of deaths decreased from the previous day, this causes the daily number of deaths to take on a negative value. This is an error. Not sure if the error is on my part or coming from the data yet. But given the problems you pointed out in the time series data and that I also see, it leads me to believe that the time series data is not recording the data correctly. If you can confirm or deny any of this it would be helpful.

**Comment by CSSEGISandData** [comment]
@a-rosenberg @QuantumForge Utah switched from reporting at a county level to reporting by health districts ([see here](https://coronavirus-dashboard.utah.gov/)).
