### ISSUE TITLE
Indian timeseries data is incorrect for last two days

### ISSUE THREAD

**Issue by nitinai** [CSSEGISandData/COVID-19#2705]
All the timeseries files have incorrect data for India for 12 Jun and 13 Jun. Looks like the values from previous day is copied to the latest day. Does it happening due to data publish time mismatch with https://www.mohfw.gov.in ?

**Comment by SidKumarSingh** [comment]
There is a lag of 1 day. As you correctly guessed, it's due to the script running before MoHFW website update. So the data showing for 13 June is actually of 12 June. They made some change in the scripts 3-4 days ago and since then India data has been all over the place. Thinking of modifying my own crawler to cover for this.

**Comment by vishivish18** [comment]
@CSSEGISandData

**Comment by SidKumarSingh** [comment]
@nitinai @vishivish18 Updated my Python script to accommodate for this in case you are interested

**Comment by CSSEGISandData** [comment]
To clarify the issue in line with @SidKumarSingh 's description above: Per #2369, we take a snapshot for our daily update between approximately 03:30 and 04:00 GMT (excluding technical difficulties).  India's Ministry of Health and Family Welfare's update comes out at approximately 05:30 GMT.  This means when we snap the data at 03:30 we are capturing the data on the site at that time, which is most likely before the update by the MOHFW.  So it's not that the data is incorrect, it's that the timing differs between the archive's update and the ministry's update.  This is a very unfortunate consequence of having to "take a snapshot" at a fixed time for the archive given the dynamic nature of all of the global updates.   The data on the main dashboard is updated hourly and captures the MOHFW reporting.

**Comment by vishivish18** [comment]
@CSSEGISandData So moving forward India data will have a lag of two days? Apparently what I see it's not even a lag rather by the time your crawlers take the snapshot, MOHfW site of India has some data updated so we only see a rise of 400-500 new cases instead of actual 10+12k daily cases.
Is there a way this can be fixed?

**Comment by CSSEGISandData** [comment]
@vishivish18 @nitinai @SidKumarSingh working on a fix, will update.

**Comment by vishivish18** [comment]
Does reopening mean we can still have it fixed @CSSEGISandData ?
