### ISSUE TITLE
New York County population data error

### ISSUE THREAD

**Issue by dhmacq** [CSSEGISandData/COVID-19#2737]
The population size, 8336817, reported in the file UID_ISO_FIPS_LookUp_Table.csv for New York County (admin2="New York", Province_State="New York", UID = 84036061), is actually the population of the City of New York. The City and County are not the same geographical entity. 

See the table at https://en.wikipedia.org/wiki/Manhattan .

The correct population for that UID is 1628706, as shown in the table on the Wikipedia page.

The nomenclature is a bit unusual: New York City consists of 5 boroughs, which are also called counties, as listed on that Wikipedia page. One of those boroughs is New York County, also known as Manhattan. Its population is 1,628,706. The 8336817 in the csv file should be replaced with 1628706.  

This table, derived from JHU csv files, shows the five counties' populations. Note that the population for NY County is different from the Wikipedia page, but the other four are the same.
 ```
 state      county  fips     pop
New York    Bronx 36005 1418207
New York    Kings 36047 2559903
New York New York 36061 8336817
New York   Queens 36081 2253858
New York Richmond 36085  476143
```
The other four counties are included separately from New York County in the JHU csv file, and thus are double counted.

Note that this relates to issues #2620, #2212, and a few others.

**Comment by youyanggu** [comment]
As others have mentioned in the issues you referenced, JHU reports all cases and deaths for the five boroughs under "New York, New York". If you look at the data for Bronx, Kings, Queens, and Richmond, they are all empty.

So the population is the sum of the 5 boroughs, which is what you expect because the data includes all 5 boroughs.

**Comment by dhmacq** [comment]
Thank you for replying, I appreciate it. I now understand the reporting strategy for these five boroughs, and that is helpful.

However, having observed that population size data is present for all five boroughs, I would NOT expect one borough's population to include the populations of the other four. This is inconsistent reporting. Data users do generally expect data consistent reporting.

Having learned of one such peculiarity, I now have to wonder if there are others. Are there? Does JHU have any other instances of having combined multiple entities into one? Is there a place where I can find a list of all such instances?


As something of an aside, the case counts data for the other four boroughs are not, strictly speaking, “empty”, since zero is a valid value for case and death data. Indeed, zero is the true and correct data for many jurisdictions in the early days – and perhaps still is in some. But the absence of a proper missing data code is another topic (see issue #1146).

Again, thank you for the reply.

**Comment by troymartinhughes** [comment]
Yes, there are other issues. I've attached a couple data quality reports that I run nightly on the JHU Daily Reports files. Starting on page 12 of the shorter report, you'll find a list of other discrepant county values, followed by explanations of how some of these data can be manually mapped to valid county FIPS codes.

But to your point on "consistent reporting," JHU has continued to report NYC boroughs consistently to facilitate data integrity and consistency; it would pose challenges to longitudinal analysis if they now began to report cases by individual boroughs rather than collectively. If you are producing geospatial or other data products that require non-zero case/death values for all counties, I'd recommend that you redistribute the NYC aggregate numbers based on population, population density, case incidence, or some other metric that you deem more accurate and acceptable; I do this for NYC as well as some regions of UT and MA, as described in the attached PDFs.

[JHU_COVID-19_Daily_Reports_US_Data_Quality_Report_20200623.pdf](https://github.com/CSSEGISandData/COVID-19/files/4827513/JHU_COVID-19_Daily_Reports_US_Data_Quality_Report_20200623.pdf)
[JHU_COVID-19_Daily_Reports_US_Longitudinal_Data_Quality_Report_20200623.pdf](https://github.com/CSSEGISandData/COVID-19/files/4827514/JHU_COVID-19_Daily_Reports_US_Longitudinal_Data_Quality_Report_20200623.pdf)

**Comment by dhmacq** [comment]
Thanks for the comments.

JHU CSSE has taken on a huge project (probably understaffed) and done very well over all. I have a great deal of respect and appreciation for their work. It's also quite understandable that when this project was started it was not possible to fully anticipate what would be needed. JHU has made significant improvements over time, and this is much to their credit.

In any large data management project there are (1) choices [choices between reasonable options with pros and cons each way], and (2) errors.  I don't object to or criticize the choice to combine the case data for the NYC five boroughs.

On the other hand, I would call the absence of a missing data code a significant error, because it makes it difficult (at best) to distinguish between a real zero and missing data. It is simply poor database design.

On a more personal note, I do think it's unrealistic of them to expect that a data user would first notice that the five boroughs' time series case data have been aggregated, and then jump to the conclusion that the population data has also been aggregated. Especially since the other four boroughs' population data is not zeroed out like the time series data is. But it's easy enough to deal with, once understood.

I was calculating population densities per county, and borough aggregation turned one county's density into a gross outlier. That's what got me started on this. Also not difficult to deal with once understood.

I also took a look at your data quality reports, and thanks, very detailed. Unfortunately, I only use the time series and lookup table CSV files.  (maybe I'll think about a systematic QA review of the time series files, instead of just noticing things here and there)

**Comment by codewarrior2000** [comment]
"Note that this relates to issues #2620, #2212, and a few others."
This relates to also one other issue raised back on March 24th, "4 New York counties with no confirmed cases"  #1457
