### ISSUE TITLE
John Hopkins Shows Michigan Spike When Michigan 

### ISSUE THREAD

**Issue by rikapace** [CSSEGISandData/COVID-19#2739]
John Hopkins shows a spike for Michigan in the last 7 days in one of its daily counts. But, it is not reflective of  https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html

The reporting makes it appear that Michigan is having a significant spike suddenly, but according to state reporting the 7 day average is down.

**Comment by CSSEGISandData** [comment]
@rikapace Thank you for bringing this up, it creates a great opportunity to discuss the difference between “date of reporting” and “date of onset”.  The data that we are providing is based on date of reporting.  So for example, on June 19th the Michigan dashboard reported 67097 cases, and on June 20th the dashboard reported 67545 cases.  This indicates that between June 19th and 20th Michigan reported 448 additional cases.  However, it does not mean 488 new cases occurred in Michigan between the 19th and the 20th.  There can be time lags between sample collection, laboratory testing, and reporting to public health departments that mean that the data that is reported on a given day can actually span a prior date range of weeks relative to when people first started experiencing symptoms.  These time lags are generally unknown or unknowable at the time of reporting (at least publicly), which is why the data that we provide, or that you’ll find in the WHO Situation Reports, are based on date of report.
 
So the graph that the state of Michigan is providing for “Daily Cases by Status” is based on the date of symptom onset and can / will change as new cases are added and backdated; the graph that you see on the dashboard and reflected in our data is based on the date of reporting – a related but different measure.  The State of Michigan’s Department of Health and Human Services is doing a great job of collecting and keeping onset date data current on their site.  This data is available at the “Cases by County by Date” link on their dashboard (https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html).
