### ISSUE TITLE
Perhaps the population data file - UID_ISO_FIPS_LookUp_Table - has some incorrect information

### ISSUE THREAD

**Issue by armsp** [CSSEGISandData/COVID-19#2748]
I aggregated the population per `Country_Region` from the [population file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv) and compared it with the [Worldometer's population data](https://www.worldometers.info/world-population/population-by-country/)

```py
import pandas as pd
population_uri = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv'
population_d = pd.read_csv(population_uri)
population_d.groupby('Country_Region').aggregate({'Country_Region': 'first', 'Population': 'sum'})
```
I see some glaring differences -
| Country | JHU | Worldometer |
| --- | --- | --- |
| US | 997,376,806 | 331,002,651 |
| Russia | 292,579,178 | 145,934,462 |
| India | 2,751,276,819 | 1,380,004,385 |
| Canada | 75,711,404 | 37,742,154
| China | 2,809,352,660 | 1,439,323,776 |

Any idea why JUH's population data is often many times more than the actual population? For quite a few of the other countries the data matches. But some of the largest countries, its all over the place.

**Comment by CSSEGISandData** [comment]
@armsp I believe it's duplication of entries in locals for which there is subnational data.  For example, for the US we have entries for the country, entries for each state, and entries for each county.  Each of these has a figure for the population.  So if you aggregate by the country_region column, you will wind up tripling the score.  Canada similarly has both National and Provincial population figures, which is why you see roughly a doubling when aggregating.

**Comment by armsp** [comment]
@CSSEGISandData You are absolutely right. I should have investigated further. Got the correct results with just the following -
```py
population_d[population_d['Country_Region'] == population_d['Combined_Key']]
```
