### ISSUE TITLE
French numbers

### ISSUE THREAD

**Issue by loulouOz** [CSSEGISandData/COVID-19#2773]
Could you please explain why french numbers are very often in negative? Could this be dealt with differently?
Thanks.

**Comment by CSSEGISandData** [comment]
Hello,

Thanks for bringing this to our attention. The issue is arising due to a disconnect between the French Health Ministry and the Ministries of Health for DROM (Guadeloupe, French Guiana, Martinique, Mayotte, La Reunion). The data released by the French Health Ministry includes cases from these overseas departments - as these are lower administrative regions for France in the dashboard, we subtract these cases from our France, France entry. We source the values directly from the regional health ministries as the French Health Ministry does not disaggregate the cases for the territories from the national dashboard.

The days with negative values for France, France are due to the increase in cases in DROM exceeding the rise in cases reported by the French Health Ministry. The effect is an apparent drop in France, France due to their being a net decrease in the numbers reported for that day. We perceive this issue to be due to there being an inefficient pipeline of information from the regional health ministries to the national health ministry.
