### ISSUE TITLE
Wyoming people_tested off by a sum of 10,000 starting on 22 June 2020

### ISSUE THREAD

**Issue by davechristianson** [CSSEGISandData/COVID-19#2777]
In the US daily reports, the number of people tested drops by 10,000 on 22 June 2020. The error seems to propogate foward in time.

**Comment by NaKo91** [comment]
The dashboard's testing data source is The Covid Tracking Project.
Since more specific information became available, they replaced test specimen data with people tested data on June 20th. 
This lead to a decrease in the totals.

**Comment by davechristianson** [comment]
THanks for the quick reply.  Is this referring to the tendency for some states to include retests of recovered individuals in their test totals (where a single individual might have multiple test results included in the testing total)?

**Comment by NaKo91** [comment]
Yes, that's what caused the change in reporting. Unfortunately, many states and countries do not differentiate nor clarify their testing data. Contrary to this, Wyoming publishes separate figures since June 19th.
As of today, at least 45.310 specimens were conducted, whereby 33.369 people got tested.
