### ISSUE TITLE
The difference in US data

### ISSUE THREAD

**Issue by Epi-Mic** [CSSEGISandData/COVID-19#2784]
Please, 
why there's so much difference between numbers from JHU, Worldometers.info, CDC and COVID Tracking project?
Can someone give me a simple explanation? Particulary i'm interested in difference between JHU and Worldometers, it's about 90,000 already!
Thanks

**Comment by lilyclemson** [comment]
JHU data is diff from the JHU web site. Its website also has discrepancy where the number listed on the left panel is different from the number in the chart at the right bottom.

**Comment by CSSEGISandData** [comment]
@Epi-Mic and @lilyclemson - the data in the master branch of this repository represents a daily snapshot of our data taken at approximately 0400 GMT daily.  During the course of the day cases will accumulate and so the numbers on different websites

**Comment by NaKo91** [comment]
I was wondering about that, too. 
Regarding Worldometer's data, I could figure out what contributes most to those additional 90.000 cases.
First, they added 15.000+ cases to New York's data retrospectively to include the results of positive antibody tests. Though, I couldn't identify the source for this data.
Secondly, they collect the number of cases in prisons, veteran affairs, the Navajo Nation, and the military separately and add them to the totals, despite some state's data already include such cases (e.g. Michigan). 
Plus, they don't adjust their data properly if a state evaluates and removes cases from the dashboard.
All this considered, I suggest the JHU dashboard to be more trustworthy. Nevertheless, Worldometer's dashboard is a useful tool to get real-time information about daily new cases on a state level.

**Comment by CSSEGISandData** [comment]
@NaKo91 @Epi-Mic @lilyclemson a brief explanation of a few of the outstanding issues in this thread:
- The data we are providing in the repository is a daily snapshot from about 0400 GMT.  We are (when everything is going well) updating the dashboard hourly as new case data is recorded.  So during the course of the day the daily snapshot will lag behind the dashboard, but will sync at 0400.
- The data for "total confirmed" will equal the sum of the confirmed cases by country.  There is sometimes a temporary discrepancy due to the caching necessary for handling the traffic to the page.  If you (at 1230 EDT) sum the confirmed cases by country, it equals the total confirmed count.
