### ISSUE TITLE
New York state data

### ISSUE THREAD

**Issue by PSingzon** [CSSEGISandData/COVID-19#2794]
Just wanted to check if the daily data for 6/30 is correct - 51 new cases and 629 deaths? Does not seem to correspond with other public reporting. Thanks.

**Comment by wellsangels** [comment]
NYC Dept of Health [posted the following](https://www1.nyc.gov/site/doh/covid/covid-19-data.page):

**New Data on NYC Resident Deaths Outside of City**

On June 30, the count of New Yorkers who have died of COVID-19 increased by 692. Most of that increase is due to new information we received from the NYS Department of Health about city residents who died outside the city. The vast majority of these deaths occurred more than three weeks ago.

**Comment by DavidViral** [comment]
I am wondering if these cumulative nursing home and ACF fatalities as of June 29 were suddenly added in on June 30. And who added them? The NY gov dashboard doesn't show the same numbers as JH for total deaths. The totals in this report  (I didn't add them up) seem to be in the ballpark to account for the discrepancy in total deaths on June 30 assuming these had not been previously included.  I don't know if this report is a one-off or periodically updated - no context is provided.

https://www.health.ny.gov/statistics/diseases/covid-19/fatalities_nursing_home_acf.pdf

**Comment by ErintheEpidemiologist** [comment]
I think there is a discrepancy in the reporting of Putnam County, NY confirmed cases. They report 1499 on 6/29, but 1326 on 6/30.

**Comment by DavidViral** [comment]
> 
> 
> NYC Dept of Health [posted the following](https://www1.nyc.gov/site/doh/covid/covid-19-data.page):
> 
> **New Data on NYC Resident Deaths Outside of City**
> 
> On June 30, the count of New Yorkers who have died of COVID-19 increased by 692. Most of that increase is due to new information we received from the NYS Department of Health about city residents who died outside the city. The vast majority of these deaths occurred more than three weeks ago.

If I subtract 692 from June 30 total deaths then I get minus 63 new deaths on June30.   How many actual new deaths were on June 30?  And new cases are still only 51.
