### ISSUE TITLE
Germany data

### ISSUE THREAD

**Issue by Epi-Mic** [CSSEGISandData/COVID-19#2805]
JHU uses data for Germany from Berliner Morgenpost's dashboard (https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/) and some other aggregators use Tagesspiegel info (https://interaktiv.tagesspiegel.de/lab/karte-sars-cov-2-in-deutschland-landkreise/). Why there's some discrepancy between them? And why first one is more reliable for JHU.

**Comment by NaKo91** [comment]
So far as I can tell, any occurring discrepancy is likely to be caused by the fact that they use different data sources. 
In Germany, the chain of reporting Covid-cases looks like this:  
Hospital/Laboratory/Doctor etc.  --> County --> DOH of the state --> federal DOH (RKI)
As the Morgenpost uses data from the state's DOHs, but the Tagesspiegel gathers data directly from the counties, the Morgenpost's reporting likely lags behind a bit compared to the Tagesspiegel.

To what discrepancy do you refer specifically?

**Comment by Epi-Mic** [comment]
Difference in death cases is about 60, while everyday increase is 3-17. This coudn't be explained by lags.

**Comment by NaKo91** [comment]
Yes, this looks like a steady mismatch...
I tried to identify the cause for that but, unfortunately,  I wasn't very successful. On both the county and the state level, Covid-cases and deaths had been revised several times over the past months, so it's hard to say when or where this gap evolved. 
I would suggest the discrepancy is linked to the different sources, though.

**Comment by CSSEGISandData** [comment]
We are using Berliner Morgenpost's data for Germany and constantly comparing it with other sources, such as WHO and ECDC. One explanation for the inconsistency is the updating time. We wrap up daily cases around 12 am ET, which is potentially different than other sources.
