### ISSUE TITLE
United Kingdom confirmed cases dropped unexplicably

### ISSUE THREAD

**Issue by bigdavey71** [CSSEGISandData/COVID-19#2825]
It appears that the number of confirmed cases for the United Kingdom (specifically the England number) dropped between 2020-07-01 and 2020-07-02.  The confirmed case count on 2020-07-01 was _314,992_ but it fell to _285,268_ on 2020-07-02.  This seems to be primarily due to the elimination of confirmed cases in the **Province_State** of "Unknown" which previously had _116,327_ confirmed cases.  This was partially offset by an increase of _83,146_ in the **Province_State** of "England".

**Comment by CSSEGISandData** [comment]
Hello,

Please see data modification records and the header of the UK coronavirus dashboard (linked [here](https://coronavirus.data.gov.uk/)) to understand the drop in confirmed cases.

In regards to the Unknown entry, this was due to the same source going stale from June 23rd to July 2nd (presumably as they were making this alterations). As case data was still being reported by DHSC for the entirety of the United Kingdom (and the presence of minor discrepancies between the DHSC reporting for individual countries and the country's own reporting), the difference between the England totals for June 23rd, the current data being reporting by the respective ministries of Northern Ireland, Scotland, and Wales, and the UK total being reported by DHSC was being added to the Unknown category. 

As noted in your post, these "missing cases" have now been redistributed back into the England entry, albeit with the drop in cases as explained by the British government.
