### ISSUE TITLE
Australia - New South Wales total higher than official state figures

### ISSUE THREAD

**Issue by AbnormallyDistributedAus** [CSSEGISandData/COVID-19#2832]
The data shows a jump from 3211 to 3405 confirmed cased on 7/3/20 while Victoria stays steady. This is incorrect as NSW's official figures are currently only 3240. 
https://www.health.nsw.gov.au/Infectious/covid-19/Pages/stats-nsw.aspx

Victoria's figures for this date should be 2469 (https://www.dhhs.vic.gov.au/coronavirus-update-victoria-4-july-2020)

Thanks for all your hard work maintaining this data :)

**Comment by runrun12** [comment]
Hi. When will this be corrected? Thank you!

**Comment by CSSEGISandData** [comment]
This was discussed yesterday in #2830 but the discussion was closed.  NSW is due to the reclassification of cases in the Ruby Princess crew (see reporting on the jump [here](https://www.theaustralian.com.au/breaking-news/nsw-covid-numbers-spike-after-ruby-princess-crew-reclassified/news-story/422714295b8917d2aa030e3940d205f1)).  Victoria appears to be a case of differences in the update time and when the data was reported.
