### ISSUE TITLE
Downward revision of UK data in row 225 of time_series_covid19_confirmed_global.csv?

### ISSUE THREAD

**Issue by elcaroom** [CSSEGISandData/COVID-19#2844]
Over weeks of file downloads, the UK row 225 confirmed caseload was rising steadily. On June 24, it had a daily value of 306,862.

In the file today, June 7th's file, I see a value for June 24 of 280,340 confirmed cases for the UK row 225.  Similar downward revisions seem to be present for many days of the time series for UK row 225.

Looked in the Errata file and didn't see any note on this – any assistance is appreciated.

**Comment by CSSEGISandData** [comment]
@elcaroom Greetings.  We try to put discussion around major shifts in reporting in the data modifications section of the readme in the data section (https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md).  This is the entry on the UK shift:

"July 3rd, on July 2nd, the United Kingdom revised their case count due to double counting of cases in England that had been tested in multiple facilities. In doing so, they revised their historical time series data for England (available here). This change resulted in the need to revise our time series for the United Kingdom. As our time series data represents collective cases in England, Scotland, Northern Ireland, and Wales and the change only affected England, we gathered historical from each respective country's national dashboard (available here, here, and here) to completely rewrite the time series data for cases in the United Kingdom."

**Comment by elcaroom** [comment]
Thank you!   That is greatly appreciated.
