### ISSUE TITLE
Significant problem with United Kingdom case data

### ISSUE THREAD

**Issue by pbsis** [CSSEGISandData/COVID-19#2879]
Your case data for the United Kingdom looks very wrong. I initially noticed when I saw this chart:

https://coronavirus.jhu.edu/embed/new-cases/timeline_newcases_date_11.html

I traced the source data back to this repo.

Comparing the data behind the chart with official UK government data produces:

![image](https://user-images.githubusercontent.com/4059311/87731981-a5a7a900-c7c3-11ea-8702-c8aa659c522b.png)

Your root readme mentions that you updated your routines to handle the 02-July change so maybe something went wrong? It also mentions needing to combine sources from multiple sites, but a single API is now available with full UK data:

https://api.coronavirus-staging.data.gov.uk/v1/data?filters=areaName=United%2520Kingdom;areaType=overview&structure=%7B%22areaType%22:%22areaType%22,%22areaName%22:%22areaName%22,%22areaCode%22:%22areaCode%22,%22date%22:%22date%22,%22newCasesByPublishDate%22:%22newCasesByPublishDate%22,%22cumCasesByPublishDate%22:%22cumCasesByPublishDate%22%7D&format=csv

Thanks!

**Comment by pbsis** [comment]
Some further analysis suggests you're using "by specimen date" data up to July, but even that is peaking higher than the official figures. There was a correction of 30K cases recently, so perhaps you're using data without that correction. Either way you shouldn't be mixing "specimen date" and "report date" data in the same chart, especially with a drop to zero between the two sets.

![image](https://user-images.githubusercontent.com/4059311/87766739-8a638a80-c811-11ea-954a-bfb223e7b0df.png)

To clarify, the reason your chart is a big problem is it suggests that UK cases dropped to zero and are now rising again. That is not what is happening and your data does not reflect the official numbers.

**Comment by CSSEGISandData** [comment]
Hello

I'll address these two issues separately, based on the order you commented them.

1) The data that is being referenced within your graph has not been corrected to avoid double counting cases in pillars I and II. If you take the sum of the "newCases" column, you'll see that it is 30572 cases higher than the official total reported in the "cumCases" column. This is also clear by the drop in cumulative cases from 7/1 to 7/2 without a negative delta in the newCases column. Our data was originally sourced from this data repository, but has shifted when this announcement was made regarding double counting.

2) The second issue is three-fold. 

a) The table by specimen date for England is the only data table that has been corrected to avoid double counting cases diagnosed in both pillars I and pillars II. As mentioned above, the "report date" data available on the api double counts 30572 individuals and cannot be used.

b) I believe the table you are referencing is data for _England only_, which is the reason that the graph you present shows the JHU data frequently being higher, as our presents cases for the entirety of the United Kingdom. To construct this table, we had to pull nation-specific data for Wales, Northern Ireland, and Scotland as this historical national data is not available on the UK website.

c) The drop in cases to near zero has two factors behind it. 
i) The United Kingdom government has frequently reported slightly lower numbers for the nations of Scotland, Wales, and Northern Ireland than were being reported by the nations themselves. We had to pull data from these sources through July 1st, while using our primary source of the "Total number by nation" header on the coronavirus.gov.uk for July 2nd and on. This slightly decreased the change in the number of cases seen from July 1st and to July 2nd for Scotland, Wales, and Northern Ireland and contribute to the low number of cases seen on July 2nd.
ii) The UK government makes frequent revisions to the "Total number of lab-confirmed cases in England by specimen date" table and "Total number of COVID-19 associated UK deaths by date reported" table hosted on coronavirus.data.gov.uk. This is an issue we have had to change several times. For this specific instance, at the time of correcting our table to fix their double-counting error, they demonstrated no new cases diagnosed on July 2nd in the specimen date table. This is likely due to delays in reporting, as you can see on the coronavirus.gov.uk website that at this very moment no new cases have been diagnosed since July 14th, which is an absurdity. 
The reason we won't immediately correct the July 2nd entry is that the scale of the revisions is massive. To give you a sense, here are all of the dates that have the same cumulative total reported now that was reported on July 2nd: April 28th. The first official case in England has also been revised from occurring on February 3rd to January 30th. 

Rather than frequently making revisions to our time series table and needing to pull cases from the other three sources, we are waiting for the UK government to correct the date reported table for all of the UK to remove the cases that have been double counted.

I hope this clears up the issue for you. Please let us know if you have any other questions.

**Comment by pbsis** [comment]
My specimen date chart was not for just England. Here it is with the England line on too:

![image](https://user-images.githubusercontent.com/4059311/87834431-4a88bb80-c882-11ea-90dc-77e08f9081f9.png)

This is from official DHSC gov.uk data, so where are you sourcing specimen date data that is so much higher?

Also from what I can tell, you are using specimen date data up to end of June and the switching to report date data. You also have a drop to near-zero on 02-Jul and a peak on 14-Jul that is not in any official data. Why have you stitched together two different representations of the data?

I can understand the point about the double-counted cases but it appears that in accounting for that, you have introduced a much more serious misrepresentation into your data. People are seeing your chart and thinking that UK cases dropped to zero and have started rising again. That is absolutely not the case and is grossly misleading.

This is the UK official cases by report date chart from the gov.uk website:

![image](https://user-images.githubusercontent.com/4059311/87834657-e7e3ef80-c882-11ea-8a55-894b8e9a4a2f.png)

This is from today's Public Health England surveillance report:

![image](https://user-images.githubusercontent.com/4059311/87834861-68a2eb80-c883-11ea-9c41-4ad77b61dae2.png)

Even Worldometer doesn't look anything like your curve:

![image](https://user-images.githubusercontent.com/4059311/87834921-94be6c80-c883-11ea-952a-dc25386701a2.png)

I think you should either switch to an official UK government source for your data, or include a clear disclaimer to indicate that you have created your data for this chart and that the drop to zero is of your own invention.

**Comment by CSSEGISandData** [comment]
Hello

As mentioned in 2cii, our data **is** sourced directly from the DHSC website. The differences between our graph and yours is that the UK government makes frequent revisions to its historical case data, as mentioned above. The graphs you are posting demonstrate these historical revisions. If you are skeptical of this, here is a [wayback machine link](https://web.archive.org/web/20200701171557/https://coronavirus.data.gov.uk/) to the day we pulled the data that I personally saved in the instance that this would occur. As you can see for yourself by comparing your data versus that which was clearly available on the official website at one point in time, the numbers for practically all dates are different than what is currently available on their website. 

In regard to the peak on July 14, here are news links that show our data matches the raw numbers announced by Public Health England for July 13th and 14th. 
July 13th: [290113 cases](https://westbridgfordwire.com/13-july-coronavirus-11-uk-deaths-see-cases-reported-today-and-data-graphs/)
July 14th: [291373](https://www.bucksherald.co.uk/news/coronavirus-update-14-july-eight-new-cases-confirmed-buckinghamshire-2913525)
July 14th - July 13th = 1260 cases 

Our data is from the same official source as you are using and claiming otherwise is inflammatory.

**Comment by pbsis** [comment]
Please provide a direct reference (not links to regional media outlets) to a single, current source of official UK government data that can be plotted to look anything like your chart?

Your data appears to be highly manipulated and claiming a dataset combined from two different sources (specimen-date and report-date) with added troughs/spikes at your own discretion is from an official source is far more than inflammatory.

**Comment by CSSEGISandData** [comment]
Let me describe how the system pulls this specific data and see if that will help clear up why our data does not match the _revised_ data provided by the DHSC.

Multiple times per day, we scrape the number reported under the header "Total number of lab-confirmed UK cases" and eventually that data is used to generate the daily reports and is appending into the time series data. That is the only case data that we pull from the coronavirus.uk.gov website and our data from July 2nd on matches that number **precisely**. 

The numbers prior to July 2nd were recreated from the DHSC website accessed on July 2nd. The data used for England is **exactly** the same as what is presented in this [wayback machine link](https://web.archive.org/web/20200701171557/https://coronavirus.data.gov.uk/).

Focusing on the July 13th and 14th spike you highlight, here are wayback machine links to the cases reported on those days (see the "last updated" header) on the DHS website. These are the totals provided under the header "Total number of lab-confirmed UK cases".

July 13th: [290133 cases](https://web.archive.org/web/20200714153817/https://coronavirus.data.gov.uk/)
July 14th: [291373 cases](https://web.archive.org/web/20200715060055/https://coronavirus.data.gov.uk/)

This is precisely the 1260 case spike we report in our time series.

That data is incompatible with the numbers you are citing. This is because the UK government **very frequently** changes their historical data. Our data is **exactly** what the UK government is reporting for cases **on that day**. Since they change their reports often, our only solution would be to pull their entire time series file every day, which we believe to be neither practical nor an honest means of reporting the case numbers that were reported by the source for that day.

**Comment by pbsis** [comment]
Please can you explain why you are using "by specimen date" date before July and "by report date" data from July onwards, and why the "by specimen date" data is approx 17,500 cases higher than the current UK official figures for that period?
