### ISSUE TITLE
Canada Recovered numbers - what happened?

### ISSUE THREAD

**Issue by bftsystems** [CSSEGISandData/COVID-19#2887]
The number of 'Recovered' cases in Canada jumped by almost 24,000 in one day (Jul-17 report). Can you explain this aberration in the numbers, and are the new numbers correct? If so, is there any plan to go back and correct the erroneous stats in the daily time series reports to account for this? 

Thanks, and keep up the great work.

**Comment by CSSEGISandData** [comment]
@bftsystems Jump is due to a change in the way that Quebec is counting recovered cases (see [here](https://www.inspq.qc.ca/covid-19/donnees/methodologie) and [here](https://montreal.ctvnews.ca/quebec-covid-19-recovery-rate-skyrockets-after-new-system-implemented-1.5028344)).  There is currently no data available to recompute Canadian historical recoveries in light of the Quebec spike.

**Comment by bftsystems** [comment]
Thanks for the clarification, and links. Take care.
