### ISSUE TITLE
Decline in Deaths for France and Recoveries for Hubei

### ISSUE THREAD

**Issue by patricksawick** [CSSEGISandData/COVID-19#2921]
I noticed a decline in the number of deaths for France:

file: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

data:

Country/Region | 7/19/2020 | 7/20/2020 | 7/21/2020 | 7/22/2020
France | 30046 | **30069 | 30056** | 30063

and in recoveries for Hubei:

Province/State | Country/Region | 4/16/2020 | 4/17/2020 | 4/18/2020
-- | -- | -- | -- | --
Hubei | China | **64435 | 63487** | 63494

Is there any comment on this decline?

**Comment by CSSEGISandData** [comment]
@patricksawick Re: France - we have found that propagation of information from French dependencies can introduce variance due to reporting delays that can manifest as exactly the phenomena you are observing.  Re: Hubei - data from public health sources is being continuously revisited and revised, so that often times you will see drops in numbers from day to day.
