### ISSUE TITLE
Idaho recovery rate 7/3 and all 7/4

### ISSUE THREAD

**Issue by petersondroogh** [CSSEGISandData/COVID-19#2932]
The Idaho Recovered for 7/3/20 showed 4393 on 7/3/20 but then showed 2801 on 7/4/20.  (See below). Not sure why the huge differences 

2636 | Idaho | US | 7/3/20 4:34 | 44.2405 | -114.4788 | 6593 | 92 | 4393 | 2108 | 16 | 368.928942 | 95121 | 340 | 1.39541938 | 84000016 | USA | 5322.74987 | 5.15698468
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2694 | Idaho | US | 7/4/20 4:34 | 44.2405 | -114.4788 | 6994 | 93 | 2801 | 4100 | 16 | 391.367969 | 98709 | 350 | 1.32971118 | 84000016 | USA | 5523.526 | 5.00428939

**Comment by CSSEGISandData** [comment]
@petersondroogh Drop was due to a correction by the state of Idaho to their calculation for recoveries.  Contemporaneous reporting can be found here: https://www.ktvb.com/article/news/health/coronavirus/idaho-coronavirus-updates-6816-confirmed-cases-93-deaths-2858-recovered/277-c685af8c-ea9d-4217-b037-c307c2113a91 .
