### ISSUE TITLE
Why testing numbers for Colorado don't match?

### ISSUE THREAD

**Issue by runrun12** [CSSEGISandData/COVID-19#2971]
Hi, 

Could you please explain why the testing numbers for Colorado don't match with the official website?. The numbers don't match with any official number: PCR tests or serology tests or Non-CDPHE tests.

This is the official Colorado source:

https://covid19.colorado.gov/data/case-data

The testing numbers are very different between your source and the official source.

Thank you

**Comment by ghostwheelVa** [comment]
I am seeing the same thing.

For July 30th Colorado Dept of Health and Environment is reporting 13,542 new PCR tests (4,435 conducted by CDPHE and 8,107 conducted by commercial labs).  They are also reporting around 1000 anti-body tests.

The number in John Hopkins (and CovidProject) is 7,495.

It would be good to understand how these number match up, this is leading to a significant difference in positive test % between Colorado provided data and JHS provided data.

**Comment by runrun12** [comment]
@CSSEGISandData could you check this, please? Thanks

**Comment by ghostwheelVa** [comment]
**I think I understand the differences now. The Colorado site is reporting total number of testing encounters per day so that a person who received more than one test (say a rapid test and a regular test) counts as two individual tests.   Whereas the Covid Tracking Project the source for Johns Hopkins testing data (and the CDC) are reporting on number of people tested per day.  

So in essence both numbers are correct, they are just measuring slightly different things.

The Colorado Department of Health and Environment site defines the chart being cited as.**

"Positivity data from clinical laboratories
•	What this graph shows: The total number of tests reported to CDPHE as being performed each day - and the percent of those tests that are positive for COVID-19. "

**It further defines this in their testing FAQ as**

"This data is a cumulative total from the positivity graph, which shows the total number of people tested each day. Many people get tested multiple times, and each of those tests is counted in the positivity graph as long as the tests were taken on separate days. If an individual was tested more than once in a given day, they will only be counted once for each day they have been tested.  
The Testing Encounters totals are higher than those represented in the People Tested numbers because in the People Tested numbers, individuals only are counted once, regardless of how many times they have been tested. "

**On the Covid Tracking Project site (source of Johns Hopkins data) they define testing as**

"Total test results
API field name: totalTestResults
Where possible, we report total tests in units of people tested, rather than units of specimens tested. Currently computed by adding positive and negative values because some states do not report totals and to work around different reporting cadences for cases and tests."
