### ISSUE TITLE
Minnesota total number of tests is DECREASING?

### ISSUE THREAD

**Issue by JuanCab** [CSSEGISandData/COVID-19#2990]
Why has the total number of test administered in Minnesota DROPPED over the last few days?  This is a cumulative number, it should only ever increase.

**Comment by NaKo91** [comment]
"On July 30th, Minnesota reports again the number of people tested. Due to this change, the number of total tests by Minnesota will decrease by 200,000. Number of specimens tested will still be tracked and available in our API."

![Unbenannt](https://user-images.githubusercontent.com/66752944/89594146-5fd58200-d851-11ea-9f76-9c594ac10467.JPG)

Source: The Covid Tracking Project

**Comment by JuanCab** [comment]
I'm not sure I follow, I see that the "New Tests" went negative on July 31 which I already knew.  Is this because MN switched the number they were reporting (dropping it by 200,000) since it is now meant to be people tested instead of specimens tested?

**Comment by NaKo91** [comment]
The number of tests performed on a given day is calculated as the difference between total performed tests at that point of time and the totals from the prior day. After MN eliminated excess tests belonging to one and the same person, this resulted in a drop of newly performed tests on Juli 31th.
