### ISSUE TITLE
Question about probable death data in New Jersey

### ISSUE THREAD

**Issue by wheatmzy** [CSSEGISandData/COVID-19#3002]
First of all, GREAT WORK! This dashboard has a real impact all over the world.

I have a question regarding the probable death data in New Jersey.
In the commit a92707460d2df2e87becc5d81fb51ddb78605d81, your team seems to add 1868 death in the row of Unassigned County New Jersey on the date of 6/24 and the days before that. I assume you guys are trying to account for the probable death in that row.
I understand that on June 25th NJ start to report probable death number (https://www.nj.com/coronavirus/2020/06/nj-reports-probable-coronavirus-deaths-for-1st-time-death-toll-now-at-14872-with-170k-total-positive-tests.html)
However, they reported 1854 probable death on that day which is different from your data. In addition, the COVID tracking project reported 1843 probable deaths on both June 25th and June 24th. The three numbers do not match. And the 1868 deaths you added, make the total deaths in NJ on 6/24 larger than 6/25. 

Here are my questions:
How am I supposed to interpret the death number in the unassigned county in New Jersey? 
If those numbers are probable death, where are those numbers coming from?
NJ starts to report probable death since 6/25, where are the probable deaths coming from for the date before that?

Thank you for your great work. Looking forward to hearing back from you.

**Comment by CSSEGISandData** [comment]
Hello

The probable death data was accessed from the [New Jersey state website](https://covid19.nj.gov/) on August 2. The date is important as we anticipate revisions to the state probable death curves, which I assume to be the source of the difference you are noting in your issue. 

To access the probable deaths on the state website, on the "DATA Dashboard" and select the "Case and Mortality Summaries" tab. On the bottom of the dashboard, select "Mortality Summary" and there will be a time series graph that includes the probable deaths. We used this data to back distribute the probable deaths from June 24th and earlier into our time series file. At the time of accessing (August 2), the state of New Jersey had reported 1868 probable deaths. I can share the file with you, if you would like.

The probable deaths are located in the unassigned county as the state of New Jersey is not releasing the location of the probable deaths due to privacy concerns. It is important to note that the probable deaths have been distributed from March 17th to June 24th, at which point the state of New Jersey distributed the totals within the counties and we remove the probable deaths from the unassigned counties. The slight drop in deaths is do to an unknown inconsistency with the state reporting.

**Comment by wheatmzy** [comment]
Thank you so much for your response. I would certainly like to take a look at the file. 
I am also curious about how you get the data from the NJ-COVID 19 dashboard. Could you please share that information with me if you don't mind. Thanks again.

**Comment by CSSEGISandData** [comment]
@wheatmzy Hello!

There weren't that many dates for which we needed probable deaths and it can be difficult to directly access Tableau so those numbers were pulled manually.

If you would be willing to provide your email, I'd be happy to send along our csv.

**Comment by wheatmzy** [comment]
Here is my email: zmi@ccl.rutgers.edu
