### ISSUE TITLE
Drop in cumulative cases in 48 of 95 Nebraska counties 18Aug20

### ISSUE THREAD

**Issue by bms44974** [CSSEGISandData/COVID-19#3045]
The Nebraska Department of Health reported [262 new cases on 18Aug20](https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd), but the aggregate time series data across counties in Nebraska reflected a decrease in cumulative cases by 710 with 48 of Nebraska's 95 counties reported a drop in cumulative cases from 17Aug20 to 18Aug20.

**Comment by CSSEGISandData** [comment]
@bms44974 - there was a temporary drop in the data at the state source very late yesterday night that got picked up in our daily update.  We are currently working to resolve.

**Comment by CSSEGISandData** [comment]
@bms44974 Thank you for your patience. This issue has been much harder to resolve than we anticipated. 

It appears that right around the time we pulled data from the State source, portions of their data had issues that resulted in these drops in 48 of the counties. As far as we can tell, they reverted their data back to what had been presented on the [state dashboard](https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd) at 8:05 PM CDT. While this change removed all of the negative deltas, it then failed to report increases that had been seen in several counties (Nuckolls and Webster, for two examples). In order to prioritize removing the negative deltas, we have overwritten the time series and daily reports with the data presented on the State dashboard for August 18.

If you would like to look at the raw data, [here is a wayback machine link](https://web.archive.org/web/20200818190231/https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd) that captures the new data we are using to populate the daily products.
