### ISSUE TITLE
Daily Infections Spain - Wrong?

### ISSUE THREAD

**Issue by Holzschuher** [CSSEGISandData/COVID-19#3047]
I am perplexed by the data for Spanish daily infections shown on the Dashboard during the past few days/weeks. Taking the 17th August the reading is 16.3k. Looking at JHU's source listed for Spain, RTVE the reading is 2.1k the same as on El Pais' site https://elpais.com/sociedad/2020/07/27/actualidad/1595838623_808240.html both claiming the Spanish Health Ministry as source. The three day average of daily infections is shown by the ECDC at 5.4k undercutting the 8.9k shown here by a wide margin.
Has anyone here got an explanation for me please?

**Comment by Holzschuher** [comment]
Just found this publication by the Spanish Health Ministry
[https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_188_COVID-19.pdf](url)
Still quite a margin. The Spanish 3.7k v the 5.1k shown here for the 18th August

**Comment by CSSEGISandData** [comment]
Hello

Our data exactly matches the daily reports published by the Spanish Health Ministry for those days.
[August 18](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_187_COVID-19.pdf)
[August 17](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_186_COVID-19.pdf)
[August 16](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_185_COVID-19.pdf).
The differences you are seeing are assumedly due to historical revisions to the date to cases that results in changes for the day to which the case is assigned. We are seeing this behavior from many health departments/ministries.
