### ISSUE TITLE
US deaths and recoveries seem off 

### ISSUE THREAD

**Issue by therealcyberlord** [CSSEGISandData/COVID-19#3063]
US Data for 8/22 (JHU)
Confirmed: 5,667,112
Deaths: 176,353 
Recoveries: 1,985,484

According to Worldometer, the number of COVID deaths in the US is at 180,174, which is little bit higher than JHU's figures. The number of COVID recoveries is much higher at 3,148,080. It seems like the data is a bit off. 

Thanks again for the amazing dataset.

**Comment by therealcyberlord** [comment]
ps: they are using the same date

**Comment by CSSEGISandData** [comment]
Hello

Thanks for your comment. We have looked into the issue and we believe this is principally due to Worldometer including deaths within Veteran Affairs (2576 deaths) and the Navajo Nation (489 deaths) as separate entries in their US total. We believe these deaths are already included in the deaths reported by the counties that contain these locations, so Worldometer is likely double counting these deaths.
