### ISSUE TITLE
Missing FIPS Code for counties in Utah

### ISSUE THREAD

**Issue by data-ninja-1812** [CSSEGISandData/COVID-19#3066]
Half of the counties in Utah are missing FIPS Codes in the `csse_covid_19_daily_reports` files.

```
,Bear River,Utah,US,2020-08-24 04:27:56,41.52106798,-113.0832816,2482,9,0,2473,"Bear River, Utah, US",1328.5657698936936,0.36261079774375504
,Central Utah,Utah,US,2020-08-24 04:27:56,39.37231946,-111.5758676,484,2,0,482,"Central Utah, Utah, US",590.5752007223565,0.4132231404958678
49011,Davis,Utah,US,2020-08-24 04:27:56,40.99001837,-112.1139997,3613,21,0,3592,"Davis, Utah, US",1016.369369952262,0.5812344312205923
49035,Salt Lake,Utah,US,2020-08-24 04:27:56,40.66616532,-111.9216011,22760,224,0,22536,"Salt Lake, Utah, US",1961.3300851317222,0.984182776801406
49037,San Juan,Utah,US,2020-08-24 04:27:56,37.62762978,-109.80337140000002,661,27,0,634,"San Juan, Utah, US",4318.0036582179255,4.084720121028744
,Southeast Utah,Utah,US,2020-08-24 04:27:56,38.99617072,-110.7013958,128,1,0,127,"Southeast Utah, Utah, US",318.17842849685553,0.78125
,Southwest Utah,Utah,US,2020-08-24 04:27:56,37.85447192,-111.4418764,3454,26,0,3428,"Southwest Utah, Utah, US",1370.4065195483292,0.7527504342790967
49043,Summit,Utah,US,2020-08-24 04:27:56,40.86688146,-110.9535882,810,1,0,809,"Summit, Utah, US",1921.9361727369794,0.12345679012345678
49045,Tooele,Utah,US,2020-08-24 04:27:56,40.44862644,-113.1295715,641,0,0,641,"Tooele, Utah, US",887.0867296807318,0.0
,TriCounty,Utah,US,2020-08-24 04:27:56,40.12491499,-109.5174415,197,0,0,197,"TriCounty, Utah, US",347.9213026738724,0.0
90049,Unassigned,Utah,US,2020-08-24 04:27:56,,,0,0,0,0,"Unassigned, Utah, US",,
49049,Utah,Utah,US,2020-08-24 04:27:56,40.1166722,-111.6657662,10120,42,0,10078,"Utah, Utah, US",1590.6072441786444,0.4150197628458498
49051,Wasatch,Utah,US,2020-08-24 04:27:56,40.33110236,-111.1691419,615,4,0,611,"Wasatch, Utah, US",1803.9951893461614,0.6504065040650406
,Weber-Morgan,Utah,US,2020-08-24 04:27:56,41.27116049,-111.9145117,3150,28,0,3122,"Weber-Morgan, Utah, US",1156.6551735533549,0.8888888888888888
```

**Comment by CSSEGISandData** [comment]
Hello

This is intentional and due to a quirk in the reporting style of the State of Utah. The [state dashboard](https://coronavirus.utah.gov/case-counts/) reports cases at the health department level. For some counties (e.g. Davis, Salt Lake, etc) the health department manages a single county. For others (Weber-Morgan, TriCounty, etc), a health department is responsible for multiple jurisdictions and the cases cannot be distributed to their respective counties. In those instances, we do not provide a FIPS because one does not exist for locations that span multiple counties.

**Comment by data-ninja-1812** [comment]
This was helpful, thank you

**Comment by rokhopr** [comment]
Utah reports by "Local Health Departments" - this page and map describes how they are organized https://ualhd.org/

**Comment by briangalindoherbert** [comment]
just fyi on how I solved the 'Utah multi-county region' issue.  I created a csv file with the structure of each of these 6 regions (a cross-references file with UID and name of each region, then the names, FIPS, and population for each county that is part of the region).  I attached it below.  
I've been writing python scripts for months to pull and consolidate covid data from the jhu, covid tracking project, and NYtimes repos, and now as part of my wrangling I read in the structure from this region file and use it to delete any individual county records that belong to a region, and I sum the county populations then use that for the region population so I get accurate ratios and calculations against the region-level data reported by the State of Utah.  Finally, by keeping track of the individual county fips that make up each region I can color-code or tag these counties as part of their respective region on maps.

I've noticed quite a few maps of covid data with blank areas across Utah, I even saw one on cable tv news.  I think this occurs because quite a few datasets still have records for individual UT counties but the covid data for those counties is zeroed since the State only reports cases, deaths, testing, and hospitalization at the region level.

I hope this helps, or perhaps I just spent a couple hours on an unnecessary utility and there's already a better solution!  But hopefully someone else finds this useful!

[UT_multi-county_regions.txt](https://github.com/CSSEGISandData/COVID-19/files/5522521/UT_multi-county_regions.txt)
