### ISSUE TITLE
New South Wales cases jump on July 3 does not match government data

### ISSUE THREAD

**Issue by jeanettelt** [CSSEGISandData/COVID-19#3093]
JHU confirmed cases time series for New South Wales, Australia does not match the case data from NSW government website:
https://data.nsw.gov.au/nsw-covid-19-data/cases

Here are the cumulative confirmed cases for New South Wales, comparing data from JHU vs. NSW government website. You'll notice a jump in cases on 7/3 in JHU data not seen in the NSW data. According to JHU data, NSW saw an increase of 194 cases on 7/3 whereas the NSW government website shows an increase of only 8 cases.

![image](https://user-images.githubusercontent.com/60018379/92271946-86f99080-ee9d-11ea-9ec2-e59d6372d0c6.png)

**Comment by CSSEGISandData** [comment]
Hello

Our reporting is consistent with the data of the national government of Australia. Per the statement on [their website](https://www.health.gov.au/news/health-alerts/novel-coronavirus-2019-ncov-health-alert/coronavirus-covid-19-current-situation-and-case-numbers#total-cases-and-deaths-by-state-and-territory), "On July 3, 189 historic cases reported in crew members on board a ship were classified as Australian cases and included in the NSW totals." It's also the reason that there has been a constant difference between our reporting and the regional government since that date.

**Comment by jeanettelt** [comment]
Thank you for the quick response and clarification!
