### ISSUE TITLE
Discrepancy in data reported on 14th September for India

### ISSUE THREAD

**Issue by Saif178** [CSSEGISandData/COVID-19#3119]
The number of confirmed cases for India has been given same as that of 13th September. Please update it.

The confirmed cases are - 4930281
The recovered cases are - 3859399
The deaths are - 80776

**Comment by CSSEGISandData** [comment]
@Saif178 hello - we're working on this. Essentially, the issue is that India has _slightly_ changed the time of day that they publish their official reports and it now takes place after the generation of our daily products. The day of this source reporting change resulted in there being no published update from the Ministry of Health during the 24 hour window between two consecutive daily products. We're working on a backup approach, but at the moment if we were to make manual updates we would run into this issue every day.
