### ISSUE TITLE
Most of Utah missing covid data

### ISSUE THREAD

**Issue by salfej** [CSSEGISandData/COVID-19#3123]
For some reason, much of Utah is now missing it's data. 
![image](https://user-images.githubusercontent.com/10404888/93359583-610ead00-f808-11ea-8e31-76f85abcc00b.png)
Some data is available, but drops off, like Washington county for example. 
![image](https://user-images.githubusercontent.com/10404888/93359709-87344d00-f808-11ea-8a64-1e50dde4d516.png)

**Comment by CSSEGISandData** [comment]
Hello

This is a consequence of the reporting by the state of Utah which occurs at the health district level rather than the county level. Here is a list of their [health districts](https://ibis.health.utah.gov/ibisph-view/about/LocalHealth.html). The numbers shown in your graph were due to reporting being at the county level before the centralized reporting was in place.
