### ISSUE TITLE
Are the cases included on the date of specimen taken, the date of positive laboratory test, or date of report? Similar question for deaths.

### ISSUE THREAD

**Issue by Hurgen-Mutz** [CSSEGISandData/COVID-19#3128]
Sorry, I have searched for this information for a long time but could not find it.

If the sample (e.g. nasal swab) is taken on Monday, the laboratory test is positive on Tuesday, and the case is reported by the public health agencies on Wednesday: For which day it the case listed in the data? Are all cases added to the date when they were reported, or will they (retroactively) be added to the date when e.g. the specimen was taken. Is this handled consistently across countries?

Similar question for deaths:  Is the death (retropectively)  added for the date when the person died, or the date when this was reported by the public health agencies.?

**Comment by NaKo91** [comment]
As far as I know, they're adding both cases and deaths to the date of reporting without making changes retroactively.
With regard to the US data, they attempt to redistribute the numbers when a bulk of older "new" cases due to delays in the reporting system appears on a single day. This depends on the availability of cleared data at the local level, of course.

**Comment by CSSEGISandData** [comment]
Hello

This is a far better question that I think you may realize! We have had many, many internal discussions regarding this issue because the reporting systems are not consistent across locations. Having the date of test would be preferable as it would be more accurate for the true time-dependence of the spread of SARS-CoV-2 in that region, but unfortunately it is not consistently available. As such, we default to the date of reporting as that is the default level available for all areas, even it may be less informative, but does allow locations to be comparable. 

In short, we use the date that cases and deaths are reported by public health agencies as our top priority. However, as noted by @NaKo91, when there is a release of a large number of historically identified cases or deaths that are announced to not be associated with their date of reporting we will distribute those back in time according to official reports. When those reports are not publicly available, we reach out to agencies directly to obtain historical records to correct our own time series.

This also opens up the issue of retrospective alterations to data that some locations (such as the United Kingdom) frequently do. Our data will always _exactly_ match the number of cases reported in that location for the given date. If these numbers no longer match the official source after a period of time, it is almost certainly due to the official source altering their data.
