### ISSUE TITLE
WI case data shows 8k increase 9/19

### ISSUE THREAD

**Issue by wellsangels** [CSSEGISandData/COVID-19#3140]
There's an unusual spike in the case data for Wisconsin of 8,278 new cases added. The average new cases added for the prior week is around 1,500. Wondering if there are any issues there.

**Comment by NaKo91** [comment]
I suggest they just started to include probable coronavirus cases. Considering there have been 1.665 new cases yesterday, that tallies.

![Unbenannt](https://user-images.githubusercontent.com/66752944/93792295-a3cfeb00-fc35-11ea-876f-3012602c66fd.JPG)

**Comment by CSSEGISandData** [comment]
Hello

@NaKo91 was correct. Our scrapper caught the probable cases today as they are now presented in a machine readable format. We've removed them from the time series files and daily reports due to the somewhat inappropriate spike of cases that the new cases resulted in. We would like to include these probable cases moving forward, so we have an email out to a POC at the Wisconsin health department to receive the historical distribution of probable cases at the county level.
