### ISSUE TITLE
Texas Unreported Cases 9/23

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3153]
The Texas 9/23 state series data looks suspiciously low for new cases, about 5000 below expectation.  Nine counties are reporting negative numbers for new cases, totaling 2873 fewer total cases than the day before.

**Comment by CSSEGISandData** [comment]
Hello

Thanks for your comment. We think it is odd as well, but these were the totals reported by the [Texas state dashboard](https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83) for 9/23. We have not been able to locate information as to why there was a drop in cases in these regions. I will leave this issue open until there is some clarity from the state.

I have a sinking feeling that it is a data entry error and may be corrected in the next update this evening.

**Comment by CSSEGISandData** [comment]
@DavidViral the negative cases appears to be due to a reporting error in Bexar County. 56639 cases were originally reported on 9/22 (which is what was present in our reports), but the time series file on the source has been changed to 56339. We have updated the time series files to reflect this change.
