### ISSUE TITLE
Ireland Duplicated

### ISSUE THREAD

**Issue by TTFH** [CSSEGISandData/COVID-19#316]
**Ireland** Confirmed: 19 Active: 19
**Republic of Ireland** Confirmed: 21 Active: 21
Someone rename Ireland to 'Republic of Ireland' and now the data is shown duplicated.

**Comment by julien-arino** [comment]
In the confirmed time series data, the problem is even more striking. As of the latest update:
,Ireland,53.1424,-7.6921,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,2,6,6,18,18,19
and
,Republic of Ireland,53.1424,-7.6921,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21
Is one Northern Ireland and the other the Republic, despite the centroids saying it's the same place?

**Comment by ChrisPariso** [comment]
Is this truly a duplication, or are two portions of Ireland being tracked separately? Data for 3/8 shows "Ireland" increasing to 19 confirmed cases, while "Republic of Ireland" has 21 confirmed cases for the same day.

**Comment by CSSEGISandData** [comment]
We have updated the dashboard to reflect the correct case counts for Ireland and removed Republic of Ireland.
