### ISSUE TITLE
Again negative numbers

### ISSUE THREAD

**Issue by eilmrein** [CSSEGISandData/COVID-19#3171]
File 09-27-2020.csv, Line 427.
How come this happens only now? What has changed?

**Comment by CSSEGISandData** [comment]
Hello

Line 427 is Unknown, Netherlands. Unknown categories decrease due to commensurate increases in known locations as those cases/deaths/recoveries are distributed geographically correctly. Seeing decreases in these entries is generally a good thing.

We've had negative deltas for as long as we've been tracking this data. We're tracking over 3000 locations in the US alone, so sources are bound to make mistakes and publish corrections that result in negative deltas. I recommend you visit the README for the csse_covid_19_data folder that has a running list of our corrections to the data or source releases of new/removal of probable cases.

**Comment by eilmrein** [comment]
These are total numbers, the CANNOT go negative, whatever corrections are being applied.
I have been loading these numbers since February and never ran into this problem until about three days ago.
