### ISSUE TITLE
Pennsylvania cases not updated on 10/3/20

### ISSUE THREAD

**Issue by mahorst** [CSSEGISandData/COVID-19#3193]
Pennsylvania cumulative cases for 10/3/20 in the time_series_covid19_confirmed_US are the same value as 10/2/20.

**Comment by CSSEGISandData** [comment]
It seems that Pennsylvania has not updated their data since 10/02/2020: https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx

Thank you.
<img width="1276" alt="Screen Shot 2020-10-04 at 1 50 04 PM" src="https://user-images.githubusercontent.com/60674295/95023023-9f99c980-0648-11eb-9572-01f9c1192d05.png">
