### ISSUE TITLE
Please display cruise ship passengers under their citizenship geographies ASAP

### ISSUE THREAD

**Issue by ChasBoyd** [CSSEGISandData/COVID-19#323]
Creation of a separate geography for ships can result in delayed support from responsible agencies.

**Comment by ciscorucinski** [comment]
If the passengers remain on the cruise ship, then why would inflating "ground" locations help? These are probably some of the most highly controlled movements in the world and placing them in their country of citizenship would create other issues.

For one, in the US, the locality of all cases are highly localized down to the county level. Where would you put them? A generic US location?? 

Also, what about a citizen that is infected that comes from a country with no current cases?

**Comment by JiPiBi** [comment]
In my opinion , the target of this dataset is not to give nationalities to the sick or dead people, but to show how Covid is geographically and numerically evoluting.

**Comment by ladris** [comment]
Agreed. Moving the ship quarantined individuals statistics back to their location of origin instead of keeping them as located currently on ship would cause resources/kits and personnel to be distributed to their home location based on "ghost" cases whereas the ships themselves, until they disembark, are what need the resource allocation. This would cause the exact issue being petitioned to prevent. Currently, the ships in question are being handled by their nearest host country, as opposed to multiple countries sending redundant aid or support to a single ship.

**Comment by CSSEGISandData** [comment]
Cruise ship passengers have been allocated as determined by our various sources.
