### ISSUE TITLE
NY state momentarily counted as a NYC borough

### ISSUE THREAD

**Issue by jonasalmeida** [CSSEGISandData/COVID-19#3230]
Please note that NY state counts were miss-assigned to NYC May 16-20:

![](https://files.gitter.im/5eaa16cdd73408ce4fe226bf/GVlj/image.png)

![](https://files.gitter.im/5eaa16cdd73408ce4fe226bf/DqAI/newplot.png)

**Comment by CSSEGISandData** [comment]
Hi Dr. Almeida,

The spike in deaths on June 18 for New York City is due to this being the first day that probable deaths were available at the borough level. As such, all of the boroughs actually show this drastic increase - New York City, New York only represents the borough of Manhattan. Issue #3084 has a description of our process for recreating the borough level data.

Best,

CSSE
