### ISSUE TITLE
Wrong number of recovered cases for Greece and USA

### ISSUE THREAD

**Issue by eguidotti** [CSSEGISandData/COVID-19#3266]
Hello,
The recovered cases for Grecce seem wrong. They are not stuck at 1347, currently they are ~10.000 according to worldometers.info  
Also for US, recovered cases seem significantly lower than the number the worldometers.info ~2.3 millions

Please see also the related issues:
- https://github.com/covid19datahub/COVID19/issues/122
- https://github.com/covid19datahub/COVID19/issues/123

Do you know the reason behind the differences? Are you planning to fix this?
Many thanks!

**Comment by Inglezos** [comment]
Yes, I confirm that these data are indeed wrong, especially for Greece and USA at least as far as I have observed during my analyses. This issue has to be addressed and resolved immediately.

**Comment by CSSEGISandData** [comment]
Thanks for the note. We are working on fixing this issue now.

**Comment by CSSEGISandData** [comment]
Hello

Our recovery data comes directly from COVID Tracking Project and we cannot comment on the differences between their methodology at that of WorldoMeter. Of note, Worldometer double counts cases in several locations in the US (federal prisons, Navajo nation, etc.) so we tend to stay away from them for US data.

In regards to Greece, it appears that recovery data is now solely available from the government press conferences: https://eody.gov.gr/category/deltia-typoy/. Their machine-readable data does not include recoveries, which is why we have been carrying forward a static value. We have manually updated the recovered time series using these press releases as far back as this total is detailed. We will use these press releases moving forward.
