### ISSUE TITLE
Timeseries_Deaths_Global mit decimal numbers

### ISSUE THREAD

**Issue by mbender-ith** [CSSEGISandData/COVID-19#3279]
FIle Timeseries_Deaths_global shows decimal numbers (12345.0) in column for Oct 28, 2020. Before, numbers where always formated without decimal point.

**Comment by Bost** [comment]
This change breaks among others the https://covid-tracker-us.herokuapp.com/all

**Comment by sapienzafra** [comment]
I changed my script to use the integer part of those numbers As result I get -23.494 deaths than yesterday

**Comment by Bost** [comment]
@sapienzafra The number of deaths in Colombia is definitely wrong. For the other countries this number seems to be correct. (Please correct me if I'm wrong)

**Comment by sapienzafra** [comment]
@Bost yes other countries look correct. I manually added in my local csv file Colombia's last value, taken from the JHU dashboard (30573) and now everything works.

**Comment by CSSEGISandData** [comment]
Hello all,

Really not sure why this happened - we will be looking into it today. I've pushed an update that removes the decimal characters and includes the correct death total for Colombia (30753).

**Comment by Bost** [comment]
> Really not sure why this happened - we will be looking into it today. I've pushed an update that removes the decimal characters

I think I know what's happening. Somebody at the key position or positions still speaks and things in terms of "removing decimal characters" instead of "using appropriate data type" to represent real world information. In this case using **integer numerical data type** to convey the information about the number of people who die, get sick, recover etc.

Instead of "Bang - Excel - Whatever"

This little "removing decimal characters" remark of yours induces one question: How much the data management improved since its worst period from the times at around #413 ? The answer is: not enough.

**Comment by mbender-ith** [comment]
Issue has reappeared today
