### ISSUE TITLE
No updated data?

### ISSUE THREAD

**Issue by mirko1075** [CSSEGISandData/COVID-19#3310]
Hi, Is there any problem with the updated daily stats? I only gets the accumulated data for country but not the daily stats.
![Schermata 2020-11-04 alle 14 28 36](https://user-images.githubusercontent.com/45468712/98117443-10334080-1eaa-11eb-8fd0-7ba5034680ef.png)

**Comment by CSSEGISandData** [comment]
Hello

Where are you pulling this data from? There are updates for cases and deaths in both the daily reports and time series for these locations. It may be due to a data type error (float instead of int) that was in the generation of the time series files for last night - those have been updated. I recommend rerunning your code in the first instance to see if it was due to the data type error and then investigate further issues.
