### ISSUE TITLE
Wyoming Deaths numbers in Time Series

### ISSUE THREAD

**Issue by ripstaur** [CSSEGISandData/COVID-19#3376]
Look at the last three rows in the Deaths time series...for Weston County, Washakie County, and Unassigned. Since these are cumulative numbers, they should all continue at the highest number recorded. In these three lines, they do not.

**Comment by CSSEGISandData** [comment]
Hello

Our data matches that which is displayed on the Wyoming covid dashboard ([linked here](https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-state-and-county-dashboards/)). Weston decrease is presumably due to the death no longer being attributed to COVID-19 and the unassigned category generally fluctuates as patient locations are determined and recorded. The Washakie County entry does not have a negative delta.
