### ISSUE TITLE
Many counties in Utah incorrectly show no cases recently

### ISSUE THREAD

**Issue by icanhazcodeplz** [CSSEGISandData/COVID-19#3405]
In [https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv) 
there are many counties in Utah that show zero new cases since April. The NYTimes shows that there are many new cases in all counties in Utah: [NYTimes Utah Map](https://www.nytimes.com/interactive/2020/us/utah-coronavirus-cases.html)

**Comment by CSSEGISandData** [comment]
Hello

We follow the conventions of the [Utah Department of Health dashboard](https://coronavirus-dashboard.utah.gov/#overview). For some counties, the cases are reported for health jurisdiction rather than county. For example, Box Elder county does not have an entry on the Utah dashboard. Our time series files and the map proper have the health jurisdictions as entries.
