### ISSUE TITLE
wrong data

### ISSUE THREAD

**Issue by birdalugureren** [CSSEGISandData/COVID-19#3471]
The number of new cases increased from 30 thousand to 824 thousand in Turkey (10 december - 11 december).
![Screenshot from 2020-12-16 15-17-56](https://user-images.githubusercontent.com/26383184/102347790-f8bf9b00-3fb1-11eb-9ce0-665d481d9d9b.png)

**Comment by CSSEGISandData** [comment]
@birdalugureren Thank you for reaching out.  The Republic of Turkey Ministry of Health made the announcement on September 30th that the cases reported to date included only symptomatic confirmed cases [[1](https://www.duvarenglish.com/coronavirus/2020/10/01/turkish-health-ministers-acknowledgement-of-publishing-only-symptomatic-cases-prompts-outrage)].  The Ministry of Health recently revised their reporting to include asymptomatic cases as well [[2](https://bianet.org/english/health/235027-turkey-starts-including-asymptomatic-covid-19-cases-in-its-daily-count-reports-28-351-cases)].  As part of that revision, historical cases were added en masse on December 10th [[3](https://bianet.org/english/health/235837-turkey-updates-coronavirus-case-count-as-1-74-million)].  Unfortunately, at this time information is not available which would allow for this revision to be distributed historically, which is why there is the significant increase in cases on the 10th.  We provide notes on significant data related events, including this spike, in the [README.md](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md) file in the data directory.
