### ISSUE TITLE
Issue with Mexico Data

### ISSUE THREAD

**Issue by CarlosBerBo** [CSSEGISandData/COVID-19#3538]
Your data is wrong on October 5th and November 28th

**Comment by CSSEGISandData** [comment]
Thank you for your posting. We are looking into the issue.

**Comment by CSSEGISandData** [comment]
Hello

The spike on October 5 is genuine and due to an alteration in the case definition by the government of Mexico, as documented in our [README](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data).

The spike on November 28 was due to an error in our data which has been corrected and documented in our [errata](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/Errata.csv) file.
