### ISSUE TITLE
Case & death counts for France are very irregular

### ISSUE THREAD

**Issue by edomt** [CSSEGISandData/COVID-19#3675]
Dear CSSE team,

As always, thank you for your work here!

I'm aware that you previously had issues with the reporting of oversea territories, and with probable vs. confirmed cases, that you laid out in https://github.com/CSSEGISandData/COVID-19/issues/2459 — but as this was all the way back in May, and as quite a few people in France still can't wrap their head around the data they see on our OWID charts, I'm opening this issue to try and find out more information on how the numbers for France are collected.

Although France has, like almost all other countries, recurring weekly patterns with lower reporting on some days, the JHU case counts regularly includes daily figures close to 0 (but still with a few cases):

![coronavirus-data-explorer(22)s](https://user-images.githubusercontent.com/7103774/107850032-b96dc900-6dff-11eb-8d5c-2dd4a7788e2c.png)

The same goes for deaths:

![coronavirus-data-explorer(23)s](https://user-images.githubusercontent.com/7103774/107850036-c7bbe500-6dff-11eb-80fc-3332f96efbab.png)

This leads to time series that, even with a 7-day smoothing, [show some random bumps](https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&time=2020-10-01..latest&country=~FRA&region=World&casesMetric=true&interval=smoothed&smoothing=7&pickerMetric=total_cases&pickerSort=desc).

**My three general questions would be:**

1. Is the method presented in #2459 still the one currently applied?
2. Are these very low values something that can be corrected?
3. Could someone from your team maybe give more information on exactly which file(s) or page(s) your data collection process is based on, so we can point people to that source and they can check for themselves?

Many thanks,
Ed

**Comment by CSSEGISandData** [comment]
Hello Edouard,

Thank you very much for the work of OWiD. Yes, we are aware that France is still quite noisy. I hope you understand the delay in responding to this issue was to address one of your raised concerns. I can answer your three questions in order:

1. Is the method presented in #2459 still the one currently applied?

- The algorithm for determining the cases in mainland France still applies. We have shifted our data source for the overseas territories to the World Health Organization due to noise with our previous sources.

2. Are these very low values something that can be corrected?

- Yes. Looking at the source (linked below), they appear to have occasional issues with uploading their .csv and .json files that result in no update over a 24 hour period (or sometimes longer). However, the file does contain historical data which we used to push corrections for some days with no growth to our time series files and daily reports. We will keep an eye on this and look to push further manual corrections in the future.

3. Could someone from your team maybe give more information on exactly which file(s) or page(s) your data collection process is based on, so we can point people to that source and they can check for themselves?

- Source for mainland France: https://www.data.gouv.fr/en/datasets/donnees-relatives-a-lepidemie-de-covid-19-en-france-vue-densemble/
- Source for overseas territories: https://covid19.who.int/WHO-COVID-19-global-table-data.csv
