### ISSUE TITLE
Infected amount data type (Double/Int)

### ISSUE THREAD

**Issue by ggwpez** [CSSEGISandData/COVID-19#37]
The `.csv` files for Confirmed, Dead and Recovered state the numbers as double.  
Files in `daily_case_updates/` have integer values.  
What is the reason behind not having integers everywhere?

**Comment by Phoenixxl** [comment]
In csv files numbers are actually ascii.
The program you import the csv into decides on the datatype.

I would suggest uing the uint64_t in whatever language you use. There being a known max of 7+ billion.

**Comment by Fromalaska49** [comment]
All values being input to the CSV should be integers when they are input. I agree that uint64_t would be the appropriate type to use for data processing purposes since the maximum values could, at least theoretically, exceed the bounds of 32 bit integers when looking at global totals, however, for country specific values, any 32 bit integer type would be sufficient. As was pointed out, the integers are cast to text anyway.

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We have adjusted the values to be integers. Thank you for the input.
