### ISSUE TITLE
Issue with French data from 2021-02-19

### ISSUE THREAD

**Issue by TomFevrier** [CSSEGISandData/COVID-19#3704]
Hello there,

New data for France dated 2021-02-19 makes little sense, as it reads only 11 new cases and a single new death in the last 24 hours (compared to 22,518 and 271 on the day before).

Is there an explanation about these low figures?

Thank you very much.

**Comment by CSSEGISandData** [comment]
Hello,

Our source from data.gouv.fr (French government) ([linked here](https://www.data.gouv.fr/en/datasets/donnees-relatives-a-lepidemie-de-covid-19-en-france-vue-densemble/#_)) has failed to update their files since February 18. When this has happened before, their next update has included data for the dates that were missing. We will push updates to our time series and daily reports when the data becomes available.

**Comment by TaoSunVoyage** [comment]
Hello @CSSEGISandData,

At the top of the page you sent states that the data is now accessible from other page. 
> Point d'attention : les données sont désormais disponibles sur [ce jeu de données](https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/).

**Comment by CSSEGISandData** [comment]
Hello,

This was patched in PR #3714. We have emailed the French Ministry of Health to obtain clarification for the update schedule of the files available on their website.
