### ISSUE TITLE
Rhode Island Unassigned Deaths

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#3745]
Just confirming that the recent Rhode Island Unassigned Deaths update is correct; numbers do not make sense (both confirmed and deaths) [see attached spreadsheet].  If the cases have been reallocated then where have the been distributed to?
[Rhode_Island_Unassigned_Update_Feb28.xlsx](https://github.com/CSSEGISandData/COVID-19/files/6069449/Rhode_Island_Unassigned_Update_Feb28.xlsx)

**Comment by CSSEGISandData** [comment]
Hello,

I believe I understand your question correctly but please respond if this is incorrect. My interpretation is that your question is more generally related to why there are high numbers for unassigned for Rhode Island _for both cases and deaths,_ rather than a specific question related to the update which was _for deaths only._

Rhode Island publishes state level data every day but only publishes municipality data once per week (this is [their official google sheet](https://docs.google.com/spreadsheets/d/1c2QrNMz8pIbYEKzMJL7Uh2dtThOJa2j1sSMwiDo5Gz4/edit#gid=264100583)). Our unassigned category is the difference between the summation of the municipality level data (which we convert to county) and the state totals. The unassigned category contains cyclical increases in cases and deaths when the state total is updated but the municipality numbers are stale - this causes the unassigned category to have a substantial drop when the county level totals are subsequently updated. Additionally, the state total has consistently been much higher than those allocated to the states, which is the reason for the large number of unassigned cases and deaths.

**Comment by RetiredGeologist** [comment]
Hi,

 

I’m not concerned about the total numbers, but how they change over time.   My answer is probably explained by “The unassigned category contains cyclical increases in cases and deaths” if it included the word “decreases” [cyclical increases AND decreases].   The concerning issue is that both “Confirmed” and “Deaths” are cummulative fields.

 

Rowan Bonser

Retired Geologist

**Comment by RetiredGeologist** [comment]
Hi Again

 

Food for thought,   How do these changes effect the rolled up state numbers (Deaths only), have they been previously double booked?  What time frame does the “ cyclical decrease” in confirmed cases apply back to.

 

Rowan Bonser  

RetiredGeologist

**Comment by CSSEGISandData** [comment]
The state level roll-ups will always equal the state level total reported by the state. When there are drops in unassigned, they are matched by equivalent increases in all of the county values (plus any new cases/deaths reported that day).

**Comment by RetiredGeologist** [comment]
I’m sorry if I’m missing something,  but changes have been backdated as far as this time last year.  If the number of “unassigned deaths”  is reduced where did they go?  Where are as you put it … “When there are drops in unassigned, they are matched by equivalent increases in all of the county values”.  Where did they go?

 

 

I must admit I have yet to dive deep into the Rhode Island raw numbers because of the problem of knowing when to attribute the deaths to.  

Coming from Alberta I’m lucky that the Alberta Govt. releases the data attributed back to the day the individual tested positive for covid19. In some cases deaths have occurred over a 100 days of contracting the virus. 

 

Being retired I’ve had the time to digitally watch the spread of Covid19 Worldwide (Thanks to you guys), the relative numbers of asymptomatic cases in China and answer the question “if I catch the virus how long will it last?” (Again lucky to be in Alberta). I’m not a mathematician trying to predict curves..  I just look at the raw data!

 

Rowan Bonser

“Retired Geologist”

Geological Application and Oil & Gas Database specialist
