### ISSUE TITLE
Spain negative new cases

### ISSUE THREAD

**Issue by mercedeslga** [CSSEGISandData/COVID-19#3752]
Hi!!

How come that Spain last new cases (march 2nd) is a negative number?? It would be impossible, right?

Thank you!

**Comment by CSSEGISandData** [comment]
Hello

This is due to a drop in cases in Catalonia by nearly 80k. This correction is due to the identification of duplicated reporting within the region. See the Spanish health ministry report here: https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Actualizacion_323_COVID-19.pdf
