### ISSUE TITLE
Uk Deaths are incorrect for 03 Mar 2021.  Should be 315 not 487

### ISSUE THREAD

**Issue by angelvine** [CSSEGISandData/COVID-19#3762]

**Comment by CSSEGISandData** [comment]
Hello,

Please see this announcement available on [the UK COVID-19 Dashboard](https://coronavirus.data.gov.uk/):

https://coronavirus.data.gov.uk/details/whats-new#172_deaths_within_28_days_of_a_positive_test_added_to_scotland_and_uk_totals

"Public Health Scotland has improved its method for linking daily confirmed COVID-19 cases with deaths reported through the National Records of Scotland. As a result, an extra 172 deaths were identifed as having occurred within 28 days of a first positive test result since the start of the outbreak. These have now been added to the cumulative totals for Scotland and the UK."

The time series file available on the UK COVID-19 Dashboard have _not_ back distributed these deaths so we will not be able to.
