### ISSUE TITLE
Uganda Recovered  *huge variation*

### ISSUE THREAD

**Issue by peppeg** [CSSEGISandData/COVID-19#3896]
Good evening (for GMT friends :P)

on 3/26/21 Uganda recovered has gone from 15147 to 40379
this an official source for Uganda
https://covid19.gou.go.ug/index.html

obviously it might not be an error but an update or a fix ... But the variation is at least unusual ...

**Comment by CSSEGISandData** [comment]
Hello

Thank you for your message. On this date, it appeared that the Ugandan Ministry of Health began reporting home-based recoveries rather than just health-center based recoveries. This change in methodology resulted in a very large increase in recoveries reported by the health ministry.

See the following tweets from the Ugandan Health Ministry:

March 25 - [here](https://twitter.com/MinofHealthUG/status/1375003565761171456)
March 26 - [here](https://twitter.com/MinofHealthUG/status/1375395333790896131)
