### ISSUE TITLE
Pike in Daily Deaths for Argentina

### ISSUE THREAD

**Issue by nmorgant** [CSSEGISandData/COVID-19#3974]
It looks like there is an input error in the number of daily death in Argentina on the 1st of October 2020. It seems to be a mistake in the placement of the decimal separator. The current sequence (with the 1st of October in the middle) is: 
8.98, 9.25, 74.14, 6.88, 4.34
If you divide the middle number by 10, the sequence makes a lot more sense. The current number is statistically impossible for a country with dozens of millions o inhabitants.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. This issue has been previously documented in the [README](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#readme) of our data folder. The spike is due to the identification of previously missing deaths in Buenos Aires. Please see the government report [here](https://www.argentina.gob.ar/sites/default/files/01-10-20-reporte-vespertino-covid-19.pdf).
