### ISSUE TITLE
Spike in India Positive Case Data (April-21-2021)

### ISSUE THREAD

**Issue by surajsahani** [CSSEGISandData/COVID-19#3986]
Yesterday Data in India was 3 Lakhs , but is show only 115. Is something broken ?
![Screenshot from 2021-04-21 13-37-03](https://user-images.githubusercontent.com/22853459/115519384-c814a880-a2a6-11eb-800d-6df7ecf7f106.png)

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. This appears to be an issue with google's ingestion of our data rather than the data itself. Based on the date available in our [time series files](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series), these were the new daily cases we have reported the most recent days:

April 20: 295,158
April 19: 259,167
April 18: 273,802
April 17: 261,394

**Comment by HenkPoley** [comment]
Currently there is also an issue with the 'Apr 23, 2021' data for India being _0_.

https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&pickerSort=desc&pickerMetric=total_cases&hideControls=true&Metric=Confirmed+cases&Interval=New+per+day&Relative+to+Population=false&Align+outbreaks=false&country=~IND

**Comment by Salman098** [comment]
seems some glitch with google.

**Comment by Salman098** [comment]
....
