### ISSUE TITLE
Data error - Iceland recoveries for April 8 2021

### ISSUE THREAD

**Issue by ajayitdev** [CSSEGISandData/COVID-19#3995]
Dear Support,

From the recovered time series, https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv, Iceland is reported as having **61117** **cumulative recoveries** and **6256 cumulative cases** on April 8 2021 (https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv).

This is obviously incorrect, as the **number of recoveries is roughly 10 orders of magnitude greater than the number of cumulative cases**.

It would also help to know the specific data source, as I cannot find a count of recoveries on the Iceland Directorate of Health and Department of Civil Protection and Emergency Management website: https://www.covid.is/data.

Your assistance in rectifying this reporting error is greatly appreciated.

Thank you.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for flagging this issue. This is resolved by #3996. It appears to have been a data entry error on the [Iceland dashboard](https://www.covid.is/data) for publishing 61117 recoveries rather than 6117. Our recovery data is equivalent to their report of individuals that have finished isolation (currently 6223).
