### ISSUE TITLE
Recoveries in Slovakia not updated

### ISSUE THREAD

**Issue by empee4** [CSSEGISandData/COVID-19#4051]
Hello, I've noticed that recoveries in Slovakia are not updated and they remain constant since 02-13-2021.

[slovakia.txt](https://github.com/CSSEGISandData/COVID-19/files/6428796/slovakia.txt)

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. We source our data for Slovakia from the [government webpage](https://korona.gov.sk/koronavirus-na-slovensku-v-cislach/). Slovakia last provided an estimate for the number of recovered COVID-19 cases in the country on February 12. We have held that total static since that date. The data is not currently available but we are watching the site in case it is made available in the future.

**Comment by empee4** [comment]
Hello, I've done some research on this an I'm afraid that the recoveries won't be updated soon, since only Slovak mutation of that page seems to be updated properly and the numbers seem odd anyway. They don't match data on https://coronalevel.com/Slovakia/ nor https://www.worldometers.info/coronavirus/country/slovakia/, so I guess numbers reported on korona.gov.sk page won't be very useful anyway.

Thank you for you good work and quick reply :)
