### ISSUE TITLE
Luxembourg (Grand Duchy) does not show the latest active cases numbers (csse_covid_19_daily_reports)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#4094]
Hi all,

Luxembourg does publish its weekend cases on Monday. I checked on their website (https://data.public.lu/fr/datasets/covid-19-rapports-journaliers/#) and they have released an update yesterday, however it does not show in the JHU data. Currently, I am unsure if the data was published late and with yesterday's date or if there is a problem with picking up the numbers.
Could you kindly crosscheck on your side?

Appreciated!

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hi Christoph,

Thank you for your message. Luxembourg does not provide their daily report pdfs on the weekends, so the update in our daily products from yesterday includes the data for the past three days (I see that cases, deaths, and recoveries increased in yesterday's commit). 

A quick glance at our time series suggests this has been the case since the end of October 2020. Is there anything in particular for yesterday's commit that looks incorrect?

**Comment by c-hera** [comment]
Hi all,

thanks for the quick reply! The automated update on my side was too early today to catch the change. My bad, please disregard.

As always, you all are doing a fantastic job, much appreciated!

All the best,

Christoph
