### ISSUE TITLE
Ireland not being updated

### ISSUE THREAD

**Issue by glassel** [CSSEGISandData/COVID-19#4112]
The Ireland data are not updated since May 14

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. Please see the following notice posted on the [Republic of Ireland dashboard](https://covid19ireland-geohive.hub.arcgis.com/):

"Due to the current disruption of HSE IT system, the updates to the GeoHive COVID-19 Hub are paused until further notice."

We are hoping that we will be able to receive a proper back distribution for the days with disrupted reporting, but if this is an error with their ability to ingest data that it is unlikely to occur.

We will leave this issue open until the Republic of Ireland has resolved their technical issue.

**Comment by CSSEGISandData** [comment]
They have resolved their case and death data (finally). They provided a back distribution for cases but not for deaths, which we have integrated into our data.
