### ISSUE TITLE
Lombardy, Italy reduction of active cases (csse_covid_19_daily_reports)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#4182]
Hi all,

Lombardy, Italy seem to have dropped some cases since yesterday.

Date            | Active Cases | Difference
2021-05-31 |           31497 |         
2021-06-01 |           31142 |           -355
2021-06-02 |           21753 |        -9,389

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hi Christoph,

This is due to the Italian Ministry of Health reported a large set of recoveries for Lombardia yesterday. Please see [their dashboard](https://opendatadpc.maps.arcgis.com/apps/dashboards/b0c68bce2cce478eaac82fe38d4138b1). Select Regione "Lombardia" and the relevant metric is "Dimessi/Guariti". Select "Andamento" for the time series.
