### ISSUE TITLE
Sweden: Disrupted reporting 

### ISSUE THREAD

**Issue by kathsherratt** [CSSEGISandData/COVID-19#4241]
Data from the Swedish Public Health Agency (Folkhälsomyndigheten) were not reported over some days in late May and recently in June during a security breach of the data system. 

The timeline appears to be:
- 27-28 May - system closed; no new cases could be reported, due to security breach - [link](https://www.folkhalsomyndigheten.se/nyheter-och-press/nyhetsarkiv/2021/maj/folkhalsomyndigheten-anmaler-forsok-till-dataintrang-mot-sminet/)
- 1 June - system re-opened and data updated - [link](https://www.folkhalsomyndigheten.se/nyheter-och-press/nyhetsarkiv/2021/juni/uppdaterad-information-om-sminet-till-anvandare/)
- 13 June - system closed in the evening - [link](https://www.folkhalsomyndigheten.se/nyheter-och-press/nyhetsarkiv/2021/juni/databasen-sminet-tillfalligt-stangd/)
- 15 June - closure continues - [link](https://www.folkhalsomyndigheten.se/nyheter-och-press/nyhetsarkiv/2021/juni/antalet-fall-av-covid-19-fortsatter-nedat/)

This seems to have affected daily case and death data, but has had only a small impact when data are aggregated weekly. However I've found it difficult identify the exact impact, as data are quite spiky throughout the time series, and this could make a difference where we are using it (evaluating forecasts in the [European forecasting hub](https://covid19forecasthub.eu/)). 

It would be great to hear from anyone who has any more information on the exact dates and case counts that were missing.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you very much for this message. The 'spiky' time series is due to Sweden updating Tuesday-Friday only. By the wording of these announcements, I believe that the data will have been reported the subsequent Tuesday in most instances. I agree this will have a minor impact on the weekly aggregate numbers, and apologize that the Public Health Agency does not appear to be delineating which cases have been identified through this method.

Potentially a bigger problem for the European Forceasting Hub has been posted in #4264 as the Swedish dashboard has not been updated since June 15 due to this security issue.
