### ISSUE TITLE
Please add back Hong Kong, Taiwan and Macau, dont merge them into China!!!

### ISSUE THREAD

**Issue by ShawTim** [CSSEGISandData/COVID-19#425]
Yesterday the data of Hong Kong, Taiwan and Macau are still there.
We are here for data, not for political correctness.

**Comment by nguyenhychan** [comment]
The data from Hong Kong, Macao and Taiwan are issued from separate organisations than the one in mainland China. The regions also have their own borders so it does not make sense to merge them into the data for mainland China. Please split the data so that they could be analysed independently. Thank you.

**Comment by eacvo67347** [comment]
John Hopkins has lost all credibility here. Can anyone fork their repo?

**Comment by sam0737** [comment]
Grouping HK, TW, MO data's into CN's is like grouping Puerto Rico's into United State's, or Princess Diamond into UK or Japan. Taiwan is not even part of the WHO!

All these territories are taking different attitudes and measures towards COVID-19, they also have different administrative body, and different medical system.

Please keep the data the way it is, so they could be analysed properly.

**Comment by jeromaxyu** [comment]
Yes, putting things like credible-less WHO make your dashboard no difference, think again

**Comment by yookoala** [comment]
Separate different jurisdictions from each other helps visitor to better understand the actual status. It's stupid to merge them and confuse everybody just for the sake of a political gesture.

**Comment by albertcsm** [comment]
The definition of cases is significantly different among those regions, I don’t understand the merge, is it by accident, or politics?

**Comment by JiPiBi** [comment]
In  my extractions , in time series , I dont see that Macau , Hong Kong or Taiwan are integrated in Mainland China , so where is the issue ? 


Province/State | Country/Region
-- | --
Hong Kong | Hong Kong SAR
Taiwan | Taipei and environs

**Comment by anthonywong** [comment]
> In my extractions , in time series , I dont see that Macau , Hong Kong or Taiwan are integrated in Mainland China , so where is the issue ?

The dataset looks fine but the accompanying [website](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) for data visualisation doesn't. Look at the tally under "Confirmed Cases by Country/Region". Hong Kong, for example, used to have its own entry there but it's no longer the case. We are eager to know why.

Combining data of Taiwan, Hong Kong and Macau just doesn't make any sense. The government and people in these regions take very different measures to tackle this pandemic, and the numbers of infections in these areas can clearly demonstrate that. Data should be segregated for the purpose of drawing meaning conclusion rather than pursuing politically correctness (if that's the real motive behind the change).

**Comment by CSSEGISandData** [comment]
please see issue #482
