### ISSUE TITLE
Gaps and errors in Honduras, Kazakhstan, , Saudi Arabia likely more

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#4446]
Covid data for Guatemala, Kazakhstan, Saudi Arabia, Honduras and many more countries have gaps and mistakes . This is also causing the total confirmed cases to show incorrectly. 
Example1:Saudi Arabia data is same for 13th to 15th July and due to this, there is a sudden jump in cases on 16th july and again data is same from 16th to 20th july and on 21th the data has sudden jump. same pattern is followed again
Example2: Kazakhstan: data for 18th and 19th july is same and huge jumo in cases on 20th. data for 24th july is less than 23th july which is not possible.
Example3: Honduras: data is same from 15 to 20th July and huge jump in cases on 21th, and 23th to 26th July. and huge Jump on 27th July.
same can be found in many countries 

Gaps in :https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

**Comment by CSSEGISandData** [comment]
Hello,

In general these are due to sources having irregular update schedules. As all of our data is organized by _date of report_, if a source fails to provide a daily update the next update will have an abnormally large spike of data published.

For the specific examples you provide, we have patched some of the data for Honduras (#4452) and Saudi Arabia (#4453) where we missed a daily update but this has not removed the days where Honduras data is stale due to not publishing daily data.
