### ISSUE TITLE
Florida death data is not being updated

### ISSUE THREAD

**Issue by xapel** [CSSEGISandData/COVID-19#4497]
The deaths for Florida in "time_series_covid19_deaths_US.csv" has not been updated since the 3rd of June.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. The "Unassigned, Florida" entry updates on a once per week basis consistent with the reporting of the Florida Department of Health. The state has not provided updates on county level deaths since June 3.

**Comment by DanielJWood** [comment]
There appears to be weekly county-level death information on HHS and CDC's pages. See [HHS' COVID-19 Community Profile Report](https://beta.healthdata.gov/api/views/gqxm-d9w9/files/cc5a9c07-ade3-41c5-855d-54551776325b?download=true&filename=Community%20Profile%20Report%2020211203.xlsx) and reflected in the [CDC dashboard](https://covid.cdc.gov/covid-data-tracker/#county-view). 

Is there a reason this isn't being used instead of Florida Department of Health?
