### ISSUE TITLE
US data in global map is doubled

### ISSUE THREAD

**Issue by mcconnde** [CSSEGISandData/COVID-19#4538]
I import case data everyday into my own spreadsheet for US.  Today, 8-21-2021 it appears US case, death data is double what it is supposed to be as displayed in the global map.  Vaccination data is missing.

**Comment by BioTurboNick** [comment]
Just noticed this myself. I was seriously alarmed for a moment. Not that half is much better... But I rely on the JHU dashboard. Hope it gets fixed soon!

**Comment by CSSEGISandData** [comment]
Hello,

Can you be more specific as to in which file or tab of the dashboard you notice this issue?

**Comment by BioTurboNick** [comment]
I think it's every US state, at least. Here's Massachusetts. We in MA did not record 6k cases on Monday. Every other day is also doubled.
![image](https://user-images.githubusercontent.com/1438610/130347582-aa5b1f4f-2a91-4cea-bd84-001404ad4f1d.png)

**Comment by BioTurboNick** [comment]
Possibly related, looks like it's also affecting Deaths. And something really funky is going on with Daily Vaccinations

This is the US:

![image](https://user-images.githubusercontent.com/1438610/130347938-1afc3eeb-490a-4034-942c-8b52cd2842ea.png)

**Comment by benni-r1** [comment]
it is not only in USA wrong in daily values. view. for example germany have on 18. 8.234 cases daily. you list on daily for 18. 18.016 cases

same can also see on united kingdom. your daily values are much too high on dates previous. on 18 you post 67.516 . but there are not more than 35.000 cases in united kingdom. the highest was 52.000 since weeks ago

i dont know what happen with covid 19 dashboard. but it look unusable now and the values can not trust

**Comment by tamaragoyea** [comment]
Please standby...we are currently addressing this issue

**Comment by CSSEGISandData** [comment]
Thank you for your submissions. We are currently addressing and will announce as soon as possible when the issue has been resolved.

**Comment by CSSEGISandData** [comment]
Resolved in #4544
