### ISSUE TITLE
Daily data for 8/20/2021 and going forward still doubled? - US cases and deaths in map display

### ISSUE THREAD

**Issue by mcconnde** [CSSEGISandData/COVID-19#4546]
You closed issue #4538 and others stating WEEKLY data is now displaying correctly.  Please look at the US case display and deaths display in world map for DAILY data.  Starting on 8/20/2021 you display cases=319456.  CDC daily case rate is approximately half that at 157450.  I know they aren't expected to be exactly the same, but 1/2 is worthy considering the doubling problem you stated was fixed.  So, the question is for display of DAILY data from 8/20/2021  going forward is the data correct of still doubled.  Prior to 8/20/2021 it appears the data is as it was before the doubling problem

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the message. The doubling error has been resolved on August 22. The impact you are seeing for August 20 in isolation is almost entirely due to the Florida Department of Health, which we currently source for our data, publicly releasing COVID-19 data once per week. This results in a significant jump in our US level data for cases and deaths on Fridays, and can be clearly seen in the 28-day curve for the US and for the admin1 region of Florida. The CDC receives case numbers directly from Florida and thus is able to spread their updates over multiple days.
