### ISSUE TITLE
Daily cases for New Zealand is not being updated on regular basis, stats are from one day past

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#4554]
All updates on github for New Zealand - daily cases are one day old. Instances:
For 13th Aug, data is 1 on Worldometer and WHO, where as count is 0 on Github possibly because the data updates on Github are from one day prior- 12th Aug
For 16th Aug, data is 7 on Worldometer and WHO, whereas count is 0 on Github possibly because the data updates on Github are from one day prior- 15th Aug
For 18th Aug, data is 12 on Worldometer and 8 on WHO, where as count is 0 on Github 
Please look into it, if it is the expected count.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. The discrepancy you note is due to time zones and does not reflect an error in our dataset. All of our data is collected with a snapshot around 11:59 PM EST (GMT -5) and published in the time series and daily reports with the day when that snapshot was taken on the East Coast of the US. Wellington, New Zealand is in GMT +12. New Zealand publishes their [dashboard data](https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-current-cases) once per day at 9:00 AM GMT +12 which is 6:00 PM EST (one day prior). As such, all updates in New Zealand appear to have occurred one day prior in our dataset.
