### ISSUE TITLE
TX, Dewitt 

### ISSUE THREAD

**Issue by cestigarribia-dtt** [CSSEGISandData/COVID-19#4579]
Hello all, 

TX, Dewitt has reported 512 covid cases on saturday 28th when they've been reporting less than 10 cases lately.

Does anyone know the correct amount of cases that should've been reported?

Thank you.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. Our source for Dewitt, Texas is the [Texas Department of State Health Services](https://dshs.texas.gov/coronavirus/AdditionalData.aspx). By their [data notes for August](https://dshs.texas.gov/coronavirus/casenotes/august2021.aspx), only 198 of these case were "older", [meaning](https://dshs.texas.gov/coronavirus/DataDefinitions.aspx) at least 14 days have passed since the date of collection for the sample. The other cases all appear to have occurred in the 14 days leading up to August 28.
