### ISSUE TITLE
Florida death reporting methodology

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#4593]
Hi CSSE team,

This report in the Miami Herald shows that Florida has made some changes to the way it is publicly reporting death counts: https://www.miamiherald.com/news/coronavirus/article253796898.html

> Until three weeks ago, data collected by DOH and published on the CDC website counted deaths by the date they were recorded — a common method for producing daily stats used by most states. On Aug. 10, Florida switched its methodology and, along with just a handful of other states, began to tally new deaths by the date the person died.

The CDC website is showing a dramatic decline in daily deaths for Florida, if you select Florida here: https://covid.cdc.gov/covid-data-tracker/#trends_dailydeaths

My understanding though is that JHU uses the weekly report published by Florida DOH here rather than the daily totals provided to the CDC: https://floridahealthcovid19.gov/

I wanted to confirm that JHU has been reporting death counts by date of report for Florida thus far, and see whether you know if the changes mentioned in the Herald article will impact your ability to keep doing so using the weekly DOH report. 

It looks to me like you may have a way around this since [last week's DOH report](http://ww11.doh.state.fl.us/comm/_partners/covid19_report_archive/covid19-data/covid19_data_latest.pdf) shows 389 weekly deaths compared to your report of 1,727, but it would be great to confirm.

Thanks in advance for any insight!

**Comment by CSSEGISandData** [comment]
Hello Nate,
You are correct that we are maintaining our data by “date of report”. To our knowledge, the change in methodology will not affect our ability to continue reporting by date of report. We report the cumulative number of deaths reported in each weekly report rather than relying on the "weekly death" metric in the report, which has not consistently been equal to the difference between the new report and report prior.

Please let us know if you have any other questions.

**Comment by naterattner** [comment]
Thank you for confirming and for the additional context, @CSSEGISandData. Much appreciated.
