### ISSUE TITLE
New daily cases mismatches with Official data for Israel

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#4613]
There are data discrepancies between the official Covid stats dashboard of Israel and the data provided by JHU.

e.g. In 31 Aug- Israeli dashboard shows [10,947 new cases](https://datadashboard.health.gov.il/COVID-19/general?tileName=newVerifiedDaily) while JHU's data shows 4,864 new cases (which means our new cases trenline feature also shows 4,864 new cases)

However I feel that this discrepancy in OW and JHU might be because the "New verified - daily" in OW might be confirmed active cases and In JHU the data is new daily increment cases(I came to this conclusion based on WHO data which depicts both the info together, check file attached) , is it so? ![Screenshot 2021-09-06 4 18 55 PM](https://user-images.githubusercontent.com/87356889/132207820-718ccc58-8edb-40f3-a6fb-d1a458483684.png)

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for posting this issue. First, allow me to state that our data products represent a snapshot of data published on all of our sources between 3:30 and 4:00 AM UTC. They do not correct for local time zones.

This apparent discrepancy is due to the frequency and timing of updates to the Israeli COVID-19 Dashboard. The data tracker website states that the dashboard updates [three times per day](https://www.gov.il/en/departments/guides/information-corona). Our internal data has shown high levels of heterogeneity for when these updates occur. 

On occasion, one of the three daily updates occurs early enough in the morning Israeli time (GMT+3) that it is recorded in the daily capture for the "previous" day in our dataset. When this occurs, that day captures four updates within a 24 hour cycle and the next day only captures two updates.
