### ISSUE TITLE
Error in COVID data reporting for SOUTH AFRICA on 23 November 2021

### ISSUE THREAD

**Issue by jaimsb** [CSSEGISandData/COVID-19#4950]
There is an error in the covid case reporting for South Africa on 23 November 2021. We did not have **18586** cases on that day it was roughly 10 times less than that. Please correct

**Comment by HannahRitchie** [comment]
I think the correct number should be 868 based on the official source: https://sacoronavirus.co.za/category/daily-cases/

**Comment by edomt** [comment]
FYI, this is due to a backlog of 77,157 additional tests imported for inclusion. This has resulted in a total of 18,586 new cases reported, but the estimated number of new cases for 23 Nov 2021 is 868.
https://twitter.com/nicd_sa/status/1463200722615513093

Because of this, most likely this won't be changed in the JHU data since they rely on the latest-reported cumulative total to build their time series.

**Comment by 3dgiordano** [comment]
Hello everyone, I add some information.

The problem seems to be the information provided by the official site. In the "Positive cases" section (thanks @HannahRitchie for the source)
That value is what it seems to be taking, and it is the one that differs from the daily value reported by the official source.
Since that date they have been reporting with that jump in cases.

I do not know if they made a historical changes and that jump happens for that reason.

If they has access to updated historical data it should be able to detect when the changes were made to update its history so that the calculations close to the real daily new cases.

Does their data for South Africa appear to be daily?

Good point provided by @edomt, surely the inclusion of all those tests that had been excluded from reporting to the counter generate the problem.
But if those positive tests were aggregated historically, it shouldn't have caused the glitch in the daily data.

If South Africa did not do it historically and incorporated it on that day, surely there will be that inconsistency between what they say is of the day with what they added to the general counter.

I hope the information can be helpful to whoever performs the analysis.

**Comment by CSSEGISandData** [comment]
Thank you @edomt. Announcement made in #4956.

**Comment by svobora** [comment]
Very funny, due to this stupid addition a lot of countries have blocked travel from RSA.

**Comment by WayneDV** [comment]
> Very funny, due to this stupid addition a lot of countries have blocked travel from RSA.
That's not accurate - they imposed the travel ban for fear of the omicron strain, first identified in bulk in South Africa

**Comment by svobora** [comment]
It is quite accurate, the claims are the variant is highly virulent due to 10x increase of seven day average in one week.

**Comment by jaimsb** [comment]
Thanks very much for that info.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
