### ISSUE TITLE
South Africa incorrect cases

### ISSUE THREAD

**Issue by Laboas** [CSSEGISandData/COVID-19#4959]
There were NOT 6000 cases on 27 November - how can you report incorrect information when the world is watching? Where is the responsibility and accountability for your actions? The South African government has a publicly available website with correct reporting. USE IT!!!!

**Comment by CSSEGISandData** [comment]
Thank you, this was patched in #4965. This happened because the data published on November 27 included two days worth of tdata. The South African government's data portal did not update prior to our daily cutoff on November 26, resulting in a single 24 hour period (November 27) containing two days worth of data. We have used an announcement on [their Twitter](https://twitter.com/nicd_sa/status/1464277820314685444?s=21), which did include the data for November 26, to correct our historical data.
