### ISSUE TITLE
The search within the page is messed up

### ISSUE THREAD

**Issue by Epi-Mic** [CSSEGISandData/COVID-19#5024]
Hi, thanks for your work. You have slightly modified the main page with all the staff, but now it's not possible to find a country within the page. I tried Google Chrome, M. Edge, mobile browser with no result.

**Comment by CSSEGISandData** [comment]
Thank you. We're aware and currently investigating.

**Comment by mynameissue** [comment]
I found the same issue.  I can't search by a country name with F3 in chrome.
I suppose that this is because that the specification of the list of country name, 28-day cases/deaths, and totals cases/deaths was changed in this month and the elements at the bottom of the list don't exist in the browser unless I scroll the list.

Before the change, I could search any countries with f3.
I hope that the the list is reverted to the previous version.

**Comment by CSSEGISandData** [comment]
This has been resolved. Apologies.
