### ISSUE TITLE
Isle of Man data seems very high compared to source

### ISSUE THREAD

**Issue by DrBazUK** [CSSEGISandData/COVID-19#5163]
As commented on the [OWID Github](https://github.com/owid/covid-19-data/issues/2231) it seems that the Isle of Man data is running very high compared to the Ministry of Health on the island.

Currently total from JHU is: 17,948 cases, MOH has it at 13,475 and there's no new data on the dashboard since 5/Jan.

Could you please investigate and see if there is an issue with data collection/processing?

Thanks in advance,
Baz

**Comment by CSSEGISandData** [comment]
Hello,

Our data for Isle of Man is matching that published on the [WHO COVID-19 Dashboard](https://covid19.who.int/region/euro/country/im). The discrepancy, as near as we can suspect, may be caused by positive lateral flow tests not being integrated into the "investigated cases" total on the Isle of Man Dashboard immediately but being integrated into the WHO COVID-19 Dashboard. We reason this due to the difference in "investigated cases" on [January 5](https://covid19.gov.im/media/2020/public-covid-summary-050122-1-8.pdf) and [January 6](https://covid19.gov.im/media/2021/public-covid-summary-060122-1-8.pdf) only being 47 cases but the report on January 6th reporting 283 positive LFT results in the past 24 hours.

The inclusion of the positive lateral flow tests is consistent with our approach for other locations. We will continue to investigate this issue.
