### ISSUE TITLE
JHU Data Backend Updates (NOTICE)

### ISSUE THREAD

**Issue by CWrecker** [CSSEGISandData/COVID-19#52]
It makes for a lot of down time on the developers end if the file structure is constantly changing without a warning. Maybe a notice could allow developers to make changes before the edits go live. :D

**Comment by dawenx** [comment]
i raised the same concern in my reply for #50. As much as we appreciate JHU's hard work, a sudden change like this is not necessary.

**Comment by CWrecker** [comment]
Yes, please don’t get me wrong. It’s amazing what you guys are doing. I can’t wait to keep adapting with you.

**Comment by Bost** [comment]
> It’s amazing what you guys are doing. 

No it's not. This is an example how NOT to manage data. All the structure and format changes significantly lower the value and the credibility of this information source, adding up its faire share of noise to the information uncertainty surrounding this virus outbreak.

I'm starting to consider applying some sort of a noise filtering and/or signal smoothing techniques over this information source coupled with using additional information source.

**Comment by Sitius86** [comment]
Agree with Bost.  If you're going to link your CNN-referenced dashboard to the source data sets and solicit media coverage (intentional or unintentional)...you now assume responsibility to provide some baseline structure, consistency, and reporting integrity. This repository is unacceptable in its current condition. 

Please consider leveraging the Github community of world-class developers and engineers, some of whom have graciously offered to assist with what is clearly becoming a data management issue at a scale you weren't prepared for. This type of thing happens at every company every day, but misinformation in your case may cost people their lives. Consider that, even if briefly, before you blitz through your backend changes and cast doubt on the entire dataset. 

Who is reviewing this work? Why is this considered acceptable for an esteemed research institution like Johns Hopkins? What is the intent of posting this data publicly if you can't manage it properly for public consumption? You have mainstream media citing numbers from your dashboard every day. This is troubling, knowing the process, or lack thereof, behind your numbers.

**Comment by CSSEGISandData** [comment]
Hello, we were maintaining and updating our GitHub early today. We will keep collecting the data and make it public. Sorry for the sudden change if that causes any inconvenience for you. Thanks

**Comment by bicubic** [comment]
@CSSEGISandData can you please try to announce further breaking changes ahead of time with a clear explanation of the planned change. Ideally though, it would be great to land on a stable format and keep location/format changes to a minimum.

**Comment by CWrecker** [comment]
Thanks for the response, I will rename this thread to JHU BACKEND UPDATES. Feel free to continue posting here with updates if that makes things easier, otherwise, the readme file is just as appropriate.

**Comment by Sitius86** [comment]
Appreciate the improved communication. Thank you for addressing your Github group directly @CSSEGISandData !

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238

**Comment by CSSEGISandData** [comment]
Any major changes we will be updating the read me to notify users in advance. We are closing this thread. Any new issues or requests please report a new issue. Thank you!
