### ISSUE TITLE
[France][Total death] Exceeded 127,000 as per public health figures as of 18th Jan

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5251]
Look at the public health figures in France, the number of deaths has exceeded 127,000, as per [santepubliquefrance](https://www.santepubliquefrance.fr/dossiers/coronavirus-covid-19/coronavirus-chiffres-cles-et-evolution-de-la-covid-19-en-france-et-dans-le-monde),  ![Screenshot 2022-01-19 5 01 47 PM](https://user-images.githubusercontent.com/87356889/150122788-d13c78f4-d441-40e9-aae6-417acbf9b9e3.png) the count of deaths in France is 127638  and as per [worldometer](https://www.worldometers.info/coronavirus/#countries ) it is 127368.

As per [JHU](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/01-18-2022.csv ), Total number of deaths in France  is ~ 125000

Please look into this discrepancy

**Comment by CSSEGISandData** [comment]
Hello,

The totals published by sante publique include deaths in several overseas territories and departments that are independent entries in our dataset (Mayotte, Reunion, Guadeloupe, French Guiana, and Martinique). We remove the cumulative cases and deaths from these territories from the France, France entry so that they are not double counted in our dataset. These is detailed in #2459.
