### ISSUE TITLE
Hong Kong new cases for 7th,8th,9th Feb 2022 are very less when compared with official websites 

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5380]
For the location of Hong kong new cases for the dates 7th,8th,9th Feb 2022 are very less when compared with official websites and other sources .
Current count
(7th Feb 2022) = 361
( 8th Feb 2022) = 150
(9th Feb 2022) =  635

[Worldometer](https://www.worldometers.info/coronavirus/country/china-hong-kong-sar/)
(7th Feb 2022) = 614
( 8th Feb 2022) = 625
(9th Feb 2022) =  1161

[CoronaTracker](https://www.coronatracker.com/country/hong-kong/)
(7th Feb 2022) = 614
( 8th Feb 2022) = 625
(9th Feb 2022) =  1161

[Official website](https://www.coronavirus.gov.hk/eng/index.html )

This is also observed for the previous month(Jan).

[Github](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)

Kindly look into this.

**Comment by CSSEGISandData** [comment]
Thank you for raising. The discrepancy appears to be due to the Hong Kong dashboard (https://www.chp.gov.hk/en/features/102465.html) adding the metric "Tested Positive". We match the "Confirmed" count. We have reached out to the managers of the dashboard to a) obtain clarity for the difference between "Tested Positive" and "Confirmed" and b) obtain historical data to correct our time series in the instance that the "tested positive" metric is consistent with our definition of probable cases.

**Comment by CSSEGISandData** [comment]
See #5478.
