### ISSUE TITLE
Daily confirm cases count for Hong Kong is not correct - 25 & 26 Feb

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5490]
JHU Feed: 
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv 

For 25th Feb 2022 JHU is showing the confirmed cases count as 10010, for 26th Feb 2022 it is showing 44899 confirm cases . 
However, as per Worldometer it should be 10622 for 25th Feb 2022 and 17053 for 26th Feb 2022.  https://www.worldometers.info/coronavirus/country/china-hong-kong-sar/ 

Official website of hong kong showing similar numbers as of worldometer. https://www.chp.gov.hk/files/pdf/local_situation_covid19_en.pdf 

Looks like there is a discrepancy in the data on JHU. Please look into this.

**Comment by CSSEGISandData** [comment]
Thank you for your comment. Our data matches that of the [Hong Kong COVID-19 Dashboard](https://chp-dashboard.geodata.gov.hk/covid-19/en.html). Please toggle to the "Statistics on Cases Tested Positive for SARS-CoV-2 Virus" and observe the graphic "Statistics on Cases Tested Positive for SARS-CoV-2 Virus" in the top left. The discrepancy may be due to the disclaimer on the document you have provided that "Re-positive cases are excluded in Figure 1(I)" and "Re-positive cases are excluded in Figure 1(ii)", but we can't be certain.
