### ISSUE TITLE
Mismatch of Hong Kong data

### ISSUE THREAD

**Issue by Zhanlgu** [CSSEGISandData/COVID-19#5538]
Hi,

The website of Hong Kong COVID-19 changed again. It added new features to separate the number of Nucleic acid tests and RAT tests. The total number should be the sum of the numbers of both 'Local' and 'RAT'.

Thank you.

**Comment by Maggiehukse** [comment]
Yes Hong Kong has started to recognize RAT test result since Feb 26 (source: https://www.scmp.com/news/hong-kong/health-environment/article/3168372/coronavirus-hong-kong-only-third-infections), this local news media listed the no of total confirmed cases after adding up both results. https://www.hk01.com/%E7%A4%BE%E6%9C%83%E6%96%B0%E8%81%9E/748286/%E6%9C%80%E6%96%B0%E7%96%AB%E6%83%85-%E7%B4%AF%E8%A8%88%E7%A2%BA%E8%A8%BA%E5%8B%A2%E7%A0%B4100%E8%90%AC-%E4%BB%8A%E5%8F%AF%E7%94%A8ha-go-app%E9%A0%90%E7%B4%84%E6%8C%87%E5%AE%9A%E8%A8%BA%E6%89%80

**Comment by CSSEGISandData** [comment]
Please see #5546
