### ISSUE TITLE
Discrepancy in Canada daily new cases & death cases

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5822]
On external sources like Corona tracker  and Worldometer the daily new cases & death cases  data for mentioned dates is different. 

Worldometer  (https://www.worldometers.info/coronavirus/country/canada/ )
15th June : New Cases = 3526  & Death = 53
16th June : New Cases = 4115  & Death = 115

Corona tracker (https://www.coronatracker.com/country/canada/ )
15th June : New Cases = 3526  & Death = 53
16th June : New Cases = 4115  & Death = 115

There are many sources mentioned from which JHU takes its data. I am not sure from which source the current stats are being taken. 

Please look into this. 
Thanks

**Comment by CSSEGISandData** [comment]
Thank you for your question. As noted in the issue, the difference is almost certainly due to different sourcing used by the aggregators. The sourcing for WorldoMeter is [a media source](https://www.ctvnews.ca/health/coronavirus/tracking-every-case-of-covid-19-in-canada-1.4852102) while the sourcing for Corona tracker is not immediately clear. Our data composites across all of the sources listed in the README to ensure the source with the highest total is being reported for a specific region. This is due to irregular update schedules and timeliness between the sources. We can not comment on the approach used by WorldoMeter or Corona tracker.
