### ISSUE TITLE
Discrepancy in France death stats. 

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5823]
Cumulative death statistics as of 16 June 2022 is 145,711 in JHU feed for France.

However, in  [(Source]((https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/) for JHU for French dataset  listed in their Readme section , it shows cumulative deaths as of 16 June , 2022 as 148,996.

Please look into this.

**Comment by CSSEGISandData** [comment]
Thank you very much for your question. This is due to the logic for calculating totals for mainland France as detailed in #2459. The total reported in the linked source includes cases and deaths that occurred in DROM (overseas territories and dependencies) which we report separately in our database. The logic subtracts the DROM totals reported by WHO from the total France report to calculate values for mainland France.
