### ISSUE TITLE
Wrong data reported for Lithuania. Please use official source!

### ISSUE THREAD

**Issue by jonas-bac** [CSSEGISandData/COVID-19#5839]
Dear JHU team,
 
I am writing to you on behalf of Statistics Lithuania, an official body responsible for calculating national COVID statistics in Lithuania. We noticed worrisome mismatches in the numbers that [you report](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data) to the World with the numbers in our official statistics (see figure below).
 
Please be so kind and clarify, where do you get the data about the pandemics in Lithuania? We would like to kindly ask you to use our official numbers as the data source. Our official statistics can be easily accessed via an automated query to the files feeding the dashboards ([osp.stat.gov.lt/covid-dashboards](https://osp.stat.gov.lt/covid-dashboards)) or by downloading the daily-updated openData files ([osp.stat.gov.lt/covid-open-data](https://osp.stat.gov.lt/covid-open-data) -> “Agreguoti COVID-19 atvejai ir mirtys”).

Do not hesitate to contact us: [covid@stat.gov.lt](covid@stat.gov.lt).
 
Jonas Bačelis
COVID data team
Statistics Lithuania

<img width="860" alt="Screenshot 2022-06-25 at 11 15 29" src="https://user-images.githubusercontent.com/9981950/175764889-27a5d99b-99ed-48b5-9be9-b11270ea571b.png">

**Comment by CSSEGISandData** [comment]
Dear Jonas,

We have sent an email to covid@stat.gov.lt and look forward to hearing from you.

For all other parties, the reason for the discrepancy is that our case totals only included total persons infected (Iš viso bent kartą užsikrėtusių asmenų skaičius) and not total infections (Iš viso buvusių/esamų užsikrėtimų skaičius). Total infections are more consistent with the COVID-19 case described by the CSTE and endorsed by the US CDC. Our data was still sourced from the dashboard linked above and in our source list README.

We have enquired with the source (above) for a back distribution by date of report. In the interim, our live data has been updated to include total infections rather than total persons infected.

**Comment by CSSEGISandData** [comment]
Thank you @jonas-bac and your team. We have used your provided data to correct our time series in [this commit](https://github.com/CSSEGISandData/COVID-19/commit/bab95b2a25657629b313697bb3434c22e9acab4f).

For the SA of all other users, the data that we used to correct was Lithuania's case time series by date of infection offset -1 day. The department assured us this was the closest product they had internally that would allow us to back distribute by a metric near _date of report_.
