### ISSUE TITLE
Time series for U.S. not accurate

### ISSUE THREAD

**Issue by rsmiller74** [CSSEGISandData/COVID-19#589]
Looks like the state totals in the time series file is not accurate prior to March 10.  Example is Colorado which is reported to have zero cases on March 9th but in the daily data lists cases.

**Comment by kalderon** [comment]
I think this is because there are individual towns / counties listed lower down, and some of these do have cases earlier than March 9th (eg Douglas County, CO). These numbers are not being included in the state totals **apart** from on March 10th and 11th - which is a consistency error that wants fixing.

**Comment by CSSEGISandData** [comment]
see issue #590
