### ISSUE TITLE
JHU source data for deaths and JHU github feed are not matching for UK

### ISSUE THREAD

**Issue by Saurabh0027** [CSSEGISandData/COVID-19#5947]
JHU source data for deaths and JHU github feed are not matching, as on the source last five days stats are incomplete. Could you please tell us how JHU is extracting and calculating for a 7-day average using these stats from source or if there is any update kindly share with us.

JHU Source: https://coronavirus.data.gov.uk/details/deaths?areaType=nation&areaName=England 

Github feed: https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/total_deaths.csv

**Comment by CSSEGISandData** [comment]
Hello,

My understanding of your question is that you are comparing our [time series for global deaths](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) to the [Deaths in England](https://coronavirus.data.gov.uk/details/deaths?areaType=nation&areaName=England) data published on the UK COVID-19 Dashboard. Please feel free to reopen this issue if I am mistaken. I believe there are three things to note here that explain the apparent discrepancy that you are referencing:

1) The total deaths for mainland UK (England, Scotland, Wales, and Ireland) in our dataset are being compared to the value only for England on the source side, which is incorrect. Please navigate to [this link](https://coronavirus.data.gov.uk/details/deaths) on the UK COVID-19 dashboard. Of note, the headline UK numbers for deaths are not equivalent to the sum of each nation independently so please see also the [England dashboard](https://coronavirus.data.gov.uk/details/deaths?areaType=nation&areaName=England), [Scotland dashboard](https://coronavirus.data.gov.uk/details/deaths?areaType=nation&areaName=Scotland), [Northern Ireland dashboard](https://coronavirus.data.gov.uk/details/deaths?areaType=nation&areaName=Northern%20Ireland), and [Wales dashboard](https://coronavirus.data.gov.uk/details/deaths?areaType=nation&areaName=Wales).
2) The visualizations and data tables on the UK COVID-19 dashboard are all time series files organized by the _date of _death__ metric while our time series is by _date of report_. Across each of the four nations, 183,953 total deaths have been reported as of 7-28-2022 (these can be checked using the above links). Hence, our data for 7-28-2022 for the UK is 183,953. Files based on _date of death_, such as the UK COVID-19 dashboard, are constantly revised based on new deaths being reported. Our approach allows for new values to be appended to an existing time series rather than rewriting all files on each update cycle.
3) Lastly, we are not responsible for the calculation of the 7-day average published by Our World in Data in their visualizations.
