### ISSUE TITLE
Israel deaths data inconsistent with official numbers

### ISSUE THREAD

**Issue by RonBarkan** [CSSEGISandData/COVID-19#5950]
Most recent deaths data is inconsistent with the official Israeli numbers and graphs.
For example, the data shown on JHU arcgis dashboard shows 34 deaths on July 26th.
The data from Israel's ministry of health dashboard https://datadashboard.health.gov.il/COVID-19/general says 3 deaths on July 26th.
Other dates also don't agree.

**Comment by CSSEGISandData** [comment]
Thank you for your question. The graph to which you are comparing our data to is based on _date of event_ while our data is based on _date of report_. The historical data presented by the Ministry of Health will continually be modified. For example, the data on the dashboard now displays four deaths on July 26th rather than the three present when this issue was posted. You can also compare the present data on the Israeli dashboard to an [ interactive screenshot via the Wayback machine](https://web.archive.org/web/20220706104038/https://datadashboard.health.gov.il/COVID-19/general) from July 14th. At that time, July 2nd had one death versus the twelve now being reported.

Our approach, which is the same for practically all locations, is to append the latest cumulative total of cases and deaths to our time series files. At present, this is 11,349 deaths.
