### ISSUE TITLE
Covid stats of July 29, 2022 for India are incorrect

### ISSUE THREAD

**Issue by Saurabh0027** [CSSEGISandData/COVID-19#5972]
Hello,

As verified from the **Ministry of Health and Family Welfare's** Official [Twitter account](https://twitter.com/MoHFW_INDIA), the **_new reported cases_** for July 28, 2022 were [20,557](https://twitter.com/MoHFW_INDIA/status/1552524594346889216) . Whereas for July 29, 2022, the count was [20,409](https://twitter.com/MoHFW_INDIA/status/1552877018785927168) -contrary to this, the Covid 19 stats for July 29, 2022 on the GitHub feed are found to be having a cumulative count of both July 28 & 29, 2022 statistics; which is 40,817.

Since there is a data discrepancy issue in the feed (_due to the fact that no recent updates are mentioned in the errata file; pertaining to backdated stats distribution_), request you to please check and fix the corresponding data statistics.

Thanks!

**Comment by CSSEGISandData** [comment]
Thank you for your question. Two small issues to note here:

First, because of time zone differences our data for India is dating back in one day (as our repository is based in EST). Due to this, we report 20,557 new cases on July 27, matching the [twitter post for July 28](https://twitter.com/MoHFW_INDIA/status/1552524594346889216).

Second, you are correct that we were mistakenly stale on July 28. We will correct our data shortly.

**Comment by CSSEGISandData** [comment]
Patched in #5997
