### ISSUE TITLE
Incorrect Covid death cases of   7th July 2022 for Belgium.

### ISSUE THREAD

**Issue by Saurabh0027** [CSSEGISandData/COVID-19#5973]
For location Belgium the data is provided on Tuesday and Friday as per Github. We checked the feed death data. But this is not matching with the source. Can you please tell the algo behind these stats.

Github: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data 

Source: https://datastudio.google.com/c/embed/reporting/c14a5cfc-cab7-4812-848c-0369173148ab/page/QTSKB

**Comment by CSSEGISandData** [comment]
Thank you for your question. If your question is related to the update days, our data collection frequently catches Belgium's updates on Mondays and Thursdays as the source updates very early in the day Belgium time (I.e., it is still the day prior in Eastern Time, which is the time zone that this repository uses to make daily cut-offs). In this way, it is updating Tuesday and Friday locally but present on Mondays and Thursdays in this repository.

If your question is about daily cases/deaths plots on the sciensano source, these are continually modified as new data comes in. Our historic data is not commonly modified as the data is updated by appending new values to the time series files rather than completely rewriting all entries.
