### ISSUE TITLE
South Africa COVID data

### ISSUE THREAD

**Issue by dlluskin** [CSSEGISandData/COVID-19#5992]
Looks like both cases and deaths in South Africa have not changed for weeks. Has that nation stopped reporting, or is something broken? Thanks!

**Comment by leemyungsub** [comment]
2022년 8월 14일 (일) 오후 11:19, dlluskin ***@***.***>님이 작성:

**Comment by CSSEGISandData** [comment]
Thank you for your question. The [South Africa Department of Health](https://sacoronavirus.co.za/) has not updated their statistics since July 29, 2022. The [WHO COVID-19 Dashboard](https://covid19.who.int/region/afro/country/za) has been providing updates in the interim, so we are adjusting our process to pull in data from WHO. We will also be correcting our historical data for the period where WHO was updating while the South Africa Department of Health was not.

**Comment by dlluskin** [comment]
Thank you!!!

-=-=-=-=-
Donald L. Luskin
Chief Investment Officer, TrendMacro
Room Rater<https://twitter.com/BookLockdown/status/1533278533987905537> score: 9/10

**Comment by dlluskin** [comment]
I see you have posted the updated cases series. But there is still nothing be reported for deaths.

-=-=-=-=-
Donald L. Luskin
Chief Investment Officer, TrendMacro
Room Rater<https://twitter.com/BookLockdown/status/1533278533987905537> score: 9/10

**Comment by CSSEGISandData** [comment]
Thank you. Both the South Africa Department of Health and WHO COVID-19 dashboard are reporting no new deaths since July 29.
