### ISSUE TITLE
displaying outdated values

### ISSUE THREAD

**Issue by jmhmjayamaha** [CSSEGISandData/COVID-19#622]
latest update doesn't display the correct values of total number and others.

**Comment by becare-rocket** [comment]
To: Everyone ... we all see the bad data.  We have to recognize that the John Hopkins team is overloaded as they are normalizing a vast dataset.  My suggestion is that each of you using the data volunteer to make a small donation to John Hopkins earmarked for the data team so that they can get some more data analysts working on the database. Email them for contact details.

**Comment by EpicureanHeron** [comment]
Seems to be missing at least the following:

Italy
Iran
Spain
Germany

**Comment by analyzewithpower** [comment]
@becare-rocket  it works for them in their dashboard. They can just do an export from the dashboard.

**Comment by nokyotsu** [comment]
It would be great if they provide easily available information on how to donate to their team. I would be very glad to contribute.

**Comment by EpicureanHeron** [comment]
The only source I could find for donations is the following on the Whiting School of Engineering site:

https://engineering.jhu.edu/alumni-giving/ways-to-give/

Seems to facilitate larger gifts, which is great and all, but it would be nice to have a patereon-esque way to give to support this specific project and their team.

**Comment by EpicureanHeron** [comment]
This can probably be closed as it looks like the data has been updated successfully.

**Comment by emilianbold** [comment]
Probably related to #650, all recent data is flawed.

**Comment by jmhmjayamaha** [comment]
Closed the issue, it looks like they updated the correct data.
