### ISSUE TITLE
ISSUE - Czechia: Number of confirmed cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6310]
Hello, Team!
Could you please check the data for the following series - Czechia: Number of confirmed cases
We can observe a large jump (value 4557086) for the 11/29/2022 period and it looks suspicious to us. Could you please confirm that the data is correct and advise the reason for the following jump? 
Thank you!

**Comment by CSSEGISandData** [comment]
Thank you. We've confirmed that this is due to the Czechia case total now including reinfections on the [source website](https://onemocneni-aktualne.mzcr.cz/covid-19). We're preparing a back distribution of reinfection data to when it was first reported on their site so we can roll these cases into our historical reporting of confirmed cases. Please standby.

**Comment by CSSEGISandData** [comment]
Please see #6313 and #6312.
