### ISSUE TITLE
China has stopped its asymptomic case report

### ISSUE THREAD

**Issue by ZauberViolino** [CSSEGISandData/COVID-19#6358]
But the cases from "Unknown, China" still rose from 1,516,591 to 1,521,800 (+5,209). Is there any sources to asymptomic cases in China that I haven't heard of?

**Comment by CSSEGISandData** [comment]
Hello,

We just posted #6359 as documentation indicating that we are ceasing the reporting of new asymptomatic cases. The +5,209 represented the asymptomatic cases reported on 12/12, we publish the daily asymptomatic cases the following day due to the timing of the reports being released and our ability to consistently work outside of business hours. See #5579 for previous documentation.
