### ISSUE TITLE
Why time series for Czechia decreases?

### ISSUE THREAD

**Issue by radekm** [CSSEGISandData/COVID-19#6620]
Hi,

I'm looking in `time_series_covid19_confirmed_global.csv` at data for Czechia.
On 2022-10-26 there are 4519021 cases and 1 day later on 2022-10-27 there are 4512136 cases.

How is it possible that cumulative data decreased by 6885 cases? Or are these not cumulative?

Thanks

**Comment by radekm** [comment]
I also looked official source and got following

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/518912/221292711-db9ee15a-794b-41ed-9be6-9eeac63ca660.png">

But it's possible that I'm looking at something different, unfortunately I'm not sure.

**Comment by CSSEGISandData** [comment]
Hello,

Our data is cumulative. Decreases in our time series files occur when sources publish decreases in their data (due to data cleaning processes, etc.). We do our best to not retroactively modify our historical data. Czechia modifies their historical data with some regularity, hence why you don't see the decrease in their data. This has been discussed in #4296 and #3819. You'll find that the data snapshots in our repository do not perfectly line up with the historical data table published on their website due to data cleaning on their end.
