### ISSUE TITLE
3/13 Upload has no data

### ISSUE THREAD

**Issue by analyzewithpower** [CSSEGISandData/COVID-19#686]
3/13 upload has no data, all values are null. 

Are you able to update?
Can you provide a clean new file?

Thanks!

**Comment by r-lomba** [comment]
Also, data in the 3/12 column haven't been fixed since yesterday. A lot of Countries (e.g. Italy, but al least 6 of them) had no increase in the number of confirmed, recovered or death. I don't seem to have found any readme about how to deal with the issue. 

You guys are doing a huge job and we are all grateful for this, but the data is not reliable anymore and there are no explanations

**Comment by FiveThirteen** [comment]
Agree with both comments above.

**Comment by jnolan00** [comment]
Same here. Also several states in the US are missing now from the daily status.

**Comment by clyde7** [comment]
The daily report for 3/13 looks legit. Can we backfill?

**Comment by sibblegp** [comment]
Here to chime in. We're down (https://covid.bio). Data is not properly formatted.

It's poor person's QA

**Comment by DavidODonovan** [comment]
Each data point for confirmed cases on 13 March is equal to zero. Something is very very wrong.

**Comment by picklejason** [comment]
This happens almost every other day, sometimes for a few countries and sometimes everything is blank. I'm grateful that JHU is providing us this data but please have some sort of check before pushing it out because a lot of people depend on this dataset for their work. If something like this happens, everything gets messed up.

**Comment by marshallstanton** [comment]
Agreed about being grateful for the data but this situation is very frustrating.  JHU would be better off enlisting the help of the user community.

**Comment by ladris** [comment]
Until they get the mass commit/pull abuse from the Chinese and Taiwanese
under control that might be a pandoras box.

**Comment by marshallstanton** [comment]
Fair point, but until then people are going to other sources (https://www.worldometers.info/coronavirus/).

**Comment by ExpDev07** [comment]
A lot of apps are showing 0 now as the latest amounts, including my API :/.

**Comment by Oneiros90** [comment]
[Our little prediction model](http://bit.ly/PREDCOVID) went down because of this issue.
Tip: if you're using [Pandas](https://pandas.pydata.org/), use [dropna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) to drop null values

**Comment by williamlidata** [comment]
Gathering all the data every day is an understandably, monumental task. The community is ready to help, let us!

**Comment by ctc** [comment]
Alternative: https://ourworldindata.org/coronavirus-source-data

**Comment by eclipse2019** [comment]
![](https://i.imgflip.com/3sj884.jpg)

**Comment by mmonfort2908** [comment]
they've now pulled it back to the 12th so there is no ZERO data issue for the 13th. However, will be good to get an update once that's going. 

Thanks again for this JHU. Such a great resource!

**Comment by shahesam84** [comment]
I bet there's an invalid syntax in their code and no one can find it ;)

thanks JHU

**Comment by CSSEGISandData** [comment]
Due to the technical issues with the dashboard, 03-13-2020.csv has incomplete data. We have updated this csv to include the proper data update as well as the time series tables.
