### ISSUE TITLE
Found 3 different date formats

### ISSUE THREAD

**Issue by MassiveNoobie** [CSSEGISandData/COVID-19#766]
M/d/yy H:mm 393 records
M/d/yyyy H:mm 167 records
yyyy-MM-dd'T'HH:mm:ss 4937 records

**Comment by MassiveNoobie** [comment]
Solution to above data problem is found here in this json file...
https://github.com/MassiveNoobie/COVID19/commit/20f538c5cb9e756d7ac68b6f9e222bb0057ecdd4?diff=unified

**Comment by cipriancraciun** [comment]
@MassiveNoobie Given how many people are already using this dataset in the current format, I think such a change would break everything once more.

Moreover, in order to keep things tidy and help the JHU team, would you consider closing this issue and following #318 which discusses the same subject and seems to have the most up-votes.

**Comment by MassiveNoobie** [comment]
Makes since to me, sorry late in the game, noticed some strange null values in my error handling for these 3 pipelines too.
![Screen Shot 2020-03-22 at 9 24 01 AM](https://user-images.githubusercontent.com/32969167/77805393-c4850280-704f-11ea-9bcb-8f7a493cbb7c.png)

the last of the 3 data pipeline seams to catch nulls and broke a few days ago, not that ive been able to mentally keep up with fixing these death pipelines..

Power to yall for keeping it up, closing this!

**Comment by MassiveNoobie** [comment]
Found 4 dates. 
![Uploading Screen Shot 2020-04-05 at 8.59.29 AM.png…]()

**Comment by MassiveNoobie** [comment]
4 dates found. 
<img width="181" alt="Screen Shot 2020-04-05 at 10 21 01 AM" src="https://user-images.githubusercontent.com/32969167/78502527-2c5ddc00-7727-11ea-907f-d5d1041d08af.png">
