### ISSUE TITLE
Number of deaths in Italy and France 3/11 and 3/12 

### ISSUE THREAD

**Issue by ktheis** [CSSEGISandData/COVID-19#785]
In the file  COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv, the number of cumulative deaths in Italy for these two days are both 827, and for France they are both 48. Looking at the daily report  COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv, it says 1266 and 79 respectively, with a last update of 2020-03-11T20:00:00.

Could you check whether there was a mistake in manually updating that day? It seems inconsistent internally, when comparing with other sources and when plotting fatalities against time.

**Comment by skr47ch** [comment]
Please search before opening an issue.
 There's already enough questions on this exact issue. The issue is there, we've asked them to fixed it. Some have provided the correct data, some have even created pull requests. We are all waiting on the team to fix these numbers.

Creating more issues will not help.

**Comment by ktheis** [comment]
Excellent!

--
Karsten Theis
Chemical & Physical Sciences Department
Westfield State College
________________________________
