### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by bkh148** [CSSEGISandData/COVID-19#791]
Maybe (most likely) me who missed it but I get the feeling the data of infected need a very huge disclaimer since most countries (especially northern Europe) is running out of tests and most countries don't do CT scans (at least to my knowledge).

_Maybe something in the line of:_
Number of positive tested **is not** equal the number of infected. It's the absolute lower bound of infected. Different countries applies different testing strategies, has different ability to perform testing and different inventory of test or test-material. According to published articles a lot of disease-carriers get very limited symptom of Sars-Cov-2.

**Comment by MassiveNoobie** [comment]
Great points, very true. Testing is a requirement to being confirmed or considered a death, for sure there's going to be a large percentage of "nonpriority" sickness that can't be accounted for due to economics. Good point, I believe as we display these data visualizations we should also explain this as a part of the due diligence.

**Comment by MassiveNoobie** [comment]
From my research, I'm hearing people who are not dealing with a major illness, are considered non-priority and recommended that quarantine at home. These are "non" counted cases and due to the dependency of a "test" rendering a positive for covid-19, it does suggest these values can be used to build a formula to forecast and weigh using true population data. Similar to italy being 5.45X less population than the USA as of 2018 population stats. We can use that to understand the speed or growth patterns with some quick multiplication. So although there should be a disclaimer, it's still a good thing we are keeping track of a sample set.

**Comment by bkh148** [comment]
@MassiveNoobie Just to be super-clear its the best we got and super credit to @enshengdong @hongru94 for managing it.. But the data is referenced A LOT  i.e in newspapers and other publications hence I believe it would be great with a disclaimer/description in the readme.md file to clarify that its the absolute lower-bound of positive infected att every point in time and so on son on. So people not normally on GitHub or using open-source data understand its at biased sample space in some sense and most likely don't represent the true sample space.

**Comment by MassiveNoobie** [comment]
Understood, good idea.

**Comment by JimBudde** [comment]
Just curious, where is the "infected" nomenclature you are referring to?  I only see "confirmed", "deaths" and "recovered" stats in this data set.  And for the record, data is nearly *always* nuanced.  The media, and any other casual consumer may misinterpret whatever visual we might produce.  It's our job to mitigate misinterpretations as much as possible.

**Comment by MassiveNoobie** [comment]
Kudos where kudos deserved @bkh148, but if this was my responsibility I would have given away the tools and shown 100% transparency into HOW data pipelines are built from end to end, VS using this as the "output" hub, which imho, this is nothing more than gate keepers in a regular organization. However, lots of kudos for kick starting the idea, im sure it was daunting however i find more bugs and problems in this than anything ive developed for fortune 2 and below, with that said i dont think we need WIZARD LEVEL ETL processes to pipe a pdf file and a couple html scrapes, i just dont because it's not that hard.

if there was row level understanding of bugs, id be happier, however there's just nothing, a black box data problem that has only generated more confusion than anything.

So yeah, kudos, but i'd be fired af if this was my day job. Super fired.
