### ISSUE TITLE
Data is wrong for Denmark (15/03/2020)

### ISSUE THREAD

**Issue by JLTastet** [CSSEGISandData/COVID-19#838]
The number of confirmed cases is currently wrongly reported as 1739 on the dashboard, while the official figure from the [Statens Serum Institut](https://www.ssi.dk/aktuelt/sygdomsudbrud/coronavirus) is 898. This matches the number reported by [politi.dk](https://politi.dk/coronavirus-i-danmark/foelg-smittespredningen-globalt-regionalt-og-lokalt). See also #579.

**Comment by b2m9** [comment]
The data itself is actually correct, the [csv has 864 cases for yesterday](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv). There must be something wrong with the arcgis side of things. I assume double counting DK plus Faroe: `(864 * 2) + 11 = 1739`

**Comment by JLTastet** [comment]
Yes. That makes sense. There must have been some confusion between new cases and total cases. Do you know if there is an upstream issue?

**Comment by b2m9** [comment]
Johns Hopkins is using the repo here mostly as a data dump. There's no information available on how they build the ArcGIS layer, the web site viz or what script they use to accumulate the numbers. I assume those poor devils just try to  make sense out of the cluttered data from all over the world as good as they can. Don't know what upstream even is in this case - probably someone's computer.

That being said, the underlying ArcGIS layers are actually linked - one layer for the default view by country, second layer for every province/state.
The second layer (by province, dependency, or state) is actually correct: it shows DK with 864 and FI with 11: https://www.arcgis.com/home/webmap/viewer.html?useExisting=1&layers=c0b356e20b30490c8b8b4c7bb9554e7c&layerId=1
However, when they group territories into countries, they screw up: https://www.arcgis.com/home/webmap/viewer.html?useExisting=1&layers=c0b356e20b30490c8b8b4c7bb9554e7c&layerId=2
You can also see that on the website that the default view is wrong but when you move over to "Province/State/Dependency" the numbers are correct.
Since it's not clear how they build the ArcGIS layer, there's no way of knowing where double counting occurs. 

However, this happened before on Friday or so. I assume someone just copied the row for DK and that's why it was double counted. It was fixed 24h later. Someone probably realized that there are two entries for DK.

**Comment by JLTastet** [comment]
I see! Thanks for the info. I guess I can close this issue.
